### ISSUE TITLE
trigger type components compositions doesn't work

### ISSUE THREAD

**Issue by giladv** [radix-ui/primitives#1051]
it's impossible to use the same element to trigger both a tooltip and a dropdown menu.
(see attacked code sandbox)
to make it work you need to put pass refs to the children (which means wrapping tooltip/dropdown each in separate components)

option 1 doesn't work. option 2 works but it seems like 1 should work as well.
[live example](https://codesandbox.io/s/radix-ui-example-forked-bbpse?file=/src/index.tsx)

**Comment by jjenzz** [comment]
These examples are behaving correctly because you have applied `asChild` to the `Dropdown.Trigger` and its child is the `Tooltip.Root` so it will become the `Tooltip.Root`. If you want `<Dropdown.Trigger asChild />` to become the tooltip trigger, then its child has to be the `Tooltip.Trigger` instead because the `asChild` prop clones props onto its immediate child.

The reason your option 2 example works is because you are redirecting those props that `asChild` forwards onto your `Tooltip.Trigger` which is the correct way to achieve it. You don't need to do `React.cloneElement` yourself though because `asChild` does that for you https://codesandbox.io/s/suspicious-noether-uclyg?file=/src/App.js

In future if you're having trouble with syntax, please can you raise a Discussion instead? We can convert it to an issue if necessary from there.
