### ISSUE TITLE
[Popover] renders behind parent [DropdownMenu]

### ISSUE THREAD

**Issue by teddyty** [radix-ui/primitives#1072]
## Bug report
I observed an issue where a DropdownMenu that renders a Popover displays the Popover behind the menu, obfuscating much of the Popover.

### Current Behavior
The Popover (in red) is behind the Dropdown, even though its a child of the Dropdown component:
<img width="643" alt="Screen Shot 2022-01-06 at 11 39 12 AM" src="https://user-images.githubusercontent.com/87341995/148441326-50d78c91-3e5e-4d9d-8685-3e94b1856fe6.png">

### Expected behavior
I would expect the Popover to be rendered above the Dropdown so thats its contents are fully visible.

It seems like this has something to do with the ordering of the portals rendered by the Popover and DropdownMenu..

### Reproducible example
[Please look at this CodeSandbox that reproduces this issue](https://codesandbox.io/s/portalzindexissue-1xl44?file=/src/App.tsx)

### Your environment

Package versions and dependencies are in the sandbox!

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |   0.1.4      |
| React            | n/a     |    17.0.1     |
| Browser          |  chrome       |Version 96.0.4664.110 (Official Build) (x86_64)         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |      osx   |    11.2.3     |

**Comment by benoitgrelard** [comment]
Hi @teddyty,

Thanks for opening this issue.
You are correct that right now as they are all using the max z-index, it will depend on order of opening, hence why you see the issue here. We have recently introduced a change to the dialog primitives, where we expose the portal part and give you full control of the z-index layering. If/when we bring this to all other primitives, you'd be able to solve this.

That said, I have to ask a few questions based on your example:
- What are you trying to achieve by having a popover inside a specific dropdown menu item? Or is it a contrived example? If so, what is the real thing that led you here?
- Another thing I'm wondering is why would you auto-open the second thing (here the popover), it doesn't seem to make sense UX-wise anyway.
- The DropdownMenu primitive is a very specific UI/accessibility pattern aimed to replicate similar menus you have in your OS for example, so generally shouldn't really diverge from using the provided parts.

Let us know!

**Comment by teddyty** [comment]
Hi @benoitgrelard, thank you for replying.

> What are you trying to achieve by having a popover inside a specific dropdown menu item? Or is it a contrived example? If so, what is the real thing that led you here?

This is a real-life use case where we want to display a dropdown menu that has tooltips (in the form of popovers) that we would display _upon hovering_ a menu option. The tooltips would provide some additional information on what the menu options do.
> Another thing I'm wondering is why would you auto-open the second thing (here the popover), it doesn't seem to make sense UX-wise anyway.

Agreed - this part of the example is contrived. The popover would be hidden by default and would display on hover. When I remove the auto-open functionality, the dropdown works as expected. I ran into the issue I reported while lazily trying to test my work with the tooltips open by default so that I wouldn't have to hover over them to see how they looked.

>We have recently introduced a change to the dialog primitives, where we expose the portal part and give you full control of the z-index layering.

Sounds like this would sufficiently address the issue described here. Thank you again for taking a look!

**Comment by benoitgrelard** [comment]
> This is a real-life use case where we want to display a dropdown menu that has tooltips (in the form of popovers) that we would display upon hovering a menu option. The tooltips would provide some additional information on what the menu options do.

Would they be tooltips or popovers? Tooltips work on focusing/hovering the trigger, so that might make sense. Popover work on click so I'm not sure how that would work considering that clicking on an item will action it and close the menu…

> I ran into the issue I reported while lazily trying to test my work with the tooltips open by default so that I wouldn't have to hover over them to see how they looked.

In any case, if you aren't going to auto open it then am I ok to assume your issue is a non-issue then?
If so, feel free to close this github issue.

**Comment by teddyty** [comment]
> Would they be tooltips or popovers? Tooltips work on focusing/hovering the trigger, so that might make sense. Popover work on click so I'm not sure how that would work considering that clicking on an item will action it and close the menu…

Because of some aesthetic differences between our popovers and tooltips we happen to be using an on-hover popover in this case that is functioning like a tooltip, (although maybe that will change later).

I will close this issue out, thank you for the help!
