### ISSUE TITLE
[Popper] Make it aware of remaining available height/width

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/primitives#1095]
### Overview

Stemmed from https://github.com/radix-ui/primitives/discussions/1081
It would be good to find a way to make Popper aware of the available height/width so people can cap it.

### Additional context

A potential suggestion I made here would be to expose some CSS custom properties so people can opt-into that behaviour by setting a `maxHeight` for example: https://github.com/radix-ui/primitives/discussions/1081#discussioncomment-1962412

**Comment by benoitgrelard** [comment]
Yeah I know, I thought of this too, it's so hard to draw the line haha.

It felt quite similar to what we do in collapsible/accordion for the animation, and in fact potentially even more justified given we already have the measurements available so doesn't incur any more cost, as opposed to when re-measuring user-side?
Additionally, if doing it manually there are other things to consider like the gap we leave around, which for us would be baked in in our calculations, as opposed to users having to "figure it out" and include it in their calcs.

But as you say, where do we draw the line…

**Comment by jjenzz** [comment]
I think the baked in functionality would always be what the majority expectation is.

For `Accordion`, most people tend to animate the item height and it was requested a lot before we implemented it. It's also not easy for consumers to do and the data we're providing is about the parts themselves so is applicable regardless of use-case. It's "design system" layer information.

In the `Popover` case, the requested data isn't "design system". It's the size of the remaining space in their particular product viewport minus the space above the popover. Also, what if someone else wants it to fill the space in a particular container and not the viewport? Now the `--max-height` is wrong or we need a `container` prop to adjust the `--max-height`. Our API starts to balloon because of a specific use-case. It seems a good example of why we keep our APIs open.

> Additionally, if doing it manually there are other things to consider like the gap we leave around,

The `maxHeight` would always prevent collision detection so the calculation I have in the sandbox would handle the gap right? https://codesandbox.io/s/charming-cannon-1n71w?file=/src/App.js.

**Comment by benoitgrelard** [comment]
> The maxHeight would always prevent collision detection so the calculation I have in the sandbox would handle the gap right? https://codesandbox.io/s/charming-cannon-1n71w?file=/src/App.js.

Yes I wasn't referring to the "side" gap but to the gap between the edge of the viewport and the content, but I just realised now that it's not really a thing in `Popper`, I'm too deep in `Select`! haha (you know that 10px we keep around).

There's something equivalent I guess which is the `collisionTolerance` but they have control of it, so that still works anyway.

I'm happy to go either way with this to be honest, I do agree it's not quite as demanded as the accordion stuff. I'll update that person about it and we can keep monitoring if it comes up. In the meantime, happy for me to close the issue?

**Comment by jjenzz** [comment]
Yeah let's close for now 👍
