### ISSUE TITLE
Error thrown when testing dropdown menu

### ISSUE THREAD

**Issue by mrseanbaines** [radix-ui/primitives#1124]
## Bug report
I've run into an issue when trying to test my dropdown component that uses `@radix-ui/react-dropdown-menu` as the base. The issue seems to be around the trigger element, when I try to mock a click event on it, it throws various errors. In my actual project, I get this error:

```sh
ReferenceError: DOMRect is not defined
```

and in the reproducible example, there is one error like so:

```sh
The provided value is not of type 'Element'.
```

and a bunch of stack traces in the console.

I ran into this error in my project after refactoring a fully custom-built dropdown to use the Radix base. Tests were passing before so I assume it's an issue with this component.

### Current Behavior

Tests throw errors as soon as I mock a click event on the dropdown trigger

<img width="1973" alt="image" src="https://user-images.githubusercontent.com/24367010/151665892-2068f714-3760-4da5-a171-8319bac8c7ea.png">

### Expected behavior

No error to be thrown

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/wizardly-frost-ru97f?file=/src/dropdown.test.js)

### Your environment
```json
  "dependencies": {
    "@radix-ui/react-dropdown-menu": "0.1.4",
    "@radix-ui/react-icons": "1.0.3",
    "@testing-library/react": "12.1.2",
    "@testing-library/user-event": "13.5.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-scripts": "4.0.0"
  },
  "devDependencies": {
    "@babel/runtime": "7.13.8",
    "@types/jest": "27.4.0",
    "typescript": "4.1.3"
  },
```

**Comment by benoitgrelard** [comment]
Hey @mrseanbaines,

This because test environments aren't always full representation of the the DOM/engine.
Have a look at this comment which should explain what you need to do: https://github.com/radix-ui/primitives/issues/420#issuecomment-771615182
Also, some other relevant threads on this search: https://github.com/radix-ui/primitives/search?q=DOMRect&type=issues

I'll close the issue for now, but feel free to keep discussing on it or re-open if you think I haven't addressed your concerns.

👍

**Comment by mrseanbaines** [comment]
Thanks @benoitgrelard! The solution you linked solved the issue.

I definitely did a little Googling before opening the issue but think I forgot to search the issues 🙈.
