### ISSUE TITLE
[Dialog] scrolling issue with react-select inside

### ISSUE THREAD

**Issue by davidavz** [radix-ui/primitives#1128]
### Current Behavior

I'm using a `react-select` component inside of a `Dialog` component, I had to add a `pointer-events: auto` to deal with visibility issue but now I'm facing a scrolling issue with my menu list.

### Expected behavior

The mouse wheel should works well

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/react-select-inside-radix-dialog-scroll-issue-y105v)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-dialog | 0.1.5 |
| React            |  | 17.0.2 |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by davidavz** [comment]
The issue is present only when the list has a long overflow (I have a small screen but you should reproducing it adding more items on the list

https://user-images.githubusercontent.com/6774576/151835277-7f1cdae6-f60a-4326-9939-557198e30b19.mov

)

**Comment by davidavz** [comment]
Hi 👋 

I'm still trying to resolve this but for the record, I'm facing the same issue with : 
- Material UI Autocomplete component https://codesandbox.io/s/mui-autocomplete-inside-radix-dialog-2hgw1p
- Your Select component https://codesandbox.io/s/radix-select-inside-radix-dialog-5lwgym

**Comment by benoitgrelard** [comment]
Hey @davidavz, the one with ours works as far as I can tell.

**Comment by davidavz** [comment]
My bad !
I didn't know the behavior of this component when scrolling.

**Comment by fgatti675** [comment]
I am having issues with the Radix Dialog and the Radix select.
It only happens if position is set to "popper" apparently

**Comment by ansh-les** [comment]
Facing the same issue!

**Comment by skysarwer** [comment]
> I am having issues with the Radix Dialog and the Radix select. It only happens if position is set to "popper" apparently

I am also have the same issues with the Radix Select nested within the Radix Dialog.

**Comment by vtkachenko-deeploi** [comment]
Replacing RadixUI `DialogOverlay` with self-written fixed the issue for me.
```
const DialogOverlay = forwardRef<HTMLDivElement, StyleProps>((props, ref) => {
    return (
        <div
            ref={ref}
            css={css`
                z-index: 100;
                position: fixed;
                pointer-events: none;
                inset: 0;
                background-color: rgba(0, 0, 0, 0.2);
            `}
        />
    )
})
```
and my react-select component is something like
```
const MultiSelect: FC<MultiSelectProps> = ({ options, selectedOptions, onChange, testId }) => {
    return (
        <Select
             menuPortalTarget={document.body}
             menuPosition="fixed"
             styles={{
                menuPortal: (defaultStyles) => ({
                    ...defaultStyles,
                    zIndex: 1100,
                    pointerEvents: 'all',
                }),
```

**Comment by jamesl1001** [comment]
I'm experiencing this issue with Radix's AlertDialog and react-select where the scroll wheel refuses to work on a long list of options when the select is inside of the AlertDialog.

And I finally figured out what’s causing this bug!

When the AlertDialog is opened, Radix registers `touchmove` and `scroll` event listeners on `body` which essentially block these two events for anything that’s not in the AlertDialog.

![Screenshot 2024-07-19 at 15 45 10](https://github.com/user-attachments/assets/a75bd49f-5e58-4143-83a6-18fc95448189)

This is implemented using `react-remove-scroll` [here](https://github.com/radix-ui/primitives/blob/main/packages/react/dialog/src/Dialog.tsx#L203). This `<RemoveScroll>` component is saying, only allow scroll on its children and any references passed into the `shards` prop (which in this case, is the `AlertDialog.Content`).

The problem therefore occurs because, by default, `react-select`’s `menuPortalTarget` is set to `document.body`, which cannot be scrolled.

This is exactly what `react-remove-scroll` warns of [here](https://github.com/theKashey/react-remove-scroll?tab=readme-ov-file#over-isolation).

I’ve confirmed this because removing the event listeners using Chrome’s devtools immediately fixes the bug.

@benoitgrelard @jjenzz I'm wondering whether Radix would consider surfacing this `shards` prop to allow developers better control over scrollable portals? 🙏🏻

**Comment by buyonjederrick** [comment]
> menuPortalTarget={document.body}
>              menuPosition="fixed"
>              styles={{
>                 menuPortal: (defaultStyles) => ({
>                     ...defaultStyles,
>                     zIndex: 1100,
>                     pointerEvents: 'all',
>                 }),

This worked fine for me with shadcn Dialog

**Comment by neilpoulin** [comment]
For shadcn users, [this comment](https://github.com/shadcn-ui/ui/issues/1175#issuecomment-2228543893) seems to fix all of the problems for me. 

Summary: Update your `<DialogContent>` component to place your `<DialogPrimitive>...</DialogPrimitive>` as a _child_ of `DialogOverlay` instead of a sibling.

**Comment by fgatti675** [comment]
@benoitgrelard 
> Given we now have our own `Select` and this seems to be rather a 3rd party compatibility issue, we won't be prioritising it.

I am facing the same issue with the native Radix Select component. I feel this is an issue with the Dialog component, considering it is impacting so many select alternatives.

@jamesl1001 seems to have found the issue.
Would it make sense to reopen this ticket?
Thank you

**Comment by jamesl1001** [comment]
> Replacing RadixUI DialogOverlay with self-written fixed the issue for me.

This solution by @vtkachenko-deeploi worked for my Radix AlertDialog / react-select incompatibility 🥳 

This makes sense since it's the `<AlertDialog.Overlay />` which implements the aforementioned `react-remove-scroll`; however, I'm unsure whether this fix will cause any further side-effects since [there's a whole bunch of other code here](https://github.com/radix-ui/primitives/blob/main/packages/react/dialog/src/Dialog.tsx#L162-L214).

Here's my fix:

```
const AlertDialogOverlay = () => (
  <div className="<styles with a lower z-index>" />
);

const AlertDialogContent = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Content>
>((props, ref) => (
  <AlertDialogPrimitive.Portal>
    <AlertDialogOverlay />
    <AlertDialogPrimitive.Content
      className="<styles with a higher z-index>"
      ref={ref}
      {...props}
    />
  </AlertDialogPrimitive.Portal>
));
```
