### ISSUE TITLE
[Tooltip] Ability to follow cursor position

### ISSUE THREAD

**Issue by jjenzz** [radix-ui/primitives#1178]
I'm not entirely sure if tooltip would be the correct a11y pattern for this but we can investigate that if team thinks this is worth supporting.

### Discussed in https://github.com/radix-ui/primitives/discussions/1090

<div type='discussions-op-text'>

<sup>Originally posted by **Rednegniw** January 16, 2022</sup>
Hi, first, amazing library! So thank you very much for developing it. 

Just had an idea - it would be cool if there was a component such as a tooltip that would follow the mouse/cursor position while hovering over an element. It might interesting, for example, when you want to tell the user why they can't click on a disabled element and so on.

Something like this - https://codepen.io/paulvddool/pen/mROEGa (not mine, found randomly on google)</div>

**Comment by benoitgrelard** [comment]
We probably won't do this anytime soon, so closing for now.

**Comment by jjenzz** [comment]
why are feature requests being closed? i don't understand the harm in them remaining otherwise it seems it will just deter people from providing valuable suggestions.

**Comment by benoitgrelard** [comment]
Thanks for raising this @jjenzz.

We looked into it a bit further and it looks like it isn't something we would consider for Radix given that it would go against an accessibility criterion which are actively working towards: #620.

So rather than "not doing this anytime soon", we can clarify to say this isn't something we would consider as it breaks accessibility.

**Comment by jjenzz** [comment]
that makes sense in terms of tooltip, i wonder if this could be a different component though?

**Comment by benoitgrelard** [comment]
Given that criteria, I don't think this is possible as an accessible component, given that it shows on hover, that criteria would then be impossible to fulfill.

**Comment by jjenzz** [comment]
The a11y in my mind would be to `aria-hidden` it. Similar to how `HoverCard` is for sighted users only. It would be nice to explore the a11y of these types of cursors as it is a common pattern these days.

**Comment by benoitgrelard** [comment]
Is it really a common pattern? I don't think I have ever seen this in the wild.

**Comment by jjenzz** [comment]
i've seen it quite a bit recently. vercel did it on their conference marketing website, figma do it for multiplayer, looks like framer do too etc.

**Comment by benoitgrelard** [comment]
Right, I guess that's a completely different pattern, more like these "live cursor" things rather than a tooltip, so not really linked to a trigger area either. It's not even really something that follows your own cursor really, it's more that you have the representation of a fake cursor with a bubble attached to it.

I'm not sure this fits well within Radix personally, but if you think there's some value Radix could provide there, feel free to submit a new primitive request.

**Comment by jjenzz** [comment]
yes that's what i meant by "multiplayer cursors" and is the reason why i said in the original ticket description that i am not convinced tooltip is the right patter for this 🙂

**Comment by benoitgrelard** [comment]
Personally I feel like this is VERY niche when compared to a pattern like `HoverCard`, and so probably better handled by more dedicated solutions like LiveBlocks (who incidentally also use Radix 😀).

**Comment by jjenzz** [comment]
I don't think liveblocks provide the components, just the websockets stuff. but yeah, it's not as common as `HoverCard`. So is radix stance now to close any requests that might be becoming popular but not currently common enough?

**Comment by benoitgrelard** [comment]
> So is radix stance to close any requests that might be becoming popular but not currently common enough?

No, not at all! The original request was for this feature to be added to `Tooltip` which isn't valid because of accessibility reasons.

But like I said here 👇, this is something we can add as a new primitive request although it would be good if we can formulate a bit better what the component actually is.

> I'm not sure this fits well within Radix personally, but if you think there's some value Radix could provide there, feel free to submit a new primitive request.

**Comment by jjenzz** [comment]
Yeah sure, if that helps avoid confusion can do that.

**Comment by vincerubinetti** [comment]
I think the most useful case for this is when the hover target has an odd concave shape, like say on a map. Making the tooltip be anchored to the mouse instead of the actual reference element would just be a simple way to position the tooltip, rather than finding the centroid of the shape or something like that.

I don't see how it goes against accessibility... the anchor point would follow the mouse, but the tooltip would flip/shift/etc. to keep it visible like it does in any other context.

Other libraries like Tippy.js have this.
