### ISSUE TITLE
Tooltip.Content doesnt work with left side atrribute, and without asChild attribute Children element gets white background

### ISSUE THREAD

**Issue by rafae2k** [radix-ui/primitives#1198]
### Current Behavior

When attribute ```asChild``` is used on Tooltip.Content component only bottom side tooltip works.

when removed ```asChild``` attribute, tooltip primitive works on all sides but background get's white.

<img src="https://i.imgur.com/dCf3IQ6.png" />

### Expected behavior

Child component in Tooltip.Content should not have this white background when ```asChild``` attribute is setted.

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/dark-sky-vybxwz?file=/src/components/Tooltip/index.tsx)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    tooltip     |     ^0.1.6    |
| React            | n/a     |     ^17.0.2    |
| Browser          |    Chrome     |     98.04    |
| Assistive tech   |    n/a     |     n/a    |
| Node             | n/a     |         |
| yarn         |         |     2    |
| Operating System |     macOS    |    BigSur     |

**Comment by benoitgrelard** [comment]
Hi @rafae2k,

I'm not sure I'm following what you mean entirely, if you could reduce it to some simpler example that would be great.
Here are a few issues I see though:

- `Tooltip.Trigger` is a `button` already, but you are putting a `button` inside that. If you want the functionality of the trigger, but using your own buttons, use the `asChild` prop on `Tooltip.Trigger` and make sure that whatever button you put inside:
  - forwards ref
  - forwards props
- Regarding the `side` stuff, not sure I follow again, but perhaps you are getting confused because it is hitting boudaries? Not matter what side you ask for, if the tooltip cannot be positioned there because it hit edges of the windows, it will reposition itself so it is still visible.

Happy to help more if you can refine a sandbox with your particular issues cause right now it's a bit difficult to know what you are talking about.

✌️

**Comment by rafae2k** [comment]
Thanks for your reply benoit,

I apologize if I wasn't clear in my issue.

As you can see what I'm trying to build is a UI exercise and for that I'm using Radix and Stitches to replicate the discord interface.

I created a buttons component for the server bar and created a generic Tooltip component as per the Radix documentation.

the structure is as follows:

```
export interface Props {
  name: string;
  icon: ReactNode;
  side?: 'bottom' | 'left' | 'right' | 'top' | undefined;
}

const Tooltip: React.FC<Props> = ({ name, icon, side = 'bottom' }) => {
  return(
    <Provider delayDuration={200} skipDelayDuration={500}>
      <TooltipRoot>
        <TooltipTrigger>{icon}</TooltipTrigger>
        <TooltipContent side={side} sideOffset={5}>
          <StyledArrow />
          {name}
        </TooltipContent>
      </TooltipRoot>
    </Provider>
  );
};

export default Tooltip;
```

My server button has the follow structure:

```
export interface Props {
  selected?: boolean;
  isHome?: boolean;
  hasNotifications?: boolean;
  mentions?: number;
}

const ServerButton = React.forwardRef(({
  selected,
  isHome,
  hasNotifications,
  mentions,
}, ref) => (
  <Button
    isHome={isHome}
    hasNotifications={hasNotifications}
    mentions={mentions}
    className={selected ? 'active' : ''}
    ref={ref}
  >
    { isHome && <img src={Discord} alt="Server logo" /> }
  </Button>
));

export default ServerButton;
```

then i render my button with tooltip in my ServersList component as follows:

`<Tooltip name='Server Name' icon={<ServerButton isHome />} />`

where icon is the component that will activate the tooltip, in this case I specify the server button component.

When I use my generic tooltip component in an icon component, for example, the ones on the top bar, and I have the asChild attribute in my tooltip, everything works perfectly, however, when using on my server button, the ones on the left sidebar , no tooltip is shown.

In this case I'm rendering the exact same way as above and my Top buttons is just an styled component.

When removing the asChild attribute from my generic tooltip component, the tooltip appears as expected both on the top bar buttons and on the server buttons on the left sidebar. However, this way, the entire component box has a white background.

I turn around it by coping my tooltip generic and wrapping it in my ServerButton component.

I'm sorry if i report my implementation problem as a bug issue.

**Comment by benoitgrelard** [comment]
Yes I see, so as I pointed out, there are a few issues in your implementation.

Your `ServerButton` should forward both `ref` and `props`:

```diff
const ServerButton = React.forwardRef(({
  selected,
  isHome,
  hasNotifications,
  mentions,
+ ...props,
}, ref) => (
  <Button
    isHome={isHome}
    hasNotifications={hasNotifications}
    mentions={mentions}
    className={selected ? 'active' : ''}
    ref={ref}
+ {...props}
  >
    { isHome && <img src={Discord} alt="Server logo" /> }
  </Button>
));
```

Additionally, because what you are passing as `icon` to your `Tooltip` abstraction already renders a button, your `Tooltip.Trigger` needs to use `asChild` so it uses the functionality of the trigger, without itself rendering another button (otherwise you end up with a button within a button). Also, the tooltip `Provider` should wrap your entire app, not every single tooltip:

```diff
const Tooltip: React.FC<Props> = ({ name, icon, side = 'bottom' }) => {
  return(
-    <Provider delayDuration={200} skipDelayDuration={500}>
      <TooltipRoot>
-        <TooltipTrigger>{icon}</TooltipTrigger>
+        <TooltipTrigger asChild>{icon}</TooltipTrigger>
        <TooltipContent side={side} sideOffset={5}>
          <StyledArrow />
          {name}
        </TooltipContent>
      </TooltipRoot>
-    </Provider>
  );
};
```

```diff
function App() {
  return (
-    <>
+    <Provider>
      <Layout />
      <GlobalStyles />
-    </>
+    </Provider>
  );
}
```

Your problem with the buttons at the top then is that in that place you are doing the opposite, instead of passing a button which contains an icon in it, you're passing only the icon. So in this case, you would have to actually style the `Tooltip.Trigger` and not use `asChild`.

But to keep things consistent, I would recommend that you use the same abstraction everywhere and simply always pass in your own button.

I think you might have misled yourself by calling the prop `icon` really.

Have a look at this abstracted implementation of a tooltip in our docs, I feel like it would be easier to understand and more consistent to use: https://www.radix-ui.com/docs/primitives/components/tooltip#custom-apis

You would use it like this in your server list:

```tsx
<Tooltip content="Servidor do Rafo">
  <ServerButton hasNotifications />
</Tooltip>
```

and like this in your toolbar:

```tsx
<Tooltip content="Fixed Messages">
  <Button>
    <FixedMessages />
  </Button
</Tooltip>
```

I hope that makes sense 👍

**Comment by rafae2k** [comment]
Thank you @benoitgrelard, i have refactor by forwarding ref and works great now.

I think I made a mistake in understanding the API, i didnt know the trigger was an actually a button 🤦‍♂️. 

But everything became crystal clear after your answer.

Sorry to reporting a non-existent bug, hope to contributing more with this amazing lib in the future.

**Comment by benoitgrelard** [comment]
No worries! Glad I could help!
