### ISSUE TITLE
Dialog Closing issue when multiple dialogs stacked on top of each other

### ISSUE THREAD

**Issue by acharyarupak391** [radix-ui/primitives#1249]
### Current Behavior

I have a Dialog component(say **Dialog1**) which opens **_another_** Dialog component(say **Dialog2**) when a button in **Dialog1** is clicked. But when I close the currently opened Dialog(i.e **Dialog2**), both the Dialogs get closed.

### Expected behavior

I expect only **Dialog2** to be closed when the close function is triggered. And the previously opened Dialog(**Dialog1**) to remain open.

### Reproducible example

[Stackblitz Template](https://stackblitz.com/edit/github-awjfn8?file=pages/index.tsx)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-dialog | 0.1.5 |
| React            | n/a     | ^17.0.2 |
| Browser          | Chrome       |   99.0.4844.51 (Official Build) (64-bit) (cohort: Stable)       |
| Assistive tech   |         |         |
| Node             | n/a     |   14.19.0      |
| npm/yarn         |  npm       |   7.17.0      |
| Operating System |     Linux    |         |

### Additional Packages

|  Name(s) | Version |
| ------- | ------- |
| next | latest |
| tailwindcss | ^3.0.7 |

**Comment by jjenzz** [comment]
your secondary model is being rendered outside of the primary modal which means clicking on it is considered "clicking outside primary modal". clicking outside will close the primary modal. it needs to be opened from inside it to be considered inside.

separately, please try to follow the provided api as closely as possible by using all of our parts unless otherwise labelled as optional in our docs. in your case, if you had used the required `Trigger` part you would have been forced to structure things correctly. 

the provided parts are there to ensure correct functionality/accessibility so you are missing `Trigger`, `Close` and `Title` which you appear to me manually creating separately. 

you can open dialogs without triggers but that should be a last resort and you are responsible for ensuring correct a11y if you decide to do that.

here is a working example: https://stackblitz.com/edit/github-awjfn8-8mjn3j?file=pages%2Findex.tsx

i have exposed separate parts to allow correct composition but if you prefer a more closed api you can provide the trigger, title and close parts as props. the exposed api is totally up to you.

**Comment by acharyarupak391** [comment]
@jjenzz  Thanks for this. I usually go for a controlled component since I have such requirements.

About the multiple Dialogs, I knew I can have the expected behavior if I nest one into another, but I was wondering if I can get the same behavior when they are used as different components(**sibling components**). 

The thing is, both those dialogs can **also** open separately(**i.e only one of them can also appear standalone**), but if one is nested into another, then for the inner Dialog to be open, the wrapper Dialog **must** open first.

So this is why I don't want to go for the nested structure.
Is there any solution to that?

**Comment by jjenzz** [comment]
i would propose re-using components instead of re-using "instances" for that use-case. you will find that the complexity of your app architecture will reduce (and benefit from tree-shaking) this way. here's a blog post i wrote on the topic https://jjenzz.com/avoid-global-state-colocate

**Comment by acharyarupak391** [comment]
Thanks @jjenzz 
I decided to go with the more recent version of the library(`@radix-ui/react-dialog`), `0.1.6`. 
Fortunately, for some reason, this version doesn't have that issue. I wanted to use the `0.1.5` version but I suppose I can make this adjustment. 
Thanks again.

**Comment by firxworx** [comment]
@jjenzz good examples + nice blog post :)
I agree with benefits of colocation and misusing global state.

I think a use-case that's missed with radix-ui apps that have valid reasons to auto-trigger modals and alerts, e.g. due to impending session timeout ("click to stay active"), an important connectivity or security update, or business apps where an urgent user decision is required e.g. regarding a real-time event or notification of high priority.

A stacked modal UX supports these cases and elegantly lets the user go back to what they were doing before being interrupted (and what they were doing could easily involve having a modal open for a multi-step flow, editing something, etc.). Users are very familiar with this pattern and won't get scared that the interruption lost their work or progress. 

AFAIK radix-ui Dialog doesn't seem capable of supporting these scenarios and its frustrating use of very intrusive third-party libraries for handling scrollbar widths + scroll lock that interfere with styles and are not configurable adds to the issues.

Please advise if I am mistaken here or if more recent updates have changed this situation!

In this type of situation the open modals and their stacking order have to be maintained. 
Check out https://github.com/mpontus/react-modal-hook for an example of a lib that understands the use-case.

This alternative way of conceptualizing modal triggers (via hook) supports use of a single overlay, portal, etc., and  various benefits for scroll-width adjusting, options for triggering / closing, etc.

**Comment by Lokeshsai0231** [comment]
hello actually i have a dialog 1 and in that dialog 1 there is another dialog 2, here my requirement is when i open the dialog 2 from dialog1 the dialog 1 close and only the dialog 2 should open, but here, iam not able to do that, i tried various ways, i cant handle it, anyone can please explain?
