### ISSUE TITLE
[Slot] `Slottable` not working as expected

### ISSUE THREAD

**Issue by tavoyne** [radix-ui/primitives#1261]
See https://github.com/radix-ui/primitives/discussions/1255

**Comment by tavoyne** [comment]
I'd be happy to work on a PR for that to work, but I'm not sure what you're trying to achieve with this `Slottable` component (please see the linked discussion). Please let me know.

**Comment by jjenzz** [comment]
my understanding was that given the following:

```jsx
const Comp = () => (
  <Slot>
    hello
    <Slottable>{children}</Slottable>
  <Slot>
);
```

usage:

```jsx
<Comp>
  <button>world</button>
</Comp>
```

should output:

```jsx
<button>
  hello world
</button>
```

but it's worth waiting for @benoitgrelard's input on this before making a start.

**Comment by tavoyne** [comment]
@benoitgrelard ?

**Comment by benoitgrelard** [comment]
After some investigation, it seems that the understanding we had of @jjenzz's use case higher up, was in fact never the case. As elements would become siblings rather than stay a parent/child. Once digging into the code, it is rather obvious to see why that is the case.

However, there is a legitimate reason why you would expect it to behave the way it has been described in this issue (and the linked discussion). It specifically becomes a lot more obvious in a "button with icons" scenario which doesn't rely on compound parts.

[This comment](https://github.com/radix-ui/primitives/discussions/1255#discussioncomment-2397051) is actually a good start as to how we would implement this in `Slot`. In fact we may be able to re-use some parts of internal slot logic for this.

We'll look into it.

✌️

**Comment by tavoyne** [comment]
Thanks for your reply @benoitgrelard.

I ended up implementing it myself. It works great. Here's what it looks like: https://codesandbox.io/s/trusting-star-85l8bg.

If you want, I can work on a PR. I think it would integrate nicely and not break any dependent component.

**Comment by jjenzz** [comment]
> was in fact never the case

i believe it was the intention as otherwise there is no need for the `Slottable` at all. we could have just done this https://codesandbox.io/s/elated-dubinsky-fbkl2o?file=/src/App.js

i believe @tavoyne's expectation was the intention for `Slottable` but looks like we never implemented it properly.

**Comment by benoitgrelard** [comment]
Yep, that's my thoughts exactly.
