### ISSUE TITLE
React 18

### ISSUE THREAD

**Issue by nicholaschiang** [radix-ui/primitives#1293]
React 18 is [here](https://reactjs.org/blog/2022/03/29/react-v18.html)! Does this library support it? I'm guessing it won't be too difficult to simply change your listed `peerDependencies` and support it, though I'm not sure how many of the new features this library would take advantage of...

**Comment by benoitgrelard** [comment]
Hi @nicholaschiang,

Generally yes, it is supported. We did a fair amount of testing prior the release of React 18.
That said, there's been a couple issues reported since it went public so we'll likely try and fix those before we upgrade the peer deps.

But it shouldn't stop you from using it with React 18 right now.

**Comment by electic** [comment]
Was trying this out. NPM seems to throw an error when installing this because the dependencies are pegged. Can someone confirm if this is supported?

npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8 || ^17.0" from @radix-ui/react-dropdown-menu@0.1.6
npm ERR! node_modules/@radix-ui/react-dropdown-menu
npm ERR!   @radix-ui/react-dropdown-menu@"0.1.6" from the root project

**Comment by benoitgrelard** [comment]
We'll have a PR up soon to make sure it's properly compatible with React 18, in terms of dependencies, types, etc.

**Comment by benoitgrelard** [comment]
#1329

**Comment by electic** [comment]
> #1329

One more thing it seems the same issue appears with icons too.

**Comment by benoitgrelard** [comment]
@electic, sorry I'm not following what you are talking about here?

**Comment by benoitgrelard** [comment]
Ah yeah maybe, seems we'll have to update that too 👍

**Comment by electic** [comment]
> @electic, in case that was what you were referring to, I've started a PR for it here: [radix-ui/icons#129](https://github.com/radix-ui/icons/pull/129)

Yup, it worked. Thank you for the update. UI-Icons still needs an update last time I checked.

**Comment by benoitgrelard** [comment]
> UI-Icons still needs an update last time I checked.

That's the PR that's up, once merged we'll publish a new version.

**Comment by electic** [comment]
> > UI-Icons still needs an update last time I checked.
> 
> That's the PR that's up, once merged we'll publish a new version.

Thank you!

**Comment by mentorkadriu** [comment]
Just created a new app using `npx create-react-app my-app --template typescript`. After that tried to install `npm install @radix-ui/react-checkbox@latest -E`. It looks most of radix ui primitives need fix to be able to use with react 18.
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-app@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8 || ^17.0" from @radix-ui/react-checkbox@0.1.5
npm ERR! node_modules/@radix-ui/react-checkbox
npm ERR!   @radix-ui/react-checkbox@"0.1.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by mentorkadriu** [comment]
Installing latest version `0.1.6-rc.8` which is not shown on npmjs fixes this issue. `npm install @radix-ui/react-checkbox@0.1.6-rc.8 -E`

**Comment by benoitgrelard** [comment]
Yeah, `@latest` is latest stable, `@next` is latest rc.
