### ISSUE TITLE
[Select] Select content is misaligned when defaultValue or value is not passed

### ISSUE THREAD

**Issue by suevalov** [radix-ui/primitives#1324]
## Bug report

When `value` or `defaultValue` is not passed `SelectContent` is misaligned.

### Current Behavior

<img width="985" alt="Screenshot 2022-04-13 at 10 31 46" src="https://user-images.githubusercontent.com/3672221/163134679-1bb21a6c-15d4-4aab-a67a-bff8b8fb9db9.png">

### Expected behavior

I think the behavior of the custom select should replicate the behavior of the native select and the first available option should be automatically selected in this case.

### Reproducible example

https://codesandbox.io/s/happy-leaf-oscbxo?file=/App.js

### Suggested solution

Automatically select first available option if `defaultValue` or `value` is not passed. Basically, the same behavior as with a native select.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  react-select       |   0.1.1      |

**Comment by benoitgrelard** [comment]
Hey Alex,

A few people have raised this (#1231, #1259, #1235).

It was intentional from our side to not copy that behaviour and rather rely on people providing a `defaultValue` or `value` seeing as it's likely you have one.

There are a couple reasons we think that native behaviour isn't great:
- in React land this would likely mean having to do a double render to pre-select the first valid option
- it's not necessarily great UX and we think providing something like first-class support for a placeholder instead would be a better solution to the problem at hand (that's the #1235 we currently have open)

Would love to hear if you have further thoughts on this though, or whether you came to it purely from the front of feeling like it should be like native.

✌️

**Comment by suevalov** [comment]
@benoitgrelard Thanks for the response. I understand the reasoning and I think that Placeholder component (#1235) makes sense.

Nevertheless, I think it would be great to fix position of the popup and it align it properly when the value or default value is not passed.

**Comment by benoitgrelard** [comment]
Yeah regardless of placeholder, we could default to aligning with the first option even if it's not "selected" like in the native case. That might be a good improvement to do first 👍
