### ISSUE TITLE
'modal' prop on Popover has no effect. Focus is always trapped.

### ISSUE THREAD

**Issue by mikeebee** [radix-ui/primitives#1338]
## Bug report

The `modal` prop on `<Popover.Root />` has no effect on the focus trapping.

According to the docs for `modal`:

> The modality of the popover. When set to true, interaction with outside elements will be disabled and only popover content will be visible to screen readers.

Given the default is `false` I assume that focus won't be trapped yet on the example and in my own tests, focus is trapped by default and cannot be changed setting `modal={false}`.

While I consider the focus trapping to be the desired default I did find it strange that I couldn't disable it.

### Current Behavior

Focus is always trapped in the popver when open and changing the `modal` has no effect.

### Expected behavior

When `modal` is `false` if you tab into the popover and continue to press the tab button, once you have moved past the last tabbable element in the popover, it should select the next logical tabbable element outside of the popover.

### Reproducible example

[CodeSandbox example](https://codesandbox.io/s/async-cherry-ielbyi?file=/App.js)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-popover     |    0.1.6     |
| React            | n/a     |   17.0.19      |
| Browser          |    Brave     |    [1.37.116](https://brave.com/latest/)     |
| Node             | n/a     |    16.0.0     |
| npm/yarn         |    npm     |   7.1.10      |
| Operating System |   macOs      |    11.6 (BigSur)     |

Thanks so much for looking into this. These components are amazing!

**Comment by samburgers** [comment]
Appears to be the same behavior for the Dialog component also. 

https://www.radix-ui.com/docs/primitives/components/dialog

**Comment by mikeebee** [comment]
> Appears to be the same behavior for the Dialog component also.
> 
> https://www.radix-ui.com/docs/primitives/components/dialog

@samburgers Yeah looks that way, I just tested it and set `modal` to `false` (it's `true` by default on the `<Dialog />` component) and focus is still trapped.

**Comment by benoitgrelard** [comment]
@mikeebee, @samburgers,

This is more of a technicality, but when `modal={false}` the focus isn't trapped per se, you can for example programatically focus something outside, or you can focus an input outside by clicking into it.

What you are seeing is the focus `loop` being still present.

In an ideal world, we would not loop, however we chose this as a compromise for now, as when these are portalled, tabbing out of it would not lead you to where you expect (as you would be at the edge of the DOM). We need to work on a better solution where we can proxy the focus back to the next element in the hierarchy (rather than the DOM order).

This is actually being tracked here: #1308 so I will close this issue for now.

Hopefully that all makes sense.

✌️

**Comment by mikeebee** [comment]
@benoitgrelard that makes sense, thanks! I assume this would be an easier fix for when `<Content portalled={false} />`?

In fact, depending on the complexity of the fix mentioned in #1308, this could be a decent compromise. i.e. if you want to remove the focus `loop` you need the `modal={false}` and `portalled={false}` combo.

Will leave it in your capable hands to decide on the best solution, thanks again for your efforts 😊
