### ISSUE TITLE
Styling Select.Value

### ISSUE THREAD

**Issue by avin-kavish** [radix-ui/primitives#1363]
https://github.com/radix-ui/primitives/blob/23b934c1aeed966f15fda1222655f24fb0b5f311/packages/react/select/src/Select.tsx#L251

I'm not sure how important it is for Select.Value to not be styled. It's preventing me from using Select.Trigger as a `flex `container and adding `flex: 1` to Select.Value to get the select to stretch to fill the container.

**Comment by benoitgrelard** [comment]
Hi @avin-kavish,

It is currently pretty important. The main reason being because it simplifies alignment calculations by not having to take into account margin/padding offset from that part.

It would help us to understand where you're coming from if you could provide a sandbox demonstrating what you are trying to achieve, then we can either provide a solution or see if we need to make changes in the component itself.

Thanks!

✌️

**Comment by iammola** [comment]
Hey @benoitgrelard, 

I fully understand why you're preventing the `Select.Value` from being styled. I've created a sandbox that demonstrates my use case.

[![Edit Radix-UI Styling Select.Value Demo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/radix-ui-styling-select-value-demo-0hxrgi?fontsize=14&hidenavigation=1&theme=dark)

I'm trying to make a "user-select" component. I expect to use it in other parts of my project so I wanted to make sure it could scale and shrink as it needs to. I reduced the `max-width` on the trigger and the content was overflowing. This was an easy fix because I'm using flex to style the trigger, I just had to set the `Select.Value`'s `minWidth` to `0`. And all the text in the component will be truncated and shrink as I want it to.

If it won't be too difficult to do, maybe you can accept only the `style` prop on the `Select.Value` component and filter out only the style properties that won't affect the element's position like `minWidth` in my case disregarding other styles or even throwing an error to make sure the user is aware.

Thanks again for the amazing work you lot put into these packages. They make life so much easier.

**Comment by benoitgrelard** [comment]
Hey @iammola,

Yeah the truncating/ellipsis is definitely one I've been thinking about.
I am reluctant to add "easy" styling of `Value` though but perhaps as people will expect it to "just work" in all cases. But maybe I am worrying too much… not sure.

In the meantime, you could do this as an escape hatch:
```diff
<Select.Trigger style={styles.trigger}>
+  <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
    <Select.Value />
+  </span>
  <Select.Icon />
</Select.Trigger>
```

Or, you could even use CSS to target that first span:

```css
.trigger > span:first-child {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```

I am aware that with that second method you can still break it by adding padding-left for example, because you're now adding styles directly to the value, rather than a parent, but at least you have to get out of your way to break it.

What do you think?

**Comment by iammola** [comment]
HI @benoitgrelard.

The first method is the better option for me. I had no idea you were allowed to do that though and I can see how both methods can be overused to avoid the style filtering on the `Select.Value`.

Now I've seen it's possible/allowed to add a parent to the `Select.Value`. From what I can assume, any extra styles you want on it can be done that way. Like in @avin-kavish's case, If I add `flex: 1`, the extra span does fill the container, and the `Select.Value` does as well.

![Screenshot 2022-06-28 at 14 00 07](https://user-images.githubusercontent.com/55806855/176184720-c7d01df9-7564-4ad3-9f5a-7b3ea9b1fdda.png)

So you maybe won't have to change anything with the current behaviour, but add a section in the docs talking about adding an extra parent as a means to add styles to the `Select.Value` that the user is sure won't change its original position. I'm obviously not sure and haven't run any tests, so If what I'm saying isn't stable or advised or straight-up crap, forgive me🙏.

Thanks again and have a nice rest of your day. I appreciate it 🙌

**Comment by benoitgrelard** [comment]
Closing this down as we have provided a solution.
