### ISSUE TITLE
[Popover] Trigger assumes type="button" 

### ISSUE THREAD

**Issue by cdeutsch** [radix-ui/primitives#1461]
### Current Behavior

Same issue as #1010

The `Popover.Trigger` assumes a button. If `asChild={true}` is used with an `<a>` child, then the anchor ends up as `<a type="button" ...>`.

### Expected behavior

I'd expect to be able to use an `<a>` child without it receiving `type="button"`.

### Suggested solution

It may not make sense to pass the `type` attribute through when using `asChild={true}`.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |     0.1.6    |
| React            | n/a     |      16.13.1   |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
Hi @cdeutsch,

I'm curious what your use-case is because I would say that making the trigger a link is most likely a mistake and there is no reason to do so. The reason being, there can't be 2 actions on activating the trigger. Given that a link navigates somewhere, it doesn't make sense for it to also open a popover.

If your link doesn't lead anywhere, then it's likely it should be a button instead anyway…

Regardless of all of that, you can simply pass `type={undefined}` and it will override the type.

I will close the issue but feel free to keep discussing here.

✌️

**Comment by benoitgrelard** [comment]
If you're handling all the button accessibility on the div, then that's fine, you can then pass `type={undefined}` to the component.
