### ISSUE TITLE
Allow adjacent sibling combinator `input:checked+.switch` in Switch

### ISSUE THREAD

**Issue by tristen** [radix-ui/primitives#1493]
### Overview

When the switch component is used inside a `<form>` element, a checkbox input is rendered below the switch element. It would be great if the input element was rendered _above_ the switch element for a CSS sibling selector like `input:checked+.switch` could work.

### Examples in other libraries

| In [Assembly](https://labs.mapbox.com/assembly/documentation/#Switches), markup is composed with the input above so the adjacent selector works | Note that it _doesn't_ work in the reverse (i.e `.switch+input:checked`) |
| --- | --- |
| <img width="838" alt="Screen Shot 2022-06-28 at 11 23 17 AM" src="https://user-images.githubusercontent.com/61150/176219017-ec755d1e-47bb-48e6-9478-c278a02389e3.png"> |  <img width="956" alt="Screen Shot 2022-06-28 at 11 21 52 AM" src="https://user-images.githubusercontent.com/61150/176219012-75d42235-174c-4c06-b164-af33157bb6f5.png"> |

### Who does this impact? Who is this for?

This impacts my ability to use a CSS framework for styling the `checked` state of [switch](https://www.radix-ui.com/docs/primitives/components/switch).

**Comment by tristen** [comment]
That's true, it's just slightly inflexible using an atomic CSS framework. It also seems arbitrary that the input element is ordered below the switch element and not above which permits adjacent sibling selection on `input:checked`.

**Comment by jjenzz** [comment]
in a way, i am pleased it is preventing that because the `input` is an implementation detail. radix might not render one at all tomorrow so you're styles would all break. also, if a consumer rendered the switch outside of a `form` they would break.

the api you would ideally consume would be what is documented (the `data` attributes [will be in docs in next release](https://radix-website-git-release.modulz-deploys.com/docs/primitives/components/switch#root)) and anything beyond that is putting yourself at risk of breaking changes.

**Comment by tristen** [comment]
Hrm that's a valid point. Closing this out then!
