### ISSUE TITLE
[Label] Is not working when JS is disabled in the browser

### ISSUE THREAD

**Issue by Haberkamp** [radix-ui/primitives#1577]
### Current Behavior

When there is a label element and a input element and both are "linked" with the same id then clicking the label element should move the focus to the input element. This will happen if the user has enabled javascript but not when the user has disabled js.

### Expected behavior

Clicking the label should focus the checkbox or any other input element.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/kind-satoshi-mtkm8l?file=/src/App.tsx)

### Suggested solution

Swap out the rendered `span` element with a `label` element.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |    1.0.0     |
| React            | n/a     |   18      |
| Browser          |     chrome    |     n/a    |
| Assistive tech   |    n/a     |     n/a    |
| Node             | n/a     |    n/a     |
| npm/yarn         |      yarn   |     n/a    |
| Operating System |     MacOS    |    Monterey     |

**Comment by andy-hook** [comment]
Hi @Haberkamp, Thanks for raising, this would be due to Radix opting not to render a native label for the accessibility reasons described in https://github.com/radix-ui/primitives/issues/638#issuecomment-835241495 , though it's on our list to revisit this and test whether this has improved since https://github.com/radix-ui/primitives/issues/1233#issuecomment-1083185231

For now I'm going to close this as duplicate as it is covered by https://github.com/radix-ui/primitives/issues/1233

🙏
