### ISSUE TITLE
Using file Input with DropdownMenu.MenuItem `asChild` props will not trigger `onChange` event

### ISSUE THREAD

**Issue by MrKou47** [radix-ui/primitives#1583]
### Current Behavior

If I use `<input type="file" />` as `DropdownMenu.MenuItem`'s child, Input onChange callback would not be trigged whether click the Input directly or use *Arrow Down*+*Enter* key.

### Expected behavior

Input `onChange` callback should be trigged as usual.

### Reproducible example

https://codesandbox.io/s/elastic-stallman-7489eh?file=/App.js:5260-5817

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    latest     |         |
| React            | 16.8.3     |         |
| Browser          | Chrome latest        |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         | yarn       |         |
| Operating System | macOS        |         |

**Comment by benoitgrelard** [comment]
Hi @MrKou47,

That makes sense because the menu will close as soon as you activate the item (so when the native file modal opens) before you've had a chance to pick a file. You can prevent closing the menu on selection by adding `onSelect={event  => event.preventDefault()}` on that specific item. This will allow the `onChange` to bubble correctly.

Then to ensure a better UX maybe, you could control the open state via `open`/`onOpenChange` and close the menu once you've got the file (in your `onChange`).

I will close the issue with the provided solution but feel free to keep discussing here.
