### ISSUE TITLE
Why not all h1..h6?

### ISSUE THREAD

**Issue by ivanbanov** [radix-ui/primitives#1590]
## Question

The primitives have a specific set of allowed nodes
https://github.com/radix-ui/primitives/blob/main/packages/react/primitive/src/Primitive.tsx#L5

Is there any specific reason for not exposing all `h1..6` elements?

I would be handy for my team.

**Comment by ivanbanov** [comment]
Hey @benoitgrelard thanks for the quick answer.
My case is a Heading component, we would like to use `h1..6`

 ```jsx
import { styled } from '@stitches/react'
import { Primitive } from '@radix-ui/react-primitive'

const Heading1 = styled(primitive.h1, {}) // not possible
```

**Comment by benoitgrelard** [comment]
The `@radix-ui/react-primitive` is not a public package, it is used only internally. So we only cater for our own internal use-case. Only the components documented on the website are to be considered public. This is because breaking changes can happen at any time in non-public packages and we won't announce anything about them.
