### ISSUE TITLE
[Slot] Slot passes functions to it's children for onX handler properties, even when the onX handler is falsey

### ISSUE THREAD

**Issue by mattdaly** [radix-ui/primitives#1702]
## Bug report

I consider this a bug given my use case, but it may be considered expected behaviour.

### Current Behaviour

The `Slot` component has [code that wraps onX handlers](https://github.com/radix-ui/primitives/blob/main/packages/react/slot/src/Slot.tsx#L99-L106) so that handlers from the Slot parent (such as Tooltip) are called. However, [it doesn't check whether the handler on the child is actually truthy](https://github.com/radix-ui/primitives/blob/main/packages/react/slot/src/Slot.tsx#L101) before wrapping it, which causes it to suddenly be defined on the child component - even if it's value has explicitly been set to `undefined`.

In cases where child components render (or do something else) based on whether a handler is defined, this causes any properties starting with onX to always be defined - even in those cases where it may intentionally (such as a conditional) be undefined in the component.

The codesandbox has an example, but some code (where `Tooltip` is a wrapper around the radix Tooltip primitive):

```tsx
<Tooltip title="Example tooltip">
    <Tag onDelete={somethingIsTrue ? () => alert('delete') : undefined}>Example</Tag>
</Tooltip>
```

If `Tag` has code that does/renders something depending on `onDelete` being defined, it is _always_ defined when wrapped in a Tooltip - because Slot does that wrapping in the code linked above. This is the case for any `onX` handler, even if it is an entirely custom, non native dom event handler such as `onSomethingCompletelyRandom`.

It is also _always_ defined for `onClick`, presumably due to [this code in Tooltip itself](https://github.com/radix-ui/primitives/blob/main/packages/react/tooltip/src/Tooltip.tsx#L283-L305). I expect resolving that is slightly more challenging than resolving it for other handlers.

### Expected behaviour

Passing `undefined` (or another falsey value) to any property named `onX` should follow through to the child component.

### Reproducible example

https://codesandbox.io/s/keen-dan-c6u5yv?file=/App.js

### Suggested solution

[Check whether onX handlers are truthy inside Slot](https://github.com/radix-ui/primitives/blob/main/packages/react/slot/src/Slot.tsx#L101) before wrapping them -  by changing `isHandler` to `isHandler && childProps[propName]`.

For those (such as `onClick`) that are defined explicitly inside the Slot parents, [like those defined in Tooltip](https://github.com/radix-ui/primitives/blob/main/packages/react/tooltip/src/Tooltip.tsx#L283-L305), this solution wouldn't really work, you'd have to exclude them explicitly from the check (or change the clause to `isHandler && (slotProps[propName] || childProps[propName])`

**Comment by benoitgrelard** [comment]
Hey @mattdaly, I think you are making great points here.

Although I would argue that these types of APIs (rendering depending on the presence of callbacks, rather than other pieces of state, or even just composition) isn't very maintainable/predictable, I do agree that regardless this is not behaving as one would expect just using the component.

I will look into it 👍

**Comment by benoitgrelard** [comment]
One thing to note with this one:

```tsx
const Tag = React.forwardRef(({ onClick, ...props }, ref) => {
  return (
    <div {...props} className="tag" ref={ref}>
      {props.children} {onClick ? <button onClick={onClick}>[x]</button> : null}
    </div>
  );
});
```

Using `onClick` like this is a bit of an issue, because if you pulled it out from `props` like that you're essentially breaking the behaviour from the internal component (in this case `Tooltip.Trigger`) so really shouldn't be done. Separately too, (although not sure if it was a real example or not) you couldn't have an interactive element inside another interactive element given the element replacing `Tooltip.Trigger` (here the tag) should be interactive.

**Comment by benoitgrelard** [comment]
Additionally, after a bit more digging, we couldn't safely add a check next to `isHandler` like so:

```tsx
if (isHandler && childPropValue) …
```

because otherwise, we're now saying if the child (tag for example) doesn't add its own `onClick`, then the `Tooltip`'s own `onClick` won't work either.

We have to do this instead I think:

```tsx
// if it's a handler
if (isHandler) {
  // and it exists on both, we compose them
  if (slotPropValue && childPropValue) {
    overrideProps[propName] = (...args: unknown[]) => {
      childPropValue(...args);
      slotPropValue(...args);
    };
  }
  // but if it exists only on the slot, we use only this one
  else if (slotPropValue) {
    overrideProps[propName] = slotPropValue;
  }
}
```

This will clear your issues with custom handlers, but as I pointed out [above](https://github.com/radix-ui/primitives/issues/1702#issuecomment-1274528812), for native handlers it's not possible.

Let me know if that makes sense and if so I can make the change.

👍

**Comment by mattdaly** [comment]
Hey @benoitgrelard thanks for the thorough replies!

You are right on `onClick` and handlers coming from the slot being a bad idea, that one was just an example and not one we actively intend to use - I just wanted to highlight the different behaviours there. We do use `onDelete` to display a delete/remove button but that api may change, composition would be probably be preferred as you mention (that's also my most liked api decision in Radix).

The proposed solution looks like it solves the issue and is also close to what we have patch-package'd in our WIP drafts.

Thanks for the response (and the great library) 💯

**Comment by benoitgrelard** [comment]
Great, I'll prepare a PR then.

And thanks so much for the kinds words! ♥️
