### ISSUE TITLE
[Tabs] Lighthouse reports `Invalid` aria-* values on Tabs

### ISSUE THREAD

**Issue by thevipinmishra** [radix-ui/primitives#1703]
### Current Behavior

I'm using radix-ui Tabs along with stitches to style them, Lighthouse is reporting this accessibility issue with the aria-* labels on Tab Trigger Buttons.

![image](https://user-images.githubusercontent.com/52159805/194461530-08bcd236-4cdc-425d-8afb-2084ddc3ab9b.png)

& here's the concerned markup.

`<button type="button" role="tab" aria-selected="true" aria-controls="radix-:R3b6:-content-backend" data-state="active" id="radix-:R3b6:-trigger-backend" class="c-kPeNTM c-kPeNTM-iYUlKk-variant-light c-fgXKcs" tabindex="-1" data-orientation="horizontal" data-radix-collection-item="">Backend</button>`

They're also referencing [this link](https://dequeuniversity.com/rules/axe/4.4/aria-valid-attr-value?utm_source=lighthouse&utm_medium=devtools) to learn more about this issue.

### Suggested solution

Can we add a little meaningful aria-* labels ? I' not really sure, how can we do this though ☹️

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | Tabs    |  1.0.0  |
| React            | n/a     |         |
| Browser          | Chrome  |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |Windows  |         |

**Comment by VulcanTech-io** [comment]
I did some testing and figured out that having colons ":" in aria-controls is invalidates the lighthouse check. 

I am not sure if it is valid aria or not, I could not find any information on it.

**Comment by benoitgrelard** [comment]
We test these components with screen readers and do not see any issues so I doubt it causes problems in real life scenarios. Those ids are generated by React too, so we wouldn't be able to change that regardless. It seems like a reporting issue from Lighthouse's side.

**Comment by SaveliiLukash** [comment]
In my case the same exact Lighthouse error occurred when I was using `Tabs.Root` + `Tabs.List` + `Tabs.Trigger` on their own without `Tabs.Content`. In such case the `aria-controls` attributes on triggers contain the ids of nonexistent `Tabs.Content` elements, hence the error.

One solution is to add `aria-controls={undefined}` to `Tabs.Trigger`s to remove this attribute and make Lighthouse happy again.

However having `tablist` and `tab` without `tabpanel` is not a good ARIA practice. So it's better to use some other component rather than `Tabs` for such cases.

P.S.: Colons ":" in ids are perfectly valid.

**Comment by benoitgrelard** [comment]
> However having tablist and tab without tabpanel is not a good ARIA practice. So it's better to use some other component rather than Tabs for such cases.


@SaveliiLukash Yes that's not good practice. I'm not sure I follow why, but there isn't much point in using `Tabs` if you're not going to use `Tabs.Content`. You have to use the whole pattern for it to work correctly and be accessible.

**Comment by djalmaaraujo** [comment]
@benoitgrelard FYI: I opened an issue on axe-core related to this issue here. It's a significant impact having to turn off the axe-core rule because of the `semicolon` usage if you imagine the number of sites that now use Radix. 

I hope there's a specific reason that would cause more harm than good, and because of this, we can also evaluate if it makes sense to change how radix generates strings.

OR, they can allow what is in the WCAG specification.

Reference: https://github.com/dequelabs/axe-core/issues/4172

**Comment by djalmaaraujo** [comment]
So, it looks like the issue is not with axe-devtools. When the runner evaluates, there might be something happening with the components, like building or evaluating, that causes a Flaky test on our side. I think happens the same with Lighthouse.

**Comment by A7med3bdulBaset** [comment]
I'm having this issue in the Dialog component. I guess that the reason is that `area-control` in `<Trigger />` refers to an id (`<Content />`'s id) that doesn't exist since it's not rendered.

**Comment by vincerubinetti** [comment]
In my case, I was accidentally spreading `{...props}` to my `Content`, where I had modified `props` to have an `id` field for different purposes, so once I omitted `id` from `props` and letting Radix set the right `id`, I got that sweet 100 lighthouse score. 

Long story short, do make extra sure the right `id` is ending up on the panel and not getting overwritten by your own code somehow, because that can cause this error.

**Comment by avernikoz** [comment]
Using TabContent solves the issue
