### ISSUE TITLE
Change default values of Tooltip props in the TooltipProvider

### ISSUE THREAD

**Issue by matthewtole** [radix-ui/primitives#1712]
### Overview

Have the ability to change the default value of `Tooltip` props using a `TooltipProvider` in the same way that you can already use it to set the default `delayDuration`.

For example, in the app that I work on, for most of the app we want the tooltips to always display centered below the trigger element. But in our primary navigation sidebar, we want all of the tooltips to be on the right of the trigger.

Here's an extremely simplified of what I'm suggesting:

```
<App>
	<TooltipProvider side="bottom" sideOffset={4} align="center">
		<header />
		<TooltipProvider side="right">
			<aside>
				<nav />
			</aside>
		</TooltipProvider>
		<main />
	</TooltipProvider>
</App>
```

### Who does this impact? Who is this for?

This could be helpful for all types of users who want to have more control of the default props of their tooltips. This could extend to any of the Radix UI Primitive components as a standard pattern,

### Additional context

Happy to do the work myself if the Radix team thinks it's worthwhile!

**Comment by benoitgrelard** [comment]
Hi @matthewtole, thanks for raising an issue.

I don't think we would want to support nested providers here because there is global logic running in it and it is designed as a top-level provider (hence why it handles only global things that are shared behaviour of multiple tooltip instances).

On top of that, most of the time this is easily handled by default props.
Additionally it would open the door for more similar changes for lots of other similar components which don't currently have global providers.

For all these reasons I don't think it brings enough value to warrant the extra API surface.

Hope that makes sense.

✌️
