### ISSUE TITLE
[DropdownMenu][Repro example] Prevent DropdownMenu.Trigger click events propagating up to document?

### ISSUE THREAD

**Issue by Nic0S** [radix-ui/primitives#1785]
I posted a discussion thread [here](https://github.com/radix-ui/primitives/discussions/1769), after trying some more things I suspect this is a feature request. It doesn't seem possible to prevent these click events from propagating currently.

Right now click event listeners on the document / window get triggered when clicking on a DropdownMenu.trigger. I've tried adding event.stopPropagation() in a few places but I have not been able to figure out how to intercept these. It seems to happen regardless of whether you put the DropdownMenu content in a portal.

Here is a minimal repro of the behavior I'm seeing: https://codesandbox.io/s/radix-demo-2eu7mn?file=/src/App.tsx:424-444

Is it possible to avoid this by stopping the propagation somehow?

**Comment by andy-hook** [comment]
@Nic0S Sorry for the delayed response here, what are you trying to achieve by stopping this propagation?

The reason this is happening to due to the default modality setting `modal={true}` on `Root`. This setting disables pointer events on the body when `pointerDown`, thus the `onClick` handler doesn't complete and wont call `stopPropagation`.

You can test this by setting `modal={false}` and the behaviour acts as you'd expect.

@benoitgrelard Has this issue come up before?

**Comment by benoitgrelard** [comment]
I don't think I follow what's happening here or what we're trying to show/achieve.

**Comment by andy-hook** [comment]
> I don't think I follow what's happening here

`onClick` on `Trigger` doesn't fire when `modal={true}`

**Comment by benoitgrelard** [comment]
Ok, but that's expected as it's modal (as you correctly pointed out) so I don't think there's any issue here.
