### ISSUE TITLE
Dialog - Dialog ״clicks״ on first focusable button inside it when opened from key down handler

### ISSUE THREAD

**Issue by nirbenya** [radix-ui/primitives#1794]
I'm using a Dialog without Dialog.Trigger (just controlling it on my own.

When I open the dialog by clicking  on the "Enter" key when an article element (not a button element) is focused, it progremmatically clicks on the first focusable element inside the dialog.
I guess it's because this is the default behavior - to focus the first focusable element inside the dialog, but something makes the dialog to "click" it.

Reproduction of the issue can be found here: https://codesandbox.io/s/gallant-greider-nwrs39?file=/App.js

In order to reproduce the bug you need to tab one time in order to make the "click me" button focused and then press "Enter" on your keyboard.
You can see that the modal is not shown (with the mouse it works fine). 
It basically opens the modal and then immediately clicks the close button.

I will try to open a PR but opening this one for now for future refrence

**Comment by kevinrobert3** [comment]
I noticed this same issue with my dialog only it has an input. And when it opens the first input is focused by default, which is not the expected behavior for me. On investigation I also noticed the actual dialog on the Radix Primitives has the same behavior by default. 
Checked the documentation and it has the content prop [](https://www.radix-ui.com/docs/primitives/components/dialog#content). `onOpenAutoFocus`
Add the prop
 ```
onOpenAutoFocus={(e)=>{
                  e.preventDefault()
                }}
```
to the Content
