### ISSUE TITLE
Popover: how to add styles to the root element

### ISSUE THREAD

**Issue by gondar00** [radix-ui/primitives#1869]
## Question
I want to know how can we add a `className` to the `Root` element, citing from: https://www.radix-ui.com/docs/primitives/overview/styling

[Styling a part](https://www.radix-ui.com/docs/primitives/overview/styling#styling-a-part)
You can style a component part by targeting the className that you provide.
```
  import * as React from 'react';
  import * as Popover from '@radix-ui/react-popover';
  import './styles.css';
  
  const PopoverComponent = () => (
    <Popover.Root> // className prop doesn't work on the Root?
      <Popover.Content className="...">
         {/* … */}
       </Popover.Content>
    </Popover.Root>
  );
  
  export default PopoverComponent;
```

I have a usecase where I need to style based on the the Root element, is it possible to add classname to the Root element?

**Comment by benoitgrelard** [comment]
Hey @gondar00,

A lot of primitives don't require the `Root` part to be an actual element.
It is merely there as a wrapper for the state/context to be provided to all parts.
`Popover` is one of those cases as there is no need for a wrapper around trigger/content.

**Comment by TinsFox** [comment]
Hi, @benoitgrelard, 

I have the same problem, when I use Popover, the content part is covered by my content, I need to change the z-index and z-index, but the relevant properties are not exposed.

If I don't handle it, the Content area of the Popover will be blocked.
<img width="780" alt="image" src="https://user-images.githubusercontent.com/33956589/223706536-3dda2024-e094-4848-b470-bdf9aa58c373.png">

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/33956589/223705460-a464a1c2-f56f-4d3b-9b54-82088d53d380.png">

Here is my code: https://codesandbox.io/p/sandbox/tailwind-admin-1xlxjb?file=%2Fsrc%2FApp.tsx

**Comment by benoitgrelard** [comment]
Hey @TinsFox,

You have a few choices here:

1. On the first screenshot, it looks like you're not using the `Portal` part. When using the `Portal` part, it shouldn't be necessary to manage `z-index` as the content will be injected in `document.body` (by default) and so should be on top of the rest of your app. If it isn't it's likely because your app root (`#root`) doesn't define a new stacking context (you could fix this by adding `position: relative; z-index: 0;` to it for example).
2. If for some reason you don't want the `Portal` part, or you can't change the CSS of your root to ensure a new stacking context so everything works automatically, you can absolutely still control the `z-index` by setting it on the `Content` part. It will be automatically copied over to the positioning wrapper to ensure correct layering.

Hope this helps!

✌️

**Comment by TinsFox** [comment]
> Hey @TinsFox,
> 
> You have a few choices here:
> 
> 1. On the first screenshot, it looks like you're not using the `Portal` part. When using the `Portal` part, it shouldn't be necessary to manage `z-index` as the content will be injected in `document.body` (by default) and so should be on top of the rest of your app. If it isn't it's likely because your app root (`#root`) doesn't define a new stacking context (you could fix this by adding `position: relative; z-index: 0;` to it for example).
> 2. If for some reason you don't want the `Portal` part, or you can't change the CSS of your root to ensure a new stacking context so everything works automatically, you can absolutely still control the `z-index` by setting it on the `Content` part. It will be automatically copied over to the positioning wrapper to ensure correct layering.
> 
> Hope this helps!
> 
> ✌️

This helped me very well, thanks a lot! 🫶
