### ISSUE TITLE
Select causing layout shift in external monitor.

### ISSUE THREAD

**Issue by aungbobotun** [radix-ui/primitives#1925]
### Current Behavior

`Select` add `--removed-body-scroll-bar-size: 15px` on **24inch** secondary monitor.  
But when I visit on my **13inch**, it's `--removed-body-scroll-bar-size: 0px`. The same value gets added to the `margin-right` property of `body` and it's causing a layout shift.

### Suggested solution

By removing 

```css
body {
   margin-right: 15px !important;
}
```
<br/>

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |      Select   |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |   MacOS      |         |

**Comment by aungbobotun** [comment]
I see the same behavior in the example from website https://www.radix-ui.com/docs/primitives/components/select

**Comment by kiastorm** [comment]
I'm getting this behaviour too when using the `DropdownMenu` component

**Comment by thewinger** [comment]
I'm seeing the same behavior, any work around?
My body doesn't habe any classes. 
I have tried using position popper and items-aligned and same issue always 

![CleanShot 2023-04-01 at 10 57 02](https://user-images.githubusercontent.com/121455/229276468-76daff63-7184-48d1-8c64-54ef960d2f8f.gif)

**Comment by zuzabrzozowska** [comment]
Worked for me adding `margin: 0 !important;` on the body!

**Comment by brenoprata10** [comment]
I am also having the same issue 😿

**Comment by TheHanna** [comment]
Any update on this? I'm experiencing this issue with `RadixOverlay` in React

**Comment by joshdavenport** [comment]
With 100% width `position: fixed` elements (e.g. a fixed header) the margin applied to body by react-remove-scroll causes a visual shift in that element as the page margin doesn't affect the fixed element. That causes a very obvious shift when the select is open and radix disables scroll via react-remove-scroll.

Thankfully react-remove-scroll adds a CSS var `--removed-body-scroll-bar-size` that you can use to manually apply the offset that it adds as a margin to the page onto the width of your fixed element. i.e. something like:

```
width: calc(100% - var(--removed-body-scroll-bar-size, 0px));
```

**Comment by benoitgrelard** [comment]
Can someone provide a sandbox with the issue.
I'm not sure what scenario you have, but out of the box things should work correctly as you can see here:

https://github.com/radix-ui/primitives/assets/1539897/26d955bc-a5ab-4545-b831-6b25aff70056

**Comment by lukevella** [comment]
> Can someone provide a sandbox with the issue. I'm not sure what scenario you have, but out of the box things should work correctly as you can see here:
> 
>  CleanShot.2023-05-30.at.16.33.54.mp4

Here you go:

https://codesandbox.io/s/dazzling-oskar-ddkwl7

As I mentioned in my previous comment, the problem for me was that I was expecting overflow on the `html` element rather than the `body`. I believe I was using some components from [headlessui](https://headlessui.com/) which did the same trick radix is doing here to avoid the layout shift so the issue seems to be that these two don't play well together.

**Comment by benoitgrelard** [comment]
Thanks @lukevella. Yeah this makes sense, `react-remove-scroll` operates on body scroll, not `html` level as this is what where the default overflow is natively when there's too much content on the body.

That doesn't really help me though because this isn't really an issue per-se. (ie. simply don't force `overflow` on `html`).

I am interested in a reproduction when used correctly.

**Comment by lukevella** [comment]
> I am interested in a reproduction when used correctly.

I don't believe there is actually any issue with radix-ui's behavior here. I suspect most people having layout shift issues simply have overflow rules on `<html>` rather than `<body>`.

**Comment by benoitgrelard** [comment]
Yeah that's what I'm trying to determine too. But given I cannot reproduce the issue I feel you might be right.

**Comment by benoitgrelard** [comment]
I am going to close this issue as explained above this is likely a non-issue if using natural native page overflow.
If someone has a genuine issue with a reproduction, feel free to post it here and I can re-assess/re-open if necessary.

**Comment by jenniferhail** [comment]
> With 100% width `position: fixed` elements (e.g. a fixed header) the margin applied to body by react-remove-scroll causes a visual shift in that element as the page margin doesn't affect the fixed element. That causes a very obvious shift when the select is open and radix disables scroll via react-remove-scroll.
> 
> Thankfully react-remove-scroll adds a CSS var `--removed-body-scroll-bar-size` that you can use to manually apply the offset that it adds as a margin to the page onto the width of your fixed element. i.e. something like: `width: calc(100% - var(--removed-body-scroll-bar-size, 0px));` or `w-[calc(100%-var(--removed-body-scroll-bar-size,0px))]` for Tailwind users
> 
> For reproduction, on Mac at least, it helps to turn set show scroll bars in General preferences to "always":
> 
> <img alt="Screenshot 2023-05-13 at 00 10 12" width="686" src="https://user-images.githubusercontent.com/757828/238096793-07c43b62-8673-4380-9bbc-0f28f5419fce.png">

This is the solve. It would be great to see the css variable mentioned in the docs for anyone who has a fixed nav or element.

I moved overflow from html to body and then used `width: calc(100% - var(--removed-body-scroll-bar-size, 0px));
` on my fixed header to fix the shift. This is the best solution because Firefox treats custom scrollbars differently than Chrome & Safari.

**Comment by pahans** [comment]
> w-[calc(100%-var(--removed-body-scroll-bar-size,0px))]

This bug is caused by a margin, --removed-body-scroll-bar-size added by radix or its dependency(possibly react-remove-scroll).  this breaks the page layout inchrome for some cases. 
how to reproduce. 

Add a `<div style="position: fixed; width: 100%">` inside body and add a radix select. 
open the select and fixed element will move as you open-close select component.

**Comment by incpo** [comment]
Hello,
I fixed this by adding w-screen (width: 100vw) class to fixed component.
I have a fixed header so when I opened the Dialog component, header shifts.

**Comment by NicoToff** [comment]
Hello everyone,

I am experiencing the same issue when using both Dropdown and Select.
Being a Tailwind user, I had to add the "important" property to my `tailwind.config.cjs` file:
```javascript
/** @type {import('tailwindcss').Config} */
module.exports = {
  important: true,
  // ...
}
```
If I understand correctly, this will break inline styles, but I'm not using any, nor do the libs I'm using, so it's all good for me.

More info here: https://tailwindcss.com/docs/configuration#important

**Comment by stylessh** [comment]
@NicoToff I don't personally recommend you using the important option, since this adds "!important" rule on each tailwindcss style, this might cause numerous issues if you try to add some custom css that can override tailwind. I suggest you disabling the inline margin property that radix adds to the container.

**Comment by NicoToff** [comment]
> @NicoToff I don't personally recommend you using the important option, since this adds "!important" rule on each tailwindcss style, this might cause numerous issues if you try to add some custom css that can override tailwind. I suggest you disabling the inline margin property that radix adds to the container.

Are you talking about this fix you mentioned above?
```
body[style] { margin: 0 !important;}
```

**Comment by NicoToff** [comment]
Alright, I think I get the whole picture, now.

- Since expanding a `<select>` element natively disables the scroll bar, Radix hides it entirely for accessibility purposes.
- Hiding the scroll bar leaves more room for the page, so CSS instructions like `margin: auto` get very confused.

I find this behaviour very intrusive. I'd love to have a way to disable it entirely rather than having to fix it with variable overriding. Removing the scroll bar is simply not a behaviour I want on my UI.

**Comment by stylessh** [comment]
Unfortunately, there's no way to disable it by setting up a config param, that's why this issue for as well. Would be really good if they'd allow us to disable that behavior

**Comment by NicoToff** [comment]
My best solution was returning to native HTML `<select>`. It works great 😂

**Comment by Rahul-Palamarthi** [comment]
We can solve this issue, let me debug what's happening

when you use Radix UI two things happen
1. <code>overflow: hidden;</code> on the body and 
2. Radix UI will add <code>margin-right: </code> on the body.

_Why the <code>margin-right: </code> is being added on the body element??_
when there is <code>overflow: hidden;</code> on the body the scrollbar will disappear(width of the scroll bar is zero) and Radix UI will add imaginary scrollbar width in order to prevent layout shift using the <code>margin-right: </code> where the margin-right value will be the width of the scrollbar.

How to Fix this behavior: 
1. First we will add <code>scrollbar-gutter: stable</code> property on the html element(This will have a fixed width for the scrollbar even when the there <code>overflow: hidden</code> is present.)
[Youtube link](https://youtube.com/shorts/ZFhPGfLfSa8?si=qImiUfMOwTiRFvJZ) to the <code>scrollbar-gutter</code> property and how it works 
```css
html {
    scrollbar-gutter: stable;
}
```
3. Secondly we will add <code>margin-right: 0px !important;</code> inside body[style]
```css
body {
    margin: 0;
}

body[style] {
    margin-right: 0px !important;
}
```

**Comment by Rahul-Palamarthi** [comment]
> Unfortunately, there's no way to disable it by setting up a config param, that's why this issue for as well. Would be really good if they'd allow us to disable that behavior

No it is possible to disable this behavior [Issue link](https://github.com/radix-ui/primitives/issues/1925#issuecomment-1741936046)

**Comment by NicoToff** [comment]
> We can solve this issue, let me debug what's happening
> 
> when you use Radix UI two things happen
> 
> 1. `overflow: hidden;` on the body and
> 2. Radix UI will add `margin-right: ` on the body.
> 
> _Why the `margin-right: ` is being added on the body element??_ when there is `overflow: hidden;` on the body the scrollbar will disappear(width of the scroll bar is zero) and Radix UI will add imaginary scrollbar width in order to prevent layout shift using the `margin-right: ` where the margin-right value will be the width of the scrollbar.
> 
> How to Fix this behavior:
> 
> 1. First we will add `scrollbar-gutter: stable` property on the html element(This will have a fixed width for the scrollbar even when the there `overflow: hidden` is present.)
>    [Youtube link](https://youtube.com/shorts/ZFhPGfLfSa8?si=qImiUfMOwTiRFvJZ) to the `scrollbar-gutter` property and how it works
> 
> ```css
> html {
>     scrollbar-gutter: stable;
> }
> ```
> 
> 3. Secondly we will add `margin-right: 0px !important;` inside body[style]
> 
> ```css
> body {
>     margin: 0;
> }
> 
> body[style] {
>     margin-right: 0px !important;
> }
> ```

Well, @Rahul-Palamarthi , I think you fixed it for me 😄 The missing piece for my use case was the `scrollbar-gutter`, apparently. A fine bit of CSS dark magic (thx for the link, btw).

I modified you snippet since I use auto margins with Tailwind (`container mx-auto`) and everything works great:
````css
html {
  scrollbar-gutter: stable;
}

body[style] {
  margin: 0 auto !important;
}
```

Thank you so much!

**Comment by vinit-churi** [comment]
for me just increasing the css specificity to the body selector worked 
```css
html body {
  margin-right: 0px !important;
}
```

**Comment by DanielSpindler** [comment]
> > I am interested in a reproduction when used correctly.
> 
> I don't believe there is actually any issue with radix-ui's behavior here. I suspect most people having layout shift issues simply have overflow rules on `<html>` rather than `<body>`.

the problem is that a simple drop down for example can manipulate the body styles...

**Comment by NicoToff** [comment]
Hello beautiful people!
Long time no see :D Turns out my issue wasn't entirely solved! Not for all screen sizes at the very least.

I unfortunately couldn't reproduce the problem in a simple Vite app, which led me to believe something was wrong with shadcn's components. I checked issues on this master's repo, and I found this: https://github.com/shadcn-ui/ui/issues/977 

A gentleperson over there share this tip:

> I had the same issue, removing the class of body to a new div under the body solved the issue.

So in my layout file:
```
    <body class={bodyClass}>
        // ...
```
became
```
    <body>
        <div class={bodyClass}>
           // ...
```

This now entirely solves my issue! ......

Until next time XD

**Comment by raphaelpg** [comment]
> ```css
> html {
>   scrollbar-gutter: stable;
> }
> 
> body[style] {
>   margin: 0 auto !important;
> }
> ```@NicoToff Thanks, this is the only solution that worked for me

**Comment by Roeefl** [comment]
Can someone please explain why is this closed?

Is this intended, legit behaviour? not a bug?

When toggling the Select to be opened in the radix website even (here) [https://www.radix-ui.com/primitives/docs/components/select], the scroll in the page is not displayed.

is this legit?

**Comment by rahu1gg** [comment]
> Can someone please explain why is this closed?
> 
> Is this intended, legit behaviour? not a bug?
> 
> When toggling the Select to be opened in [the radix website](https://www.radix-ui.com/primitives/docs/components/select), the scroll in the page is not displayed.
> 
> is this legit?

they are using ```overflow: hidden``` on the body or html tag. Hence the scroll will not be displayed

**Comment by joshdavenport** [comment]
The issue isn't really about whether the scroll bar is visible or not, it's relating to layout shift caused by the implementation of preventing a shift due to the scrollbar taking viewport space before the select is opened, and then maintaining the previously occupied scrollbar space when it is no longer showing after the select is opened due to  `overflow: hidden` on the body. As there is a scrollbar and then there isn't and radix's implementation of dealing with that via [react-remove-scroll] doesn't affect fixed elements, because the margin on the body it adds doesn't affect those elements, there is a visible layout shift:

![2023-12-20 12 25 03](https://github.com/radix-ui/primitives/assets/757828/cc82bdd6-e0c5-41d9-8110-a052d924e443)

However, you'll only see that issue if you have scrollbars set to "Always" in MacOS (see https://github.com/radix-ui/primitives/issues/1925#issuecomment-1546419319 for reference of the setting I'm talking about). That header is using fixed positioning and so it's affected. This happens because the viewport width actually changes when the scrollbar goes.

If you have the OS level setting set to "When scrolling" (or they aren't showing based on the automatic setting) then you won't see the issue in the first place. This is because with that setting, the scrollbar sits on top of the page, not ever affecting the viewport width.

The fix is [simple](https://github.com/radix-ui/primitives/issues/1925#issuecomment-1546419319) thankfully:

![2023-12-20 12 33 06](https://github.com/radix-ui/primitives/assets/757828/74e1ba32-ad17-48bc-92b1-a66ece643283)

**Comment by AndrShept** [comment]
html body {
 
  overflow-y:   visible !important;
  margin-right: 0 !important;

}

**Comment by Roeefl** [comment]
> > Can someone please explain why is this closed?
> > Is this intended, legit behaviour? not a bug?
> > When toggling the Select to be opened in [the radix website](https://www.radix-ui.com/primitives/docs/components/select), the scroll in the page is not displayed.
> > is this legit?
> 
> they are using `overflow: hidden` on the body or html tag. Hence the scroll will not be displayed

Yes, I am well aware, thank you. the issue with that is that it's not considered super legit to do that to begin with.

**Comment by JasonColeyNZ** [comment]
I have just come across this. And its even worse if you have a popover on a modal.
It appears the same -15px is applied to the modal, however, when you open the popover on the modal, then close it you get the shift even with the fixes above. Because I assume that when the popover closes the -15px is removed, but the modal is still open, causing a shift of the dialog, which is even worse than the layout shift happening behind the modal as was happening. Surely there is a better solution to this, or least a way to opt out of the scroll-lock thing.

**Comment by DanielSpindler** [comment]
> I have just come across this. And its even worse if you have a popover on a modal. It appears the same -15px is applied to the modal, however, when you open the popover on the modal, then close it you get the shift even with the fixes above. Because I assume that when the popover closes the -15px is removed, but the modal is still open, causing a shift of the dialog, which is even worse than the layout shift happening behind the modal as was happening. Surely there is a better solution to this, or least a way to opt out of the scroll-lock thing.
> 
> Actually my bad, its a dropdownmenu that is causing this issue on a dialog, however, same issue really.

also the same issue. for a few months now. i dont know why this is getting closed if the "solutions" are only workarounds

**Comment by JasonColeyNZ** [comment]
> also the same issue. for a few months now. i dont know why this is getting closed if the "solutions" are only workarounds

Hopefully they are looking into this..[. see here.](https://github.com/theKashey/react-remove-scroll-bar/issues/57)

**Comment by JasonColeyNZ** [comment]
Therehas been a fix associated with my issue, i.e. multiple layered controls using the react-remove-scroll, see here, will this be implemented to help fix the issues?

[Regression introduced when used in nested contexts](https://github.com/theKashey/react-remove-scroll-bar/issues/57)

**Comment by digitaltim-de** [comment]
Best worked solutions for me for shadcn..

`
html {
  scrollbar-gutter: stable;
}

body[data-scroll-locked] {
  overflow: hidden;
  position: fixed;
  width: 100%;
}
`

**Comment by JasonColeyNZ** [comment]
OK so I have overridden the react-remove-scroll used in radix-ui components, react-dialog and react-popover to use the latest "2.5.9" and the issues have gone so far from testing, this is to do with using layered components using these components, i.e. a dropdown menu on a dialog etc.
This is what I placed in my package.json...

```
"overrides": {
"@radix-ui/react-dialog": {
      "react-remove-scroll": "2.5.9"
    },
    "@radix-ui/react-popover": {
      "react-remove-scroll": "2.5.9"
    }
}
```

**Comment by thehashton** [comment]
This is what fixed it for in side `global.css` (tailwind css). You have to target `body[data-scroll-locked]` but you have to be even more specific by adding `html` as well because the DropDownMenu component will still try to override it.

```
  html body[data-scroll-locked] {
    margin-right: 0 !important;
  }
  ```

**Comment by Maliksidk19** [comment]
Don't need to add extra classes or something just remove this min width class from select component imported from shadcn and this issue will gone 

![image](https://github.com/user-attachments/assets/0bb4626d-7edd-427d-b1c8-9af7aa1fc94b)

**Comment by HoangTitannn** [comment]
> This is what fixed it for me inside `global.css` (tailwind css). You have to target `body[data-scroll-locked]` but you have to be even more specific by adding `html` as well because the DropDownMenu component will still try to override it.
> 
> ```
>   html body[data-scroll-locked] {
>     margin-right: 0 !important;
>   }
> ```

Thanks i have same issue and it work

**Comment by marcelino-borges** [comment]
None of the above suggestions worked for me.

My solution: adding `width: 100vw;` to `body` in my globals.css.

```css
/* globals.css */

body {
  /* (...) */
  width: 100vw;
}
```

I didn't try `body[style] {  margin: 0 auto !important; }` though, because I think it's too much haha

**Comment by ayortanli** [comment]
The library's styling is correct. In my case, it was due to the body being styled with the flex layout. After removing it, enabling/disabling the scrollbar stopped affecting the layout.

**Comment by Pascalmh** [comment]
Depending on your layout you'll need to add additional classes from [react-remove-scroll-bar
](https://github.com/theKashey/react-remove-scroll-bar) which is used internally for the radix-ui/primitives.

I needed to add the `fullWidthClassName` to my "main div" (the first child after the router outlet).

It is adding a `margin-right: 15px !important;` once the select is opened to the div it is applied to (if there was a scrollbar before - otherwise it adds `margin-right: 0px !important;`)

See also: https://github.com/radix-ui/primitives/discussions/1586#discussioncomment-3302669

**Comment by mausam-giri** [comment]
I was facing layout shifts when opening the **Radix Dialog** modal and while picking items from the **Select** component. The solutions provided didn’t entirely solve the issue, but here’s what worked for me:

- For the Modal **(Radix Dialog)**, I found that setting `--removed-body-scroll-bar-size: 0px !important;` helped resolve the layout shift caused by the scrollbar.
![modal-open-shift-before](https://github.com/user-attachments/assets/98a702d8-f573-44de-a66b-dd6596ed0fe0)

- For the **Select**, the main issue wasn’t margin-right, but the padding-right added by` data-scrolled-locked='2'`. I resolved the layout shift by explicitly setting `padding-right: 0 !important;`.
![screenshot-open-shift-before](https://github.com/user-attachments/assets/40bb6e16-8d68-4bac-92a8-29dc807c0549)


Here’s the solution that fixed both issues:
`html body[data-scroll-locked] {
  padding-right: 0 !important;
  --removed-body-scroll-bar-size: 0px !important;
}`

This combination ensures that both the Dialog and Select components no longer cause layout shifts.

**Comment by DanielSpindler** [comment]
> Don't need to add extra classes or something just remove this min width class from select component imported from shadcn and this issue will gone
> 
> ![image](https://private-user-images.githubusercontent.com/105909607/348937577-0bb4626d-7edd-427d-b1c8-9af7aa1fc94b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzEwMDEsIm5iZiI6MTczMDk3MDcwMSwicGF0aCI6Ii8xMDU5MDk2MDcvMzQ4OTM3NTc3LTBiYjQ2MjZkLTdlZGQtNDI3ZC1iMWM4LTlhZjdhYTFmYzk0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwOTExNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmNmMjg4ZGQyMTc0NDRmOTdhNmRlNzhkYjA4ODBkZGFmMWE5NDYxN2E3NGVjNGQyMWM0MTYwNzkwYzVhNDkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.86nRdsTXsixKSmvgkZVEtCuraeRcKV90amz9E9cLUuI)
> 
> Also from the dropdown
> 
> ![image](https://private-user-images.githubusercontent.com/105909607/348937892-4e857e3a-a291-4f17-a465-f7cb48fe55f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzEwMDEsIm5iZiI6MTczMDk3MDcwMSwicGF0aCI6Ii8xMDU5MDk2MDcvMzQ4OTM3ODkyLTRlODU3ZTNhLWEyOTEtNGYxNy1hNDY1LWY3Y2I0OGZlNTVmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwOTExNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTBhYzI1MmM2NTYwYzBiMDQ4Mjc0N2IzZmUwNDM0M2M5M2QwOThmZWQzNWNlOTE1OWM0Y2I4MjRmNTdjZDNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.p1PFT9PACpWa3i5pxcQQc2BPJh1OvkF6I0d6EKRj-rY)

That might be true for your setup, but shouldnt fix it at all! else your dropdown dictates the size width of your page. Usually CSS like that comes from a layout. And most people here have the LayoutShifts because clicking the select triggers an Event that removes css and replaces it on a TopLevel. They already did a quick fix for it and it should be gone for correct implementations. Min-w is just a minimum width. Wrong implementation of the Component if this triggers a Layoutshift.

**Comment by DevBobi** [comment]
For me, this worked!!
 ```
 body {
    scrollbar-gutter: stable;
    overflow-y: scroll;
  }
```

**Comment by surenafard** [comment]
> > I am interested in a reproduction when used correctly.
> 
> I don't believe there is actually any issue with radix-ui's behavior here. I suspect most people having layout shift issues simply have overflow rules on `<html>` rather than `<body>`.

This fixed my issue.

**Comment by qgatssdev** [comment]
html body[data-scroll-locked] {
    margin-right: 0 !important;
    --removed-body-scroll-bar-size: 0px !important;
  }

If anyone still faces this issue and uses tailwind, this worked for me

**Comment by Rami-Abdou** [comment]
> With 100% width `position: fixed` elements (e.g. a fixed header) the margin applied to body by react-remove-scroll causes a visual shift in that element as the page margin doesn't affect the fixed element. That causes a very obvious shift when the select is open and radix disables scroll via react-remove-scroll.
> 
> Thankfully react-remove-scroll adds a CSS var `--removed-body-scroll-bar-size` that you can use to manually apply the offset that it adds as a margin to the page onto the width of your fixed element. i.e. something like: `width: calc(100% - var(--removed-body-scroll-bar-size, 0px));` or `w-[calc(100%-var(--removed-body-scroll-bar-size,0px))]` for Tailwind users
> 
> For reproduction, on Mac at least, it helps to turn set show scroll bars in General preferences to "always":
> 
> <img alt="Screenshot 2023-05-13 at 00 10 12" width="686" src="https://private-user-images.githubusercontent.com/757828/238096793-07c43b62-8673-4380-9bbc-0f28f5419fce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDU5MDIyNTEsIm5iZiI6MTc0NTkwMTk1MSwicGF0aCI6Ii83NTc4MjgvMjM4MDk2NzkzLTA3YzQzYjYyLTg2NzMtNDM4MC05YmJjLTBmMjhmNTQxOWZjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQyOVQwNDQ1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODRiMjRkMmQzNWI2ODBlZTZmY2I2ZWJmOGVhYjQ5MDE3YzYxYWRhYzRjYjIyOGQ5MmExYjIyOWE2MTgyY2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hrDzNevmkdzKNnEhCFXc2V1nD3_KE9FTkznQlrxBVfY">

thanks legend.

**Comment by mengxi-ream** [comment]
For something fixed to the right, this is what I did:
add right padding `pr-[var(--removed-body-scroll-bar-size,0px)]`, and add more width width: `calc(${sideContentWidth}px + var(--removed-body-scroll-bar-size, 0px))`
```tsx
      <div
        className={cn(
          "fixed top-0 right-0 bg-background h-full z-[2147483647] pr-[var(--removed-body-scroll-bar-size,0px)]",
          isSideOpen
            ? "translate-x-0 border-l border-border"
            : "translate-x-full"
        )}
        style={{
          width: `calc(${sideContentWidth}px + var(--removed-body-scroll-bar-size, 0px))`,
        }}
      >
```

https://github.com/user-attachments/assets/4320f18e-a48a-4999-918f-19cecf3f14b7

**Comment by cjoecker** [comment]
This CSS solved the issue for me
```
body { @apply !min-w-full; }
```

**Comment by john-james-gh** [comment]
I’m hitting this as well. Using Tailwind v4 and Shadcn/UI. OS doesn’t seem to matter in my case.

In my setup, opening a shadcn/ui Select (Radix) causes the main container to temporarily shrink. The trigger is the `data-scroll-locked` styles Radix applies to body, which end up conflicting with a Tailwind's `container mx-auto max-w-5xl` common layout.

Workaround that fixed it for me
Force the layout constraints on body using Tailwind’s !important modifier so the scroll-lock styles can’t override width/centering.

```ts
// layout.tsx. tailwind v4 + shadcn/ui
<body className="container! mx-auto! max-w-5xl! p-4! min-h-screen">
  {children}
</body>
```

**Comment by hrshihab** [comment]
Its work for me :  

html body[data-scroll-locked] {
    margin-right: 0 !important;
    --removed-body-scroll-bar-size: 0px !important;
  }
