### ISSUE TITLE
Dialog doesn't open on Trigger's keyboard action when asChild={true}

### ISSUE THREAD

**Issue by nik-webdevelop** [radix-ui/primitives#1941]
### Current Behavior

```
<Dialog.Root>
  <Dialog.Trigger asChild>
    <div role="button" tabIndex={0}>
      Div as button
    </div>
  </Dialog.Trigger>
  ...
</Dialog.Root>
```

When I click the Div with the mouse modal opens. When I select it with the Tab and try to open modal with enter/space nothing happens

### Expected behavior

Modal should be open with keyboard actions

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/zealous-wozniak-d5f3w5?file=/src/App.tsx)

### Additional context

I have intricate markup with a lot of styling in Trigger, so I decided to use a div instead of a button.

**Comment by benoitgrelard** [comment]
Hey @nik-webdevelop, that is to be expected.
If you don't use semantic, accessible elements, it's on you to patch all of the missing accessibility.

Here a `div` isn't interactive by default. You have rightfully made it focusable by passing `tabIndex={0}` but there's a lot more that would be needed to make it behave like a button (respond to pointer inputs, respond to keyboard inputs, etc).

I would discourage you to go that route though, as it's just a ton of work when a native `button` is all you need.
Was there a specific reason you wanted a div instead of a button?

**Comment by nik-webdevelop** [comment]
@benoitgrelard I see. Thanks for the clarification. 
The button only allows phrasing content as children, and I have a lot of markup and styles inside it, so I wanted to use div to be able to use tags other than <span>/etc

**Comment by nik-webdevelop** [comment]
@benoitgrelard It's interesting though, if we assume that using any other tag than the button would be discouraged, why do we need `asChild` here then? If we can pass all valid button props right to `Dialog.Trigger`

**Comment by benoitgrelard** [comment]
`asChild` is very useful here still because you most likely don't want to "fix" the design of your dialog triggers to be the same everywhere in your app, same for `Popover`, `Tooltip`, `DropdownMenu`, etc.

The reality is in your app you are likely to open these things from plenty of different looking triggers, so you may have:

```tsx
<Dialog.Trigger asChild>
  <Button variant="ghost">…</Button>
</Dialog.Trigger>

<Dialog.Trigger asChild>
  <IconButton color="gray">…</IconButton>
</Dialog.Trigger>

etc…
```

**Comment by nik-webdevelop** [comment]
Yes, this makes sense. Thanks a lot )
