### ISSUE TITLE
Menubar Items get removed from DOM immediately after appearing

### ISSUE THREAD

**Issue by boidushya** [radix-ui/primitives#1948]
### Current Behavior

Menubar Items get removed from DOM immediately after appearing

https://user-images.githubusercontent.com/26746725/217915835-ac6ccfe1-7f35-4059-84ee-1a44f13e490d.mov

### Expected behavior

Menubar Items should persist after being appended to DOM

### Additional context

Here's the link to a live reproduction [boidushya-com.vercel.app](https://boidushya-com.vercel.app/)
and [the code for the same](https://github.com/boidushya/boidushya.com/blob/master/src/elements/Menu/MenuContent.jsx)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     react-menubar    |     ^1.0.0    |
| React            | n/a     |     ^18.0.0    |
| Browser          |    brave     |    1.47.171     |
| Assistive tech   |    create-react-app    |    n/a     |
| Node             | n/a     |     18.9.0    |
| npm/yarn         |     yarn    |     1.22.19    |
| Operating System |    MacOS     |     Ventura    |

**Comment by benoitgrelard** [comment]
Hey @boidushya,

Are you able to reproduce this with a basic codesandbox rather than your entire app?
I'm fairly certain this is due to something you are doing in your app, but if you can manage a reproduction using a simple sandbox (starting from our demo for example) that would be helpful.

Thanks!
