### ISSUE TITLE
[AccordionContent] `asChild` removes the children on closed state

### ISSUE THREAD

**Issue by siriwatknp** [radix-ui/primitives#1967]
### Current Behavior

```js
const AccordionContent = ({ children }: React.PropsWithChildren<{}>) => (
  <StyledContent asChild>
    <div>…</div>
  </StyledContent>
);
```

`div` is removed from DOM when it is in `closed` state but this does not happen without `asChild`.

### Expected behavior

`div` should always remain in the DOM similar to the [basic example](https://www.radix-ui.com/docs/primitives/components/accordion#accordion) without `asChild`

### Reproducible example

https://codesandbox.io/s/joy-ui-feat-radix-accordion-forked-tofszs?file=/demo.tsx

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |    v1.2.0     |
| React            | n/a     |  18.2.0       |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by iSchoen** [comment]
I have the exact same issue.  Sucks to see there was never a response.

**Comment by benoitgrelard** [comment]
> ## Bug report
> ### Current Behavior
> ```js
> const AccordionContent = ({ children }: React.PropsWithChildren<{}>) => (
>   <StyledContent asChild>
>     <div>…</div>
>   </StyledContent>
> );
> ```
> 
> `div` is removed from DOM when it is in `closed` state but this does not happen without `asChild`.
> 
> ### Expected behavior
> `div` should always remain in the DOM similar to the [basic example](https://www.radix-ui.com/docs/primitives/components/accordion#accordion) without `asChild`

This is functioning as intended.
- When you don't provide `asChild` to the `Content` part, the `Content` part renders a DOM element for itself, therefore the `div` you put inside that it basically an inner wrapper that you add.
- When you provide `asChild` to the `Content` part, you are essentially providing the element `Content` should render instead of letting it do its default. If you want to achieve the same (ie. having an inner wrapper), you'd add another `div` inside, this would result in the exact same DOM hierarchy.

on a side-note:
```tsx
<Accordion.Content asChild>
  <div>
  …
  </div>
</Accordion.Content>
```

doesn't make much sense, as `Accordion.Content` already renders as a `div` by default. So essentially this is exactly equivalent to:

<Accordion.Content>
  …
</Accordion.Content>
