### ISSUE TITLE
[Switch] undefined in controlled state

### ISSUE THREAD

**Issue by aboveyunhai** [radix-ui/primitives#2112]
### Current Behavior
```tsx
   const [checked, setChecked] = useState();
   <Switch.Root className="SwitchRoot" checked={checked} onCheckedChange={setChecked}>
      <Switch.Thumb className="SwitchThumb" />
    </Switch.Root>
```

if I call `setChecked(undefined)` from a outside state re-setter, the `<Switch />` will reject the change due to the value is `undefined`. 

### Expected behavior

This is either a bug or a limitation of typescript definition.

I expect the `undefined` is equivalent to `false` in this case.  Otherwise the typescript of initial state should be `boolean` only instead of  `boolean | undefined` but I think the undefined is caused by the `?` optional property. 

The correct typescript should be if it's either `undefined`, or `boolean` only once the property is defined.

Or maybe document this behavior somewhere such that if you want to use `checked`, the correct way to do is:
```tsx
<Switch.Root 
    className="SwitchRoot" 
    checked={checked || false} // <== pass the default false here 
    onCheckedChange={setChecked}
/>
```
### Reproducible example

[CodeSandbox](https://codesandbox.io/s/admiring-scott-fo22ec?file=/src/App.tsx)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | lastest     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
Hey @aboveyunhai,

The current behaviour and types are correct.

This is because the component can be both "controlled" or "uncontrolled".
"uncontrolled" is determined by the absence of `checked` prop (ie. `checked === undefined`).
This is exactly what React does for any form inputs too (`value === undefined` => uncontrolled input).
Setting the state to `undefined` would mean you are trying to change from controlled to uncontrolled which is not possible.
React even shows a warning if you try to do that with an `input`.

Hope that helps!

✌️
