### ISSUE TITLE
[HoverCard] automatically renders content if the trigger is a button tag, inside the [Popover]

### ISSUE THREAD

**Issue by andrey779evseev** [radix-ui/primitives#2138]
### Current Behavior
If place HoverCard inside Popover, and trigger of HoverCard will be tag button, on opening Popover, HoverCard content will be automatically showed, which is not correct behavior, but if place div instead of button in HoverCard trigger everything work as expected

https://github.com/radix-ui/primitives/assets/63901022/d78d0f28-6bb6-4c08-8f12-d4f0cfb48fde

### Expected behavior
Show HoverCard content on trigger hover event, not on opening popover event.

### Reproducible example

[CodeSandbox Reproduction](https://codesandbox.io/p/sandbox/old-firefly-zi9bg6?file=%2Fsrc%2FApp.tsx%3A7%2C8-7%2C19)

### Suggested solution
Temporary this bug can be fixed by replacing button tag with div (for example with role=button attribute), but would be great if this will work also with default button tag.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-hover-card    |    1.0.5     |
| Radix Package(s) |    @radix-ui/react-popover     |    1.0.5     |
| React            |     n/a     |     18.2.0    |
| Browser          |    Arc     |    0.103.0     |
| Assistive tech   |     n/a    |     n/a    |
| Node             |     n/a     |    19.8.1     |
| npm/yarn/pnpm         |    pnpm     |    8.4.0     |
| Operating System |    MacOS     |    Ventura 13.3    |

**Comment by joaom00** [comment]
It's because with the button tag when the popover is opened the button is focused making the hover card open. You can prevent this by placing another interactive element before or programmatically focusing another element in `onOpenAutoFocus`. 

It is worth mentioning that the hover card was designed for the trigger to be an anchor and only for sighted users as it does not have any kind of accessibility for screen reader users.

**Comment by andrey779evseev** [comment]
@joaom00 Got it, thanks a lot for the detailed explanation.
