### ISSUE TITLE
[DropdownMenu] Can I disable tracking Trigger positioning, after the menu has been opened?

### ISSUE THREAD

**Issue by yudinvictor** [radix-ui/primitives#2139]
## Question

I need to put display: none to trigger (when dropdown is not active or user is not hovering over Trigger). 
Initially I planned to use [data-state='open'] attribute (to put display: block), but I have animation to close (on css) and have problem with putting data-state = false -> my trigger gets hidden -> dropdown content breaks because it seems to follow trigger positioning

Is there any way to
1. Disable tracking trigger positioning, after the menu has been opened (preferably)?
2. To know that the dropdown has been unmounted? 

## Demo

https://codesandbox.io/s/radix-ui-hide-dropdownmenu-trigger-item-after-animation-close-obgh55?file=/src/App.tsx

https://github.com/radix-ui/primitives/assets/43467675/666437ec-6333-441b-89a2-564083a01937

**Comment by joaom00** [comment]
Basically you need to hide the trigger visually, with `visibility: hidden` for example. It is worth mentioning that if the user is navigating through the keyboard, when closing the dropdown the trigger is not focused causing it to lose the context where it was. I have an example where I believe to be a good UX https://codesandbox.io/s/muddy-resonance-yvioxi?file=/App.js

**Comment by yudinvictor** [comment]
It's not enough for me to just hide the element. 

In your demo above, the three dot icon takes up space to the right of the text, even if it is not visible. 

![image](https://github.com/radix-ui/primitives/assets/43467675/93d2d6b5-9e36-4e26-9289-734b4ca60d57)

I need the text to take up the full width by default (For example, as in the sidebar Notion)

![image](https://github.com/radix-ui/primitives/assets/43467675/c910d888-90a4-4da9-8d1f-53bdaaccd4d5)
![image](https://github.com/radix-ui/primitives/assets/43467675/31e278f6-fc45-402c-aacd-40d24660b0c9)

**Comment by benoitgrelard** [comment]
Hey @yudinvictor,

> 1. Disable tracking trigger positioning, after the menu has been opened (preferably)?

There isn't anything to do that.

> 2. To know that the dropdown has been unmounted?

You could probably do this yourself by adding a component inside the `DropdownContent` to track that.

---

Regardless, I believe this is what you are after, and this is accessible via keyboard too.

https://codesandbox.io/s/radix-ui-hide-dropdownmenu-trigger-item-after-animation-close-forked-yepnvd?file=/src/row/row.tsx

There is one minor thing remaining when using the keyboard.
Because of your animation on close, the focus isn't returned immediately to the trigger, therefore there will be a slight moment in time where the trigger will be taken out of flow (but then back again).

I'm running out of ideas to get around that, apart from using some timers to set some extra attributes (totally possible using `onOpenChange`) I don't think we can get around that.

But otherwise this would be the way I'd do it.
