### ISSUE TITLE
[RadioGroup] Toolbar mode for RadioGroup

### ISSUE THREAD

**Issue by sohcfst** [radix-ui/primitives#2146]
### Overview

Would love to see a mode for RadioGroup where the value is not set until the spacebar is hit. (Contained in Toolbar - more context below)

### Examples in other libraries

https://www.w3.org/WAI/ARIA/apg/patterns/toolbar/examples/toolbar/

### Who does this impact? Who is this for?

Me! And other consumers of the library.  We had a use case where "only one value could be selected at a time" but we didn't want the `onValueChange` handler to fire unless we hit space. 

### Additional context

https://www.w3.org/WAI/ARIA/apg/patterns/radio/, under "For Radio Group Contained in a Toolbar"

**Comment by benoitgrelard** [comment]
Hey @sohcfst,

Just so I'm clear, are you asking for that behaviour for the `RadioGroup` primitive or for the `Toolbar` primitive to have a radio group component?

**Comment by sohcfst** [comment]
Hi @benoitgrelard! 

I'm asking for that behavior for the `RadioGroup`, it just so happens that by w3 standards, the behavior of that `RadioGroup` is expected when it it's inside of a `Toolbar`.  (It looks like `Toolbar` already has that behavior via `ToggleGroup`. )

To give more context, we have a very long multistep form. We didn't want users to have to select a radio item, then hit a submit button to move forward to the next form item, rather, we wanted to combine submission + value selection into `onClick` or something. 

For keyboard users, we basically _don't_ want `onValueChange` to be triggered unless the user hits space. Currently with `RadioGroup`, arrow key navigation triggers `onValueChange`, which doesn't play well with this UX described above

Thank you much - please let me know if you need anything else. Cheers!

**Comment by benoitgrelard** [comment]
Hi @sohcfst,

I understand your context better now. That being said, it's really non-standard UX and I am not sure we would want to expose this in `RadioGroup` as that isn't how radio groups behave on the web or natively, thus breaking user expectations.

There is a reason they behave this way specifically in the context of a toolbar, that's because arrow keys may be use to navigate over the whole toolbar, so you may need to navigate over and past these items without modifying them on the fly.

I wouldn't really recommend it for the reasons above, but If you still wanted to go ahead with this particular UX for your case, you can achieve it by preventing our default behaviour (check it when focused) by calling `event.preventDefault()` in `onFocus`:

Here's an example: https://codesandbox.io/p/sandbox/radiogroup-dont-change-value-on-focus-spvhfh?file=%2FApp.jsx%3A13%2C11-13%2C54

**Comment by sohcfst** [comment]
@benoitgrelard thank you for the explanation @benoitgrelard!

It's hard to catch these things in design reviews and we're already committed to a timeline. We ended up going with a list of buttons which also does not feel right since we want to signal only one option can be clicked and selected...

Surely this has to be solved in mobile world in terms of accessibility. 

Anyway - appreciate it!

**Comment by benoitgrelard** [comment]
> It's hard to catch these things in design reviews and we're already committed to a timeline. We ended up going with a list of buttons which also does not feel right since we want to signal only one option can be clicked and selected...

Yeah that's not ideal indeed.

At least you know how to do this for next time in case it comes up again.
