### ISSUE TITLE
Can I use DropdownMenu without DropdownMenu.Trigger?

### ISSUE THREAD

**Issue by sgonv** [radix-ui/primitives#2173]
In case of the Dialog, I can use it without Dialog.Trigger. Instead, I can pass `open` and `onOpenChange` property directly, it can trigger dialog's opening. (https://www.radix-ui.com/docs/primitives/components/dialog#close-after-asynchronous-form-submission)
But DropdownMenu, I cannot trigger with `open` and `onOpenChange` property, only `DropdownMenu.Trigger` worked. Is it a bug? or intended?

**Comment by benoitgrelard** [comment]
Hey @sgonv,

> Can I use DropdownMenu without DropdownMenu.Trigger?

No you can't because the content needs to be positioned against the trigger.

> In case of the Dialog, I can use it without Dialog.Trigger. Instead, I can pass open and onOpenChange property directly, it can trigger dialog's opening. (https://www.radix-ui.com/docs/primitives/components/dialog#close-after-asynchronous-form-submission)

Whilst you technically can make this work, we wouldn't recommend it because in doing so you will be missing some crucial accessibility attributes on the trigger.

---

Basically, the patterns are meant to be used fully with all their parts (unless specifically stated as optional)

**Comment by rimzzlabs** [comment]
hi @benoitgrelard how about when clicking on a <tr> component? if I pass `asChild`, it will shrink my entire table row
