### ISSUE TITLE
`DropdownMenu.Item`s positioned over the trigger will auto select on opening the `Dropdown`

### ISSUE THREAD

**Issue by jpreeb** [radix-ui/primitives#2186]
### Current Behavior

I found what I think is a bug in the `DropdownMenu` primitive. My use case is that I want to use a dropdown for a hamburger menu and style the dropdown to be a fixed sidebar in my application. The styling causes the `DropdownMenu.Content` and in turn a `DropdownMenu.Item` to appear over the trigger itself.

When I click the trigger it "auto-selects" the first menu item. I've created a code sandbox forked from the one here: https://www.radix-ui.com/docs/primitives/components/dropdown-menu (https://codesandbox.io/p/sandbox/ecstatic-worker-lb4bz9?file=%2FApp.jsx%3A23%2C1) that illustrates the problem.

I'm just adding an `onSelect` handler that console logs when the first item (over the trigger) is selected and modifying the CSS to style the first `DropdownMenu.Content`/`DropdownMenu.Item` above the trigger:

```jsx
// App.jsx
<DropdownMenu.Item
  className="DropdownMenuItem"
  onSelect={() => {
    console.log("on select ran")
  }}
>
  New Tab <div className="RightSlot">⌘+T</div>
</DropdownMenu.Item>
```

```css
/* styles.css */
.DropdownMenuContent {
  position: absolute;
  top: -40px !important;
  left: -60px !important;
}
```

In this video recording the bug is illustrated. The first couple of clicks where it "auto-selects" is just a mouse click. The one where it stays open I mousedown, drag and release outside of the `DropdownMenu.Content`:

https://github.com/radix-ui/primitives/assets/1353899/c18805bf-13e6-4759-99f6-2015abd0afbb

### Expected behavior

Triggering a dropdown that will overlay the trigger should stay open and not select an item.

### Reproducible example

https://codesandbox.io/p/sandbox/ecstatic-worker-lb4bz9?file=%2FApp.jsx%3A23%2C1

### Your environment

Forked from the website sandbox (I assume everything is latest)
Note: I am on Chrome: Version 113.0.5672.126 (Official Build) (x86_64) on Mac

**Comment by jpreeb** [comment]
For anyone experiencing the same issue I have temporary workaround where I'm setting the overlaid `DropdownMenu.Item` `disabled` and using state to re-enable it after a 500ms timeout (updated in `onOpenChange`). Haven't done extensive testing but it seems to work for now.

Understandably this is not ideal, but just posting in case it's helpful to anyone else.

**Comment by benoitgrelard** [comment]
Hi @jpreeb,

It isn't a bug per se as this isn't how the component is meant to be used, it is meant to pop out of the trigger and position next to it. This is why we don't handle this case.

The reason it opens then closes is because we support selecting items in one interaction:
- pointer down on trigger
- pointer move to item
- pointer up on item -> activates

This is contrast to our default positioning for `Select` for example where it is expected for the item to be on top of the trigger (that's the whole point of it in fact). In this scenario we do handle this case more precisely.

With that in mind, it does mean that technically we could handle this for `DropdownMenu` too but I am a little reluctant potentially as it could produce bad UX, given this isn't how the component is supposed to be used.

I will keep the issue open as a potential enhancement for now and we'll see if more people want it or not.

✌️

**Comment by jpreeb** [comment]
Thanks for the quick explanation @benoitgrelard, much appreciated. Curious as well if the community is running into this issue.

**Comment by benoitgrelard** [comment]
I will close the issue as I don't think we will work on adding this as it goes against the component usage.
See my [comment](https://github.com/radix-ui/primitives/issues/2186#issuecomment-1574058791) for more details.
