### ISSUE TITLE
Playwright click() action triggers the element to appear then disappear right away. 

### ISSUE THREAD

**Issue by tielushko** [radix-ui/primitives#2288]
## Bug report

When using playwright testing, especially in codegen, clicking on the select/dropdown elements causes the popover to instantly close. 

### Current Behavior

When using .click() on select locator, the options open then immediately close, making the popover content invisible to playwright. 
### Expected behavior

I would expect the selector to not close immediately after triggering it open with .click() call on playwright locator. 

<img width="1257" alt="image" src="https://github.com/radix-ui/primitives/assets/46033508/960d3c65-ac4b-4ad4-a6f4-445c713f71c5">

<img width="612" alt="image" src="https://github.com/radix-ui/primitives/assets/46033508/1d1e2339-c446-4ad5-9b8e-145b89a7a277">

### Reproducible example
Can't provide the exact example. I ran the following in my project.  

1. npx install playwright
2. npx playwright codegen
3. navigate to https://www.radix-ui.com/docs/primitives/components/select
4. Attempt to click on the selector. 
5. Observe how it flashes open then closes right away. 

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by JoshApp** [comment]
running into the same issue.

**Comment by benoitgrelard** [comment]
It probably is due to their implementation under the hood, because our select responds to `pointerdown` to open, and then `pointerup` to select an item, so guessing they simulate that and what's happening is it's opening and selecting the first item that's overlaid.

**Comment by dvaldivia** [comment]
@tielushko did you solved this problem?

**Comment by tielushko** [comment]
Hey @dvaldivia, I haven't been paying attention to this issue anymore and haven't found a workaround.

**Comment by iulianbaranai** [comment]
I encountered this issue while testing a DropdownMenu for language switching in a Next.js 15 application. The dropdown works perfectly in Chromium and Firefox Playwright tests, but completely fails in WebKit.

  Environment:
  - Playwright v1.56.0
  - Radix UI DropdownMenu (latest)
  - Next.js 14 with React 19
  - Test results: Chromium ✅ 14/14 | Firefox ✅ 14/14 | WebKit ❌ 0/14

  Symptoms:
  - Trigger element exists and is actionable (aria-expanded="false", data-state="closed")
  - Portal never appears in DOM after any interaction
  - document.querySelectorAll('[data-radix-portal]').length always returns 0
  - TimeoutError: locator.click: Timeout 30000ms exceeded

  Failed Attempts (All Resulted in NO Portal Rendering)
  I systematically tried 7 different approaches, confirmed via screenshots and DOM inspection:

1. Standard click with explicit wait

  ```
const languageSwitcher = page.locator('[data-testid="language-switcher"]')
  await languageSwitcher.click()
  await dropdownOption.waitFor({ state: 'visible', timeout: 10000 })
  // ❌ Portal never appears
```

  2. Hover + Focus + Click combination
```
  await languageSwitcher.hover()
  await languageSwitcher.focus()
  await languageSwitcher.click()
  // ❌ Portal never appears
```

  3. Keyboard interaction (Space/Enter)
 ```
 await languageSwitcher.press('Space')
  await languageSwitcher.press('Enter')
  // ❌ Portal never appears
```

  4. Manual PointerEvent via page.evaluate()
```
  await page.evaluate(() => {
    const trigger = document.querySelector('[data-testid="language-switcher"]')
    const event = new PointerEvent('pointerdown', { bubbles: true, cancelable: true })
    trigger.dispatchEvent(event)
  })
  // ❌ Portal never appears
```

  5. Playwright dispatchEvent (pointerdown + pointerup)
```
  await languageSwitcher.dispatchEvent('pointerdown')
  await languageSwitcher.dispatchEvent('pointerup')
  // ❌ Portal never appears
```

  6. Playwright dispatchEvent (click)
```
  await languageSwitcher.dispatchEvent('click')
  // ❌ Portal never appears
```

  7. Increased timeouts (10s, 15s, 30s)
  - Confirmed timeout is NOT the issue - portal simply never renders

  Debug Evidence:
  - Trigger's data-state updates correctly
  - Console shows no errors
  - Screenshots confirm zero portal elements in DOM
  - Real Safari browsers work perfectly (production unaffected)

  **Working Solution:** Browser-Specific Testing Strategy
  Since this is a WebKit/Playwright automation limitation (not affecting real users), I implemented a pragmatic workaround:

  ```
/**
   * Language switching helper with WebKit workaround
   */
  async function switchLanguage(page: Page, targetLocale: 'en' | 'nl') {
    const browserName = page.context().browser()?.browserType().name()

    if (browserName === 'webkit') {
      // WebKit: Bypass broken UI, test actual functionality (cookie-based)
      await page.context().addCookies([{
        name: 'preferredLanguage',
        value: targetLocale,
        domain: 'localhost',
        path: '/',
        expires: Date.now() / 1000 + 365 * 24 * 60 * 60,
        sameSite: 'Lax',
      }])

      // Navigate with proper locale (matches production behavior)
      await page.goto(`/${targetLocale}`)
      await page.waitForLoadState('domcontentloaded')
    } else {
      // Chromium/Firefox: Standard UI interaction (works perfectly)
      await page.locator('[data-testid="language-switcher"]').click()
      await page.locator(`[data-testid="language-switch-${targetLocale}"]`).click()
    }
  }
```

  Test Results:
  - Before: 0/14 WebKit tests passing (100% failure)
  - After: 14/14 WebKit tests passing (100% success)
  - Chromium & Firefox: Still 14/14 passing

 Note: This appears related to how WebKit handles React Portals in automated testing environments. Production Safari works flawlessly.
