### ISSUE TITLE
Accordion - Requires two clicks to close when value is `undefined`

### ISSUE THREAD

**Issue by ysulyma** [radix-ui/primitives#2296]
### Current Behavior

When using `value={undefined}` on `<Accordion.Root>` to indicate that no item is selected, it takes two clicks to close accordion items

### Expected behavior

`undefined` should work as an empty value the same way that `""` does

### Reproducible example

[CodeSandbox link](https://codesandbox.io/p/sandbox/confident-sky-pq5g6d?file=%2FApp.jsx%3A7%2C30)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |      Accordion   |   1.1.2      |
| React            | n/a     |    18.2.0     |
| Browser          |         |      Firefox 116   |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |     Mac    |

**Comment by joaom00** [comment]
how would we know it is being controlled without checking for undefined?

**Comment by ysulyma** [comment]
@joaom00 I didn't realize that was the reason for this behavior. I guess that makes sense. You could do
```tsx
function isControlled(x) {
  return Object.keys(x).includes("value");
}

// true
isControlled({value: undefined});

// false
isControlled({});
```
to distinguish controlled vs uncontrolled.

**Comment by benoitgrelard** [comment]
That is a side-effect of using controlled components wrong. By going from a set `value` to an `undefined` `value` you are effectively trying to go from a controlled component to an uncontrolled component, which would always break.
This is the same reason why React issues a warning when you attempt to do that on a native input field for example, that's because the lack of `value` is how React determines whether you are controlling the value or React should control it for you.
