### ISSUE TITLE
Dialog: On mobile, keyboard hide the dialog

### ISSUE THREAD

**Issue by Natchii59** [radix-ui/primitives#2323]
## Bug report
On phone, the keyboard hides the dialog when opening it.

### Current Behavior
When you put an input with autoFocus, it directly focuses the input when the dialog opens, and it doesn't have time to move the dialog.

https://github.com/radix-ui/primitives/assets/96394660/9b2409e6-65f1-4dcf-a9fa-c87242ff0564

### Expected behavior
It would be nice to crop the dialog so it's centered between the top of the page and the end of the keyboard. (see the video, when I leave the textarea then I come back to it, it moves the dialog)

### Reproducible example
You just need to add the dialog box example to the radix-ui site

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-dialog | 1.0.4 |
| React            | n/a     | 18.2.0 |
| Browser          | Safari IOS | 16.6 |
| Node             | n/a     | 18.12.1 |
| npm/yarn         | pnpm | 8.6.7 |
| Operating System | IOS | 16.6 |

**Comment by Emiliano-Bucci** [comment]
@Natchii59 Hey, did you find a solution? I'm stucked here as well, with the consequence that when the keyboard is opened the content don't scroll :/

**Comment by Natchii59** [comment]
@Emiliano-Bucci no...

**Comment by Emiliano-Bucci** [comment]
@Emiliano-Bucci I've solved by using headless ui dialog.

**Comment by dy** [comment]
I've prevented focus trap on `Dialog.Content` and enabled `autoFocus` on internal input:
```jsx
<Dialog.Content onOpenAutoFocus={e=>e.preventDefault()}>
  <input autoFocus />
</Dialog.Content>
```

**Comment by benoitgrelard** [comment]
This isn't really an issue with the component, but rather with styling, or app-level use-case where you can decide to move focus somewhere else instead of the input using `onOpenAutoFocus`. I would recommend moving the focus somewhere though, not preventing it entirely like @dy is showing above, that is an accessibility issue otherwise. A common recommendation from WAI-ARIA is to set `taxIndex={-1}` on the dialog title and programatically focus there instead.
