### ISSUE TITLE
[Checkbox] Page scrollbars with Checkbox inside scrollable container

### ISSUE THREAD

**Issue by steschwa** [radix-ui/primitives#2402]
### Current Behavior

If a Checkbox is nested within a `<form>` in a scrollable container (e.g. ` max-height: 400px; overflow-y: auto;`) the browser shows a scrollbar for the page even thought the visible content does not overflow the page. 

You can see the problem in the below recording: the `<body>` is scrollable (as seen by the yellow color):

![CleanShot 2023-09-22 at 11 26 05](https://github.com/radix-ui/primitives/assets/24265130/60deb7fb-fa14-4a2e-820f-1d6a08717443)

### Expected behavior

What i would expect is, that there are no scrollbars shown (as the scrollable container already has one).

`body` is now scrollable and the yellow background-color is not shown:

![CleanShot 2023-09-22 at 11 27 20](https://github.com/radix-ui/primitives/assets/24265130/26ef3ac6-93c2-4ac3-bdeb-b074904b76e7)

### Reproducible example

[Example](https://codesandbox.io/s/brave-kare-x7smc7?file=/src/App.tsx)

### Suggested solution

I found out that an easy solution would be to hide the `input[type="checkbox"]` element that is rendered if the Checkbox is nested within a `<form>` element with `display: none`. Not sure if that creates accessibility problems, thought (open [this file](https://codesandbox.io/s/brave-kare-x7smc7?file=/src/app.css) and uncomment the relevant styles at the bottom).

### Environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-checkbox    |     1.0.3    |
| React            |     |     18.2.0    |
| Browser          |     Chrome / Safari    |         |

**Comment by Aluisio** [comment]
Hello, I have exactly the same problem and your solution also worked for me.
In my tests the problem is related to the `<form>` tag, as doing the same example with a div the problem does not occur.

@benoitgrelard What do you think about this behavior?

| Software | names(s) | version
| -------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-checkbox | 1.4.0 |
| React | | 18.2.0 |
| Browser | Microsoft Edge | 119.0.2151.46 (Compilação oficial) (arm64) |
| SO | macOS | Sonoma 14.1 |
