### ISSUE TITLE
[Dropdown menu + Dialog]The dialog cannot be opened when use in the dropdown menu

### ISSUE THREAD

**Issue by melon95** [radix-ui/primitives#2471]
### Current Behavior
When opening a drop-down menu and clicking on a menu item, the click does not open the Dialog directly.

https://github.com/radix-ui/primitives/assets/35761035/f75e0340-ffb7-4388-b052-e966fd203ac8

### Expected behavior

When I click on the first item in the drop down menu I am able to open a Dialog as if I had clicked on the button below.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/p/sandbox/cool-kilby-yfzqxt?file=%2FApp.jsx%3A7%2C13)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  react-dropdown-menu react-dialog      |         |
| React            | latest     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | latest     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by jayelg** [comment]
Just happened to be dealing with the same issue.

I have modified your sandbox code to solve this issue.
The idea is that instead of using a <Dialog.Trigger /> component, you will set the open state for the dialog directly using onClick to run a function that sets the open state of the dialog to true.
the state and the state setting function can be passed to `<Dialog.Root open={newTabOpen} onOpenChange={setnewTabOpen}>` as per the [Radix Dialog API docs](https://www.radix-ui.com/primitives/docs/components/dialog#api-reference).
Instead of nesting the Dialog code inside the dropdown, you can put it anywhere outside the dropdown code as it doesn't have to be located with the triggering object anymore.

[Code Sandbox](https://codesandbox.io/p/sandbox/kind-greider-4qwtfr)

**Comment by melon95** [comment]
@jayelg Thank you very much for your answer, this is a very good way, but there is no way to extract the Dialog in my real code. I've already achieved what I want with the Dropdown Menu's `open` property and `onOpenChange` method, and `e.preventDefault()`.

**Comment by yudinvictor** [comment]
@melon95  Hi, I am facing the same problem (can't get the dialog out). Could you please fix your demo above with your solution?
