### ISSUE TITLE
[Checkbox] Controlled Checkbox inside a form will trigger an infinite loop

### ISSUE THREAD

**Issue by clementoriol** [radix-ui/primitives#2549]
### Current Behavior

A controlled `<Checkbox />` will trigger an infinite loop when : 
- The Checkbox is in a `<form/>`
- The Checkbox has a parent that triggers a state change (changing the Checkbox controlled value) on Click, and that parent is clicked.

**Error :** 
```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

### Expected behavior

A Controlled Checkbox inside a `<form/>` should work as expected and re-render properly when its `checked` prop changes, even if this change is triggered by a parent component.

### Reproducible example

Here's a reproduction example:
[Codesandbox link](https://codesandbox.io/p/sandbox/jovial-ptolemy-spsz94?file=%2Fsrc%2FApp.tsx%3A9%2C83)

### Suggested solution

Not sure

### Additional context

This seems to only happen if the setState is triggered from a parent component.
If a sibling of the Checkbox mutates the state, everything works as expected.

See : 
[Codesandbox link](https://codesandbox.io/p/sandbox/intelligent-microservice-6cvfw3?file=%2Fsrc%2FApp.tsx%3A30%2C21)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-checkbox     |   1.0.4       |
| React            | n/a     |      18.2.0   |
| Browser          |    Chrome     | 119.0.6045.159         |
| Assistive tech   |         |         |
| Node             | n/a     |  18.15.0       |
| npm/yarn         |   pnpm      |      7.33.1   |
| Operating System |     macOS    |    Ventura 13.3     |

**Comment by takagimeow** [comment]
I also encountered a similar issue as @clementoriol.

It turned out that the problem wasn't with the `<Checkbox>` itself.
Inside the `<Checkbox>`, a component called `<BubbleInput>` is used. This component is only placed if a `<form>` element exists as a parent element. Inside `<BubbleInput>`, `useEffect` is utilized to compare the current and previous values of `checked`, and if they differ, the `onclick` event is dispatched.
This causes event bubbling, which triggers the `onClick` event handler attached to the parent `<div>` element. 
Since the `onClick` event handler inside updates the value of `checked`, it again triggers a `useEffect` callback in `<BubbleInput>`. This repetition results in the "Maximum update depth exceeded" error.

To avoid this, I think the problem can be solved by adding logic to the `onClick` event handler attached to the parent element, where it compares the `currentTarget` and `target` values of the event object, and does nothing if they are different.

```tsx
import * as React from "react";
import * as RadixCheckbox from "@radix-ui/react-checkbox";

export function App() {
  const [checked, setChecked] =
    React.useState<RadixCheckbox.CheckedState>(false);

  return (
    <form>
      <div
        onClick={(e) => {
          if (e.currentTarget !== e.target) {
            return;
          }
          setChecked(!checked);
        }}
      >
        <RadixCheckbox.Root checked={checked} onCheckedChange={setChecked}>
          <RadixCheckbox.Indicator>✓</RadixCheckbox.Indicator>
        </RadixCheckbox.Root>
        Click me
      </div>
    </form>
  );
}
```

**Comment by oleksandrstarov** [comment]
Same for Switch  component - 1.0.3. Using in a form causes infinite loop

**Comment by clementoriol** [comment]
@benoitgrelard The issue exists in standard `<form>` component, I don't think it's related to the Radix `Form` primitive.

**Comment by MateoKruk** [comment]
This happened to us when using the `<Checkbox />` inside a `<form />` tag

**Comment by CarlosVergikosk** [comment]
Reporting the same problem here, for someone looking for a quick solution, you can use version 0.0.15 of checkbox.

**Comment by andersonba** [comment]
Same here!

**Comment by scherroman** [comment]
Also ran into this infinite loop issue, only happens when the checkbox is rendered within a `<form>`. Baffling and spent the better part of a day trying to debug it as neither the `onClick` or `onCheckedChange` callbacks appear to fire on the `<Checkbox.Root>` even though an `onClick` event bubbles up to the parent div.

**Comment by GuiSelair** [comment]
> Also ran into this infinite loop issue, only happens when the checkbox is rendered within a `<form>`. Baffling and spent the better part of a day trying to debug it as neither the `onClick` or `onCheckedChange` callbacks appear to fire on the `<Checkbox.Root>` even though an `onClick` event bubbles up to the parent div.
> 
> [@andersonba](https://github.com/andersonba)'s [workaround with the memoized root](https://github.com/radix-ui/primitives/issues/3192#issuecomment-2504741692) worked well. Another workaround is to change the `<div>` you want to put the `onClick` handler on into a `<label>`, since clicking on a label that wraps a checkbox automatically toggles the checkbox.
> 
> ```
> import * as RadixCheckbox from "@radix-ui/react-checkbox";
> 
> export function App() {
>   const [checked, setChecked] =
>     React.useState<RadixCheckbox.CheckedState>(false);
> 
>   return (
>     <form>
>       <label className="flex items-center gap-2">
>         <RadixCheckbox.Root checked={checked} onCheckedChange={setChecked}>
>           <RadixCheckbox.Indicator>✓</RadixCheckbox.Indicator>
>         </RadixCheckbox.Root>
>         <span>
>           Check me
>         </span>
>       </label>
>     </form>
>   );
> }
> ```

This worked for me! Thanks!
