### ISSUE TITLE
[Dialog] "flex-direction: column-reverse" scrolling blocked at the bottom

### ISSUE THREAD

**Issue by MeDeyvid** [radix-ui/primitives#2657]
### Current Behavior
When adding the direction of the reversal column, the scroll gets stuck at the end, needing click interaction to start working again, but every time it reaches the end it freezes again.

### Reproducible example

[CodeSandbox Example](https://codesandbox.io/p/sandbox/dreamy-snowflake-t3f7yn?file=%2Fsrc%2FApp.tsx)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  dialog    |   1.0.5   |
| React            | n/a     |   18     |
| Browser          |    Chrome     |  120.0.6099.216   |
| Assistive tech   |         |         |
| Node             | n/a     |    20.9   |
| npm/yarn         |  npm   |  10.1.0   |
| Operating System | Sonoma  | 14.2.1 |

**Comment by kal07** [comment]
I think this is a bug in css not in the dialog component because I had the same issue when moving things around in you example

**Comment by benoitgrelard** [comment]
@kal07 yeah I was going to say the same, I don't think it's an issue with the dialog as it doesn't really do anything with scroll in the content, that isn't one of its responsibilities.

**Comment by kag359six** [comment]
@benoitgrelard @dreijer-dev  this is definitely not a CSS issue. It appears the issue is related to the usage of `RemoveScroll` in the `Dialog.Overlay` component, which is the only place scrolling is hijacked in the Dialog component. 

Removing the `Dialog.Overlay` in the example provided "unlocks" scrolling.

[Here is reproducible codesandbox forked from the one provided by @MeDeyvid ](https://codesandbox.io/p/sandbox/fervent-jepsen-pk3sh5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clum3pur700072e66ent9ungy%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clum3pur700032e66hk3tj3h5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clum3pur700042e663sb1dwn1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clum3pur700062e66rxyngnyw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clum3pur700032e66hk3tj3h5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clum3pur700022e665j4wc9pw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A25%252C%2522startColumn%2522%253A10%252C%2522endLineNumber%2522%253A25%252C%2522endColumn%2522%253A10%257D%255D%257D%255D%252C%2522id%2522%253A%2522clum3pur700032e66hk3tj3h5%2522%252C%2522activeTabId%2522%253A%2522clum3pur700022e665j4wc9pw%2522%257D%252C%2522clum3pur700062e66rxyngnyw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clum3pur700052e66b0444lmz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clum3pur700062e66rxyngnyw%2522%252C%2522activeTabId%2522%253A%2522clum3pur700052e66b0444lmz%2522%257D%252C%2522clum3pur700042e663sb1dwn1%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clum3pur700042e663sb1dwn1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by lauri865** [comment]
Thanks a lot @kag359six!

I've been troubled by this issue for some time, and I thought it was a browser issue. But definitely the culprit is `RemoveScroll`.

Temporary workaround – add to Overlay component:
`onWheel={(e)=>e.stopPropagation()}`
