### ISSUE TITLE
I am not able to set my Accordion horizontaly

### ISSUE THREAD

**Issue by Calculator-dev** [radix-ui/primitives#2693]
![Screenshot from 2024-02-09 10-02-28](https://github.com/radix-ui/primitives/assets/27162413/119929b0-278e-4f13-8e08-fa7d27462706)
I am not able to set my Accordion horizontaly. I am not sure if I'm doing something wrong here but it is always vertical

**Comment by cvillar6** [comment]
Same here

**Comment by benoitgrelard** [comment]
Primitives are unstyled, the `orientation="horizontal"` you pass to the primitive is about setting things up for accessibility and functionality (ie. keyboard using left/right arrows instead of up/down for example).

It is your responsibility to style the component to look horizontal.

I believe your issue is `flex-col` as that's layout out the items vertically.

Here's an example in our storybook: https://601857eb614bae0021c9b9dd-evgfcrkbbq.chromatic.com/?path=/story/components-accordion--horizontal

**Comment by Calculator-dev** [comment]
Thank you very much :)

**Comment by cvillar6** [comment]
crack
