### ISSUE TITLE
[ContextMenu] Default context menu with "html" target on border rightclick

### ISSUE THREAD

**Issue by odeyal0** [radix-ui/primitives#2757]
### Current Behavior
Default context menu with html target on contextmenu border rightclick.

https://github.com/radix-ui/primitives/assets/46008279/ee2b15c3-df8f-4942-bdb4-13ea172f221f

### Reproducible example
https://codesandbox.io/p/devbox/radix-context-menu-bug-zlqgfp

### Your environment
Check sandbox

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Browser          |   google chrome|     |
| Operating System | windows         | 11  |

**Comment by benoitgrelard** [comment]
Where are you logging the pointer events from in the sandbox? I don't see it in the source.
I also can't seem to reproduce the issue either way.

**Comment by odeyal0** [comment]
I just added lisener to the console.
Now added to sandbox.

**Comment by benoitgrelard** [comment]
I managed to reproduce it a few times, but it's extremely hard haha.

It doesn't seem related to the border at all, because even without it can happen.
It seems there's exactly 1px where it can happen, just outside of the content.

I'm not sure we can fix it really, it kinda looks like a browser bug, given that it happens even if we prevent default on context menu `onContextMenu` handler…

**Comment by odeyal0** [comment]
Ok)
I used this workaround to fix it :
```ts
  const handleContextMenu = useCallback(
    (e: MouseEvent) => e.preventDefault(),
    [],
  );

  useEffect(() => {
    document.addEventListener('contextmenu', handleContextMenu);

    return () => document.removeEventListener('contextmenu', handleContextMenu);
  }, [handleContextMenu]);
````
