### ISSUE TITLE
[Tooltip] Unable to click content inside tooltip after dismissing tooltip by clicking the trigger

### ISSUE THREAD

**Issue by masbagal** [radix-ui/primitives#2768]
### Current Behavior

1. There's a tooltip containing a button in its content.
2. Hover to open the tooltip, then click the trigger to dismiss the tooltip.
3. Hover again to open the tooltip, click the button inside tooltip content --> tooltip is dismissed and the button click handler doesn't run

https://github.com/radix-ui/primitives/assets/16324649/7858a900-20ce-41b6-9e02-7ec6b5f6f78b

### Expected behavior

Even if the tooltip is dismissed by clicking the trigger, the button inside the tooltip is still clickable

### Reproducible example

[CodeSandbox Radix Tooltip Issue](https://codesandbox.io/p/sandbox/radix-tooltip-click-2khlqg?file=%2Fsrc%2Findex.js)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-tooltip      |   1.0.7      |
| React            | n/a     |   18      |
| Browser          |   Chrome/Edge      |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
Tooltips should never have interactive content inside them, they are purely for small amounts of textual information. This is because their interactive content isn't accessible.

Note, that the trigger in your case (little i button) serves no other purpose than showing that information.

You should use a `Popover` instead, where clicking the trigger would open (rather than hover) and then your content is accessible inside, so you can have interactive stuff like a button in your case.
