### ISSUE TITLE
Context error when using dropdown in next js 14

### ISSUE THREAD

**Issue by KaidiMohammed** [radix-ui/primitives#2814]
## Bug report
The dropdownmenu in this page https://www.radix-ui.com/primitives/docs/components/dropdown-menu is not working well (at least in my case) in a next js 14 project, this error is returned when running the app: 
Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function

### Current Behavior
Importing the component in a page, displays this error : 

![image](https://github.com/radix-ui/primitives/assets/43373719/44adf5db-b280-4cbe-af40-cf52f552d202)

Adding "use client" to the component let dropdown display but without the corresponding css : 
![image](https://github.com/radix-ui/primitives/assets/43373719/f095e714-758b-48f4-89bb-fb39e3f09a14)

All the necessary css is configured correctly using tailwind 

Other components, like buttons for example are displayed coreectly.

### Expected behavior
Having the dropdownmenu displayed correctly : 
![image](https://github.com/radix-ui/primitives/assets/43373719/c9cbc81e-cc54-4681-a349-7cfd55961d09)
 
### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     latest    |         |
| React            | 18   |         |
| Browser          |     chrome    |         |
| Assistive tech   |         |         |
| Node             | 20     |         |
| npm/yarn         |     npm    |         |
| Operating System |   macos      |         |

**Comment by KaidiMohammed** [comment]
Apparently there was a CSS file conflicts in my project, by cleaning the code, it works fine now.
"use client" is mandatory to fix the error :
Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function

**Comment by Senbonzakura1234** [comment]
I think this issue need to be reopen since this happened with other radix primitive components as well, and they never mention it in their docs that we need to add `'use client'` to make it works. 

Some primitive components doesn't require any extra hooks to works, like [Scroll Area](https://www.radix-ui.com/primitives/docs/components/scroll-area). 

We either need make a fix to the primitive components or update the docs mentionning that we need to add `'use client'`.
