### ISSUE TITLE
Allow disabling the `display: table` CSS on `SrollArea`

### ISSUE THREAD

**Issue by hspak** [radix-ui/primitives#2964]
### Overview

I noticed that the `ScrollArea` component sets this `display: table` style as a strategy to recalculate thumb sizes: https://github.com/radix-ui/primitives/blob/55f9189a4b3e1a525c89297d5f337c03b2a44f61/packages/react/scroll-area/src/ScrollArea.tsx#L178-L187)

### Examples in other libraries

N/A

### Who does this impact? Who is this for?

There's a side navigation that I'm trying to use the `ScrollArea` component for that we allow for dynamic re-sizing and this table display is not respecting the width value from the parent.

Manually removing the CSS style from the browser solves the issue.

### Additional context

N/A

**Comment by matiasvlevi** [comment]
Same issue here,

In the mean time I resorted to something like this:

```tsx
useEffect(() => {
  const elem: HTMLElement | null = document.querySelector(
    ".my-scroll-area > div > div"
  );
  if (elem) elem.style.display = "block";
}, []);
```

this works, but it's also horrible. We really need a fix for disabling `display:table`

**Comment by F-z-Coder** [comment]
Same issue

**Comment by aishwaryaborkar** [comment]
Bumping this, experiencing the same issue. Because of the `display: table` and `min-width: 100%`, the content overflows but you can't see it because of `overflow: hidden` and as a result, the content looks not centered (since overflow is hidden; it actually is centered). Ideal case would be allowing to override this.

**Comment by moonrailgun** [comment]
idk but when i check source code, this code has been changed in https://github.com/radix-ui/primitives/commit/f6d70b3050929effc910971ddd3a5259c9de17ff

did its means have been resolved?

**Comment by F-z-Coder** [comment]
Yes

> idk but when i check source code, this code has been changed in [f6d70b3](https://github.com/radix-ui/primitives/commit/f6d70b3050929effc910971ddd3a5259c9de17ff)
> 
> did its means have been resolved?

Yes now it resolved in version 1.2 but currently this version is in Rc mode

**Comment by moonrailgun** [comment]
yeah, look forward 1.2.0 release.

i am watching it.

![image](https://github.com/user-attachments/assets/bfb82c66-f02a-4943-8092-ba7eeb14c55d)

**Comment by hspak** [comment]
This appears fixed on 1.2.0 and it's been released! 🎉

**Comment by omridevk** [comment]
Should re-open:
https://github.com/radix-ui/primitives/pull/3225
the fix was reverted.

**Comment by jkhaui** [comment]
> Should re-open: [#3225](https://github.com/radix-ui/primitives/pull/3225) the fix was reverted.

Please, please add a prop to use anything but display: table on the nested div... It's so painful to work with...

I even tried using `asChild` with a flex container as the immediate child of ScrollArea.Viewport, but it messed up scrolling

**Comment by tgds** [comment]
yes, please! this breaks layout and its impossible to work with in certain scenarios as children stretch the table div (max-width is not respected as we enter table formatting context and intrinsic table width wins). for example, if you need items in a vertical scrollarea with text ellispsis and set  `white-space: nowrap; text-overflow: ellipsis; overflow: hidden;` on the item, the items are stretched and cut off.

**Comment by FarhanShares** [comment]
Bump, the issue is real. I had to spent 2 days just after this. Never knew this was from ScrollArea until I inspected the parent elements one by one. Using one of the hacks to fix now, but this should be solved in a better way.

**Comment by 29thfloor** [comment]
Still hitting this on `1.2.10.` Our use case is an outline/navigation panel (sidebar with truncated section titles) — `text-overflow: ellipsis` breaks because the `display: table` wrapper expands to the intrinsic text width instead of being constrained by the viewport.

Current workaround:
```
[data-radix-scroll-area-viewport] > div {
  display: block !important;
  min-width: 0 !important;
}
```
This fixes truncation for vertical-only scroll areas but would break legitimate horizontal scroll cases, so it needs to be scoped carefully. A per-axis overflow prop on `Root` or a `display` prop on `Viewport` would let us opt out cleanly without targeting internals.
