### ISSUE TITLE
Portalled tooltips appear behind modals/overlays that have z-index

### ISSUE THREAD

**Issue by mattaningram** [radix-ui/primitives#368]
## Bug report
Using a portalled tooltip in an overlay or modal that has a z-index means the tooltip gets positioned behind the modal.

### Current Behavior

Portalled tooltips are placed at end of `<body>` with `<radix-portal>` element and a `<div>` with positioning. These cannot be styled specifically for tooltip instances and therefore can't have z-index set on them. So they can't appear above any item that created them that has a z-index.

To attempt to fix I set the tooltip portalled to `false`, but this also illustrates the problem from this [issue](https://github.com/radix-ui/primitives/issues/367) where a not portalled tooltip inside a positioned element such as a modal will not be positioned correctly:

<img width="509" alt="Screen Shot 2020-12-23 at 1 23 20 PM" src="https://user-images.githubusercontent.com/955092/103026487-0f21a580-4522-11eb-8fa0-4e71ced474d2.png">

### Expected behavior

Portalled tooltips appear above the elements that create them and/or can have a z-index set on them and are positioned correctly.

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/radix-primitives-tailwind-forked-e095i?file=/src/App.tsx)

### Suggested solution

Give the positioning div a `[radix]` attribute to allow styling with a z-index.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | Tooltip | 0.01 |
| React            | n/a     | 16.12  |
| Browser          |  Chrome, FF, Safari, Edge       | Latest |
| Assistive tech   | n/a        |         |
| Node             | n/a     |  10.17       |
| npm/yarn         | Yarn | 1.22.10 |
| Operating System | Mac + Windows | Latest |

**Comment by benoitgrelard** [comment]
Hi @mattaningram, we are aware of this and have documented it internally quite a bit (in an old private repo).
But the gist is this:

- all our components which use `Portal` internally are appended inside body (same if you were to use `Portal` directly)
- so It comes down to stacking contexts in CSS
  - if you have something inside your app that has a set `z-index`
  - but your app root doesn't define a new stacking context, then these set `z-index` element will be on top of things added after your app root (in DOM order)
- so the solution really is to create a new stacking context at the lowest-level possible of your app

For example in a next app, this might be:

```css
#__next {
  position: relative;
  z-index: 0;
}
```

We have been thinking of ways to automate this somehow:
- one option we could try is that we would do something in a top-level provider component which would do this automatically, but it's pretty tricky because we'd either need to:
  - add an extra element that would wrap their entire app (most people probably wouldn't like that I expect)
  - alternative is that we don't know what their react root element is, so we'd have to ask them for a reference to that, or a selector, etc.
 
or we bail out and just document it…

So at the very least I'd say we should add a paragraph to the docs in our `Portal` component (https://radix-ui.com/primitives/docs/utilities/portal) about this, and perhaps a link to that form all other primitives which use `Portal` internally.

Let me know if this is satisfactory.

**Comment by mattaningram** [comment]
This unfortunately doesn't solve the problem because it is very common for portalled modals+overlays at end of `body` to have z-index themselves, so even when the `radix-portal` comes after it cannot appear above them.

This currently a blocker for me to start using Radix primitives because we can't switch all of our existing components over at once and we can't remove the z-index from the modal and overlay at the moment. I was intending to use tooltips as a way to sell Radix to the rest of my team.

What is the downside to letting us add a z-index to the absolutely positioned div that sets the tooltip position inside `radix-portal`?

**Comment by benoitgrelard** [comment]
You are free to set any css anywhere in the components so there is no reason you shouldn’t be able to make your use case work, at this point you’re just in z-index war which is one reason portals are better because it’s always the last inserted that wins.

**Comment by mattaningram** [comment]
Perhaps I'm missing something in docs, where would I add styles to this element?
![image](https://user-images.githubusercontent.com/955092/103574877-b5fd2e80-4e9e-11eb-8348-43d9b79a808f.png)

I don't want to target any `div` in any `radix-portal`, I want to target the one specifically for tooltips and this has no identifying selector and nowhere indicates how to edit these inline-styles in the docs.

**Comment by benoitgrelard** [comment]
Hey @mattaningram, yeah I understand your issue a little bit better now.

We have never hit it because we don't really use z-index in our own modals, etc (there shouldn't be a need for it when using portals).

However, I can see in your case that because you don't have access to that internal div (which creates a new stacking context) you have an issue.

For now, if you're only using the `Tooltip` primitive,  you could use this escape hatch:

```css
radix-portal > div { z-index: … }
```

This of course targets the first div inside a portal, which generally isn't good enough if using more than the `Tooltip` primitive, but in your case might be ok.

We have discussed this internally, and we will add extra `data-radix-•` attributes to these (hard to reach) non-exposed elements so that you can do things like set a z-index, etc.

Does that make sense?

**Comment by mattaningram** [comment]
That would be perfect!

In the short term I'm using the `radix-portal > div { z-index: … }` approach, and in long term going to remove the z-index from my non-Radix modal/overlay components to address issue overall (since you are right that ideally they shouldn't need them).

Adding those additional `data-radix-*` attributes will allow people to fix this issue if they can't fix their modals.

Thank you! Looking forward to getting more Radix primitives into our codebase soon.

**Comment by benoitgrelard** [comment]
New data attributes added in #347

**Comment by benoitgrelard** [comment]
Hey @mattaningram, just a heads up in case you are still depending on the `radix-portal` selector as a hack (and haven't moved to the new selector), we are introducing some change to our `Portal` which should actually negate all these hacks in the first place. See #410 for more context.

**Comment by mattaningram** [comment]
Thank you so much @benoitgrelard this is great!
