### ISSUE TITLE
[Popper] Improve calculations to account for parent positioning / scroll offsets

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/primitives#370]
This is for cases when people aren't rendering in portals.

See https://github.com/radix-ui/primitives/issues/367 for example.

**Comment by tarngerine** [comment]
thanks! would also want to echo the suggestion to provide a non-calculated/collission-tested version that we can place ourselves with more manual CSS :)

**Comment by benoitgrelard** [comment]
Yep that will be possible too 👍

**Comment by jofbe** [comment]
@benoitgrelard do you have any news on this issue? I would like to use the dropdown not portalled.

**Comment by benoitgrelard** [comment]
@jofbe it hasn't been a priority at the moment so I don't have more news on this. If you let me know your use case with a sandbox, perhaps I can try and offer a temporary solution?

**Comment by dmoz-ixl** [comment]
Thanks for all your work on Radix!

I'm trying to finagle a tooltip whose content appears as an extension of the trigger. To do this, the tooltip content needs to match the width of the trigger exactly.

I tried rendering the content inside the trigger so the width could be set to 100% of the parent(trigger) using a Portal referencing the trigger with `containerRef`. I'm able to successfully match the width because it does render inside the ref, but the positioning is off because of the `translate3d` when the content is set to `portalled={false}`.

Is there a better way to either set the width of the content, or use the portal to match the width but bypass the `translate3d`? TIA!

Using Portal containerRef(matches width, odd positioning): https://codesandbox.io/s/vibrant-cohen-3pc17
Without portal(can't match trigger width, correct positioning): https://codesandbox.io/s/serverless-rgb-2wuqv

**Comment by benoitgrelard** [comment]
> EDIT: Our team is using ResizeObserver in the meantime, for a few different implementations, but in this case, to match the width of the trigger.

@dmoz-ixl I was going to suggest that you could attach a ref to the trigger to measure it and set that same width on the tooltip but it sounds like your team has figured that out already 👍
