### ISSUE TITLE
Open Dropdown on Enter/Return

### ISSUE THREAD

**Issue by tigranpetrossian** [radix-ui/primitives#377]
### Overview

Consider enabling opening Dropdown on "Enter" in addition to current "Space", "ArrowDown", "ArrowUp". 

### Examples in other libraries

https://material-ui.com/components/menus/
https://reach.tech/menu-button

### Who does this impact? Who is this for?

[WAI-ARIA](https://www.w3.org/TR/wai-aria-practices-1.2/#keyboard-interaction-13) specifies this, plus it feels like most web services (including the one we're on) support opening various popovers on "Enter". 
Don't have enough data to know if keyboard users go for "Space" or "Enter" instinctively, but I've been finding myself hitting Enter trying to open menus.

### Additional context

I'm also curious what's the rationale behind not having Trigger respond to "Enter". Happy to submit a PR (perhaps make it optional if necessary?) and update the docs.

**Comment by benoitgrelard** [comment]
Hi @tigranpetrossian,

That's a great point!

I think the original reason was because native platforms don't tend to do it, but I see no reason we couldn't add it to the relevant components, especially as you note that WAI-ARIA points out we should.

Also, if for some reason someone doesn't want it, it is easily preventable as we already compose all of our event handlers and check for `.defaultPrevented` so you could always get back to the current behaviour.

Thanks for your suggestion, we'll implement it int he relevant components.

👍
