### ISSUE TITLE
New component: HoverCard

### ISSUE THREAD

**Issue by chaance** [radix-ui/primitives#387]
An example of a `HoverCard`.

https://user-images.githubusercontent.com/805073/114011235-eb7a3500-985c-11eb-9448-412b49479611.mov

This component would be primarily for sighted users. It should only be used on links with a href. It should only ever display content that is available on the href.

A rough feature-set for `HoverCard`:

- Popper positioning. I assume we can reuse our utility for this?
- Trigger delay (research whether to use same delay as tooltip. Potentially use the same code and link them globally? Gotta do some thinking there.)
- Support for Arrow or no Arrow.
- Close on ESC.
- Don't trigger on focus.
- Try to avoid what twitter does where you can reopen the HoverCard if you hover its container before the close animation has completed?
- Should work well with `Slot`.

No focus trapping. No focus management at all.

**Comment by benoitgrelard** [comment]
At a glance I don't think it would need that logic that tooltips have where it's global and you can jump from one to the other quickly without having a delay. I think that might be distracting because they're usually much bigger.

**Comment by andy-hook** [comment]
> It should only ever display content that is available on the href.

What would be an incorrect use case example? at a glance I'm unsure how this might relate to the component api, or are we just referring to usage guidelines?

**Comment by benoitgrelard** [comment]
I think it is more about guidelines.
The reason we say this is that the content inside the hover card cannot really made accessible to keyboard or screen reader users. Therefore, it shouldn't be primary content, but rather content that can be accessed another way (like visiting a link with that same info behind it).

**Comment by colmtuite** [comment]
It might just be usage guidelines yeah. This isn't an ARIA component, it's just kinda popped up everywhere around the web in the past few years. But it's not really possible to make it accessible, so we will just need to wing it, and do our best to document good guidelines.

I'm thinking, let's say someone puts it on a a button avatar like

```
<HoverCard as={Slot}>
  <Avatar as="button" />
</HoveCard>
```

(or however code works)

and it just displays log out links and stuff, that aren't on another page. Something like that.

**Comment by andy-hook** [comment]
Makes sense! will do some quick research and report back

**Comment by andy-hook** [comment]
I had a quick look at other uses of this pattern out in the wild

#### Dribbble
![image](https://user-images.githubusercontent.com/11708259/114035992-8f70da00-9877-11eb-8f17-ed092ff2aa4c.png)

#### Github
![image](https://user-images.githubusercontent.com/11708259/114036405-f2fb0780-9877-11eb-8ddf-3e0c39171479.png)

#### Behance
![image](https://user-images.githubusercontent.com/11708259/114036472-01e1ba00-9878-11eb-9b6d-5d67b83b9634.png)

#### Wikipedia
![image](https://user-images.githubusercontent.com/11708259/114036953-67ce4180-9878-11eb-904c-e573e330302e.png)

Interestingly, wikipedia positions content based on the entrance coord:

https://user-images.githubusercontent.com/11708259/114038329-afa19880-9879-11eb-81ac-594217ff610d.mov

My initial thought is that we don't need this complexity and that a `side` prop (ala [Tooltip](https://radix-ui.com/primitives/docs/components/tooltip#content)) would suffice?

#### Visibility Delay
This is interesting because these cards might want to make lazy requests / async sides for content or assets, you could argue that you might want to change the visibility delay independently from the trigger for controlling perceived performance? perhaps that's not this components responsibility?

#### Dynamic content size
Do we want to provide some type of internal mechanism (resize obs?) that will update the collision if the content size changes after first render? perhaps this isn't necessary but I can imagine some scenarios where there is an async content update that screws with collision, or is `popper` smart enough to deal with this now?

The other points in the original outline look good to me. Having looked at common uses I think it's safe to expect additional interactive elements within cards and to make sure our visibility logic is tactile and doesn't interfere.

I guess if we wanted a distinction we would say that the presence of other interactive elements is what differentiates this implementation from a `Tooltip`? I (surprisingly) couldn't find many good examples of it in other popular libraries, please point me at some if you have though!

**Comment by benoitgrelard** [comment]
This is great Andy!

Regarding delays, do they all feel about the same?
Do some have an unmount delay? Or would we say that's just part of the exit animation?

>Visibility Delay
This is interesting because these cards might want to make lazy requests / async sides for content or assets, you could argue that you might want to change the visibility delay independently from the trigger for controlling perceived performance? perhaps that's not this components responsibility?

If I understand correctly you're saying that they may want to delay opening based on loading something asynchronously?
I think you could argue the same with `Dialog` and `Popover` but we haven't done anything internally for this.
I think our opinion would be that in such cases, you control the component and only open it once you've got what you need.

I also think most of the time it's probably better to start showing it and populate after but I can see why some people might not like that, having a loader for a bit etc. All of this kinda falls into the `Suspense` stuff as well. We haven't really looked at all there for now. I would say for our first version we should follow what we've done with other primitives and not worry about it yet.

As far as user feedback, we haven't had any requests around that yet.

>Dynamic content size
Do we want to provide some type of internal mechanism (resize obs?) that will update the collision if the content size changes after first render? perhaps this isn't necessary but I can imagine some scenarios where there is an async content update that screws with collision, or is popper smart enough to deal with this now?

`Popper` handles all of this automatically already, so if your content dynamically changes size, it would reposition itself if necessary.

>I guess if we wanted a distinction we would say that the presence of other interactive elements is what differentiates this implementation from a Tooltip?

Whilst it's true that `Tooltip` shouldn't have interactive elements in them, and that `HoverCard` can have some. I don't think you can think of them as analogous with just that difference though. In my mind `Tooltip` behaves more globally, only one at a time and also has properties that I think don't apply here (like bypassing delay in some cases, etc).

**Comment by andy-hook** [comment]
> Regarding delays, do they all feel about the same?
> Do some have an unmount delay? Or would we say that's just part of the exit animation?

They are pretty similar on the mount and map well to user intent. The unmount varies, some have no timeout on dismount, anecdotally I prefer a short delay on the exit to account for imprecise pointers.

e.g.

https://user-images.githubusercontent.com/11708259/114064937-0915c180-9892-11eb-8e19-25e939d155ea.mov

> I think our opinion would be that in such cases, you control the component and only open it once you've got what you need.

Sounds sensible to me

> I also think most of the time it's probably better to start showing it and populate after but I can see why some people might not like that, having a loader for a bit etc.
>
> I would say for our first version we should follow what we've done with other primitives and not worry about it yet.

Totally agree with this


> `Popper` handles all of this automatically already, so if your content dynamically changes size, it would reposition itself if necessary.

Great!


> Whilst it's true that `Tooltip` shouldn't have interactive elements in them, and that `HoverCard` can have some. I don't think you can think of them as analogous with just that difference though. In my mind `Tooltip` behaves more globally, only one at a time and also has properties that I think don't apply here (like bypassing delay in some cases, etc).

That's fair, on the subject of the delays – do you think we should expose them to consumers with some standardised defaults? or not provide them at all? I can see an argument for and against, I'm not familiar with all of our principles on this and how opinionated we tend to be.

**Comment by benoitgrelard** [comment]
> The unmount varies, some have no timeout on dismount, anecdotally I prefer a short delay on the exit to account for imprecise pointers.

I think what we're seeing here on google calendar is actually a wider hit area rather than a timer-based interaction. You can verify this by leaving your mouse outside for a while. That's another way to do it obviously, you can have a pseudo element behind that's slightly larger.

> on the subject of the delays – do you think we should expose them to consumers with some standardised defaults? or not provide them at all? I can see an argument for and against, I'm not familiar with all of our principles on this and how opinionated we tend to be.

We have recently exposed props for them on `Tooltip` so I think we'd do the same here for sure.

**Comment by andy-hook** [comment]
> I think what we're seeing here on google calendar is actually a wider hit area rather than a timer-based interaction.

Interesting, in some ways this could be problematic if the "offset" overlaps unrelated elements.

> We have recently exposed props for them on `Tooltip` so I think we'd do the same here for sure.

Good to know 👍

**Comment by benoitgrelard** [comment]
>Interesting, in some ways this could be problematic if the "offset" overlaps unrelated elements.

Yeah that's very true. To be honest inspecting the DOM I can't see such element anywhere, so if they're doing something like that they must be doing their own hit-test instead comparing mouse position with getBoundingClientRect.

**Comment by jjenzz** [comment]
> anecdotally I prefer a short delay on the exit to account for imprecise pointers.

Same and it looks timer based to me 

https://user-images.githubusercontent.com/175330/114164855-aec54100-9923-11eb-8ec4-2bf0cf465d61.mov

**Comment by benoitgrelard** [comment]
Ha great! That explains it all! I somehow assumed the trigger was just the name, but now I can see you can hover the entire row. 👍

**Comment by andy-hook** [comment]
Here's what i'm thinking, mostly riffing on what we have in `Popover` and `Tooltip`..


Basic usage

```
<HoverCard.Root>
	<HoverCard.Trigger enterDelayDuration={700} exitDelayDuration={400}>
		Hover trigger
	<HoverCard.Trigger/>

	<HoverCard.Content>
		<h3>Andy</h3>
		<p>Favourite Lemur: Ring-tail</p>

	  	<HoverCard.Arrow />
	</Popover.Content>
</HoverCard.Root>
```

Controlled, slotted

When controlled the enter / exit delays won't apply, any thoughts?

```
const [cardOpen, setCardOpen] = useState(false)

<HoverCard.Root open={cardOpen} >
	<HoverCard.Trigger as={Slot}>
		{children}
	<HoverCard.Trigger/>

	<HoverCard.Content>
		{content}
		
		<HoverCard.Arrow />
	</Popover.Content>
</HoverCard.Root>
```


### Root
- **defaultOpen**

- **open**

- **onOpenChange**

- **enterDelayDuration**
– The duration between the mouse entering the `trigger` and the HoverCard opening.

- **exitDelayDuration**
– The duration between the mouse leaving the `content` *and* `trigger` area before the HoverCard closes.

### Trigger
- **as**

### Content
- **as**

- **anchorRef**

- **portalled**

- **side** – `top | right | bottom | left`

- **sideOffset**

- **align** – `start | center | end`

- **alignOffset** – An offset from the `start` or `end` alignment.

- **avoidCollisions**

- **forceMount**

- **collisionTolerance**

### Arrow

[See Tooltip](https://radix-ui.com/primitives/docs/components/tooltip#arrow)

## Animation
[See Popover](https://radix-ui.com/primitives/docs/components/popover#styling)

## Keyboard
On reflection I'm not sold on the need to bind `Escape` to close, I havn't seen this implemented anywhere else and it doesn't feel like the right choice for a purely hover based interaction. Other bindings are not nessesary as we don't want to handle focus or trigger on tab.

**Comment by andy-hook** [comment]
> * I wonder if `exitDelayDuration` is just really an exit animation with a delay? But I guess you may still want to have that slight delay so you can come back on it quickly even if you're not transitioning unmount

My thinking was `exitDelayDuration` refers to the grace period after mouse leaves, prior to unmount. I need to check how we are currently handling animation hooks, I typically consider animation separate from user intent. 

> * how did you get to 400 for exit? just feeling what's feels good to avoid imprecise pointer stuff?

Arbitrary eyeballing, the default should probably be longer actually, will need to test

> * Do we think `HoverCard.Trigger` should render a `a` by default? What do we think make sense here?

Yeah I think that's appropriate

> * heads up, we're currently changing the `anchorRef` bit so you'll end up with an optional `HoverCard.Anchor` part instead

Thanks for the nudge

> * Regarding `Escape` that's interesting yeah, I don't see it anywhere either. But that said I also don't see it on a lot of tooltip implementations. But yeah perhaps it's different as it's only ever opened via hover, I could get behind that.

I didn't realise this behaviour was also on `Tooltip`, no strong opinions tbh, maybe it's a consistency question.

**Comment by colmtuite** [comment]
> I didn't realise this behaviour was also on Tooltip, no strong opinions tbh, maybe it's a consistency question.

Tooltip can trigger on focus too though. I think in that case, ESC makes sense. It might be different for this component which can only trigger on mouseover.

If we agree it is, there might be a case to be made that ESC should only close a Tooltip when it has been triggered by focus?

**Comment by benoitgrelard** [comment]
> If we agree it is different, there might be a case to be made that ESC should only close a Tooltip when it has been triggered by focus?

This is something we changed recently after you raised it that it should close on escape all the time. As far as I can tell other libs like reach and spectrum also do it.

**Comment by colmtuite** [comment]
Yes I think it should close on ESC. I'm just presenting cases and raising arguments to help the debate.

**Comment by andy-hook** [comment]
> Tooltip can trigger on focus too though. I think in that case, ESC makes sense. It might be different for this component which can only trigger on mouseover.

Good point, I'm leaning towards no binding. You don't ever interact with HoverCard via keyboard and if you did it would be a one way operation before having to use a pointer to show it again.

**Comment by benoitgrelard** [comment]
Yeah I think I agree with you both:
- escape on tooltip
- no escape on hover card

**Comment by jjenzz** [comment]
I also paused on the `HoverCard.Trigger` being an `a` for a second but then realised that we're saying the `HoverCard` use-case is to preview information hidden behind a link. If that is the case, I agree it should be an `a`.

I like the `enterDelayDuration` and `exitDelayDuration` props. Regarding the following though...

> When controlled the enter / exit delays won't apply, any thoughts?

I think uncontrolled and controlled should behave the same, so delays would apply in both. It feels weird to me that parts of the API would suddenly become redundant simply because of switching between controlled/uncontrolled. If they don't want delays then they can do:

```jsx
<HoverCard.Root open={open} onOpenChange={setOpen} enterDelayDuration={0} exitDelayDuration={0}>
 // ....
</HoverCard.Root>
```

Thoughts?

**Comment by benoitgrelard** [comment]
That's an interesting one… 🤔 I did miss that.
I can see what you're saying Jenna in terms of parts of the API becoming redundant.
I suppose perhaps Andy was thinking about when controlling the open state from outside entirely delays wouldn't apply, in which case I think I agree. However, I do think delays would apply, even when controlled, when the interacting with the trigger part.

**Comment by andy-hook** [comment]
> I think uncontrolled and controlled should behave the same, so delays would apply in both. It feels weird to me that parts of the API would suddenly become redundant simply because of switching between controlled/uncontrolled.

I agree. I was just playing with this and it didn't feel right to apply different defaults for controlled vs uncontrolled. Original thinking was that a user would want full control when controlling, but they could achieve that by removing the delays themselves.

> If they don't want delays then they can do:
> 
> ```js
> <HoverCard.Root open={open} onOpenChange={setOpen} enterDelayDuration={0} exitDelayDuration={0}>
>  // ....
> </HoverCard.Root>
> ```

Something I've realised with my current implementation is that using `exitDelayDuration={0}` makes the `Content` inaccessible to the pointer – the timer expires faster than you can physically hover over the `Content` to reset it. I'm wondering what to do here, some first thoughts could be to:

- Impose additional layout so that the "hitzone" of `Content` always meets the trigger (Content positioning offsets applied via `padding` values for example)
- Apply more complex pointer logic that assess the intent of the movement (velocity, acceleration etc) and decides when to apply timer props
- Simply highlight it as a constraint in the docs

Have you solved for similar before?

**Comment by benoitgrelard** [comment]
>Something I've realised with my current implementation is that using exitDelayDuration={0} makes the Content inaccessible to the pointer – the timer expires faster than you can physically hover over the Content to reset it.

Yeah, I'm torn…

I feel like that it is expected. As in, by setting this prop to 0s, it's pretty obvious that it would have that effect.
Generally we like to keep things as simple as possible, especially for initial release, so we could ship with a good default value for exit delay, document the caveat of using 0s, then we wait to hear feedback on all this as people come up with their use-cases. 

On the other hand, I'm starting to think that perhaps there are 2 different scenarios here, and that the exit delay only applies to one of them. It seems to me that exiting the trigger could instantly close it, and that the delay is mostly here as a way to allow for pointer wobble when exiting and re-entering the **content** part.

So in a way, I feel like the exit delay prop might be better placed on the content itself.

Then it's debatable whether the trigger part would also need an exit delay prop. But the point I think is that exit delay or not, when considering the trigger, arguably you should be able to hover from the trigger to the content without having the content closing on you.

**Comment by andy-hook** [comment]
Thanks for the feedback on this @benoitgrelard, I thought about it some more and I'm leaning into simpler the better. If a user wants a `0` delay on exit they can do this and everything does work predictably, as expected. We expose all the options needed to create working abstractions without exit delays e.g. offsets are fully customisable.

Happy to discuss if we think we need to account more for this, for now [I've raised a PR here](https://github.com/radix-ui/primitives/issues/387)

**Comment by benoitgrelard** [comment]
@andy-hook Good call, that's what we generally go for, keep things as simple as possible.

**Comment by andy-hook** [comment]
@benoitgrelard @jjenzz something we didn't discuss was the handling of touch events, what do we think the expectation is on mobile devices? should we be doing anything special here?

**Comment by benoitgrelard** [comment]
Seeing as these are purely for enhancement of info that should be accessible via the link, I would be tempted to say on mobile it shouldn't do anything at all…
