### ISSUE TITLE
Render prop API

### ISSUE THREAD

**Issue by itsMapleLeaf** [radix-ui/primitives#498]
### Overview

Primitive components should support a render prop API as an alternative to the `as` prop.

- This would allow making a clean and convenient façade based on `cloneElement`, example:

  ```tsx
  function MenuItem({ children }) {
  	return (
  		<RadixMenu.Item>{(item) => cloneElement(children, item)}</RadixMenu.Item>
  	)
  }

  const example = (
  	<Menu>
  		<MenuItem>
  			<button>Do something</button>
  		</MenuItem>
  		<MenuItem>
  			<a href="...">Go somewhere</a>
  		</MenuItem>
  		<Modal>
  			<MenuItem>
  				<ModalTrigger>Show a modal</ModalTrigger>
  			</MenuItem>
  			<ModalContent>hi lol</ModalContent>
  		</Modal>
  	</Menu>
  )
  ```

- Allows other flexible custom API overrides, like using the render props in the UI, without the need to control the component externally

  ```tsx
  function DrawerPanel({ children }) {
  	return (
  		<RadixDialog.Content>
  			{(content) => (
  				<div
  					{...content}
  					className={`drawer ${content.open ? "open" : "closed"}`}
  				>
  					{children}
  				</div>
  			)}
  		</RadixDialog.Content>
  	)
  }
  ```

- Beyond simple cases, the `as` prop can be harder to reason about. From my experience, render prop APIs make it clearer which props are going where and on what.

- Render prop APIs are generally easier to type and add overrides for. To forward an `as` prop to a component, one requires mirroring the generic signature, which is hard to do correctly:

  ```tsx
  // I'm not sure what to do here; it's late and I definitely don't have enough brain energy to figure it out
  function Example<As extends keyof JSX.IntrinsicElements>(props: {
  	as?: As
  	???
  }) {
  	return (
  		<SomeOtherWrapper>
  			<Dialog.Trigger {...props} />
  		</SomeOtherWrapper>
  	)
  }
  ```

  Versus this, which gives me the capability to use any element/component without too much pain

  ```tsx
  function Example({ children }: { children: ReactNode }) {
  	return (
  		<SomeOtherWrapper>
  			<Dialog.Trigger>
  				{(trigger) => cloneElement(children, trigger)}
  			</Dialog.Trigger>
  		</SomeOtherWrapper>
  	)
  }
  ```

### Examples in other libraries

[Here's a good example from Reakit.](https://reakit.io/docs/menu/#abstracting)

### Who does this impact? Who is this for?

For any user who wants a little more power and/or choice in using the library, more cleanly and explicitly (imo) than what the `as` prop can do.

### Additional context

An increase in API complexity seems like a potential downside here. Still seems worth?

**Comment by benoitgrelard** [comment]
Hi @itsMapleLeaf, thanks for bringing this up.

I think there are really 2 different questions here:

- first, the ability to render your own element rather than using the `as` prop

On this point, the library exposes a `Slot` component which you can use to turn any part into a slot that receives an element (instead of that part rendering the element itself). You can read more about is on our documentation: https://radix-ui.com/primitives/docs/utilities/slot

- second, the ability to get access to some underlying state in a render prop

For this one, this is something we have considered but so far are not keen on doing as it adds to the API surface. Our take on it is that you can already do everything you need by controlling the component, without a need to change the API. Here's another issue where we discussed this previously: #391

Thanks! 🙏

**Comment by itsMapleLeaf** [comment]
Ah, looks like I missed this `Slot` API, which, at a glance, seems like exactly what I need. I'll probably be using this a lot 😅 I'll see how it works in practice. Thanks for your time 😄
