### ISSUE TITLE
RadioItem does not permit "as"

### ISSUE THREAD

**Issue by tarngerine** [radix-ui/primitives#553]
### Current Behavior

<img width="778" alt="image" src="https://user-images.githubusercontent.com/1629901/110869633-6d903180-8290-11eb-9d2c-f21757ac896e.png">

### Expected behavior

It should allow me to use as via string or component

### Reproducible example

https://codesandbox.io/s/reverent-mccarthy-kv6v8?file=/src/App.tsx

### Suggested solution

add "as" to types, as per docs
<img width="903" alt="image" src="https://user-images.githubusercontent.com/1629901/110869674-813b9800-8290-11eb-8101-7017aa75256e.png">

**Comment by smhutch** [comment]
I have also faced this issue, but managed to find a workaround. I believe `RadioGroup.Item` does accept an `as` prop as documented, but it's hard to create wrapper components which correctly support the `as` and `css` types.

In my project I needed to implement something like this:

```tsx


interface DropdownItemProps
  extends Omit<ComponentProps<typeof DropdownMenu.Item>, "as"> {
  // some other props specific to my own abstraction
}
type PolymorphicDropdownItem = Polymorphic.ForwardRefComponent<
  "div",
  DropdownItemProps
>;

export const DropdownItem = React.forwardRef(({ className, ...props }, ref) => (
  <DropdownMenu.Item
    {...props}
    ref={ref}
    className={clsx(className, dropdownItem.className)}
  />
)) as PolymorphicDropdownItem;
```

I got this approach from a comment @peduarte left on Discord, which pointed me towards the approach taken internally at Modulz: https://github.com/radix-ui/design-system/blob/master/components/Heading.tsx

**Comment by benoitgrelard** [comment]
I haven't had a chance to look at this issue in details, but if what you are all seeing is that the `as` replacement actually works (ie. the resulting DOM is correct) but it's the types that are complaining then 100% @smhutch would be right.

If you want to wrap a part whilst still maintaining polymorphism, you will need to use our polymorphic package. This is what we do internally for all of our components.

This is how we would suggest doing it:

```
```

**Comment by benoitgrelard** [comment]
> I have also faced this issue, but managed to find a workaround. I believe `RadioGroup.Item` does accept an `as` prop as documented, but it's hard to create wrapper components which correctly support the `as` and `css` types.
> 
> In my project I needed to implement something like this:
> 
> ```tsx
> interface DropdownItemProps
>   extends Omit<ComponentProps<typeof DropdownMenu.Item>, "as"> {
>   // some other props specific to my own abstraction
> }
> type PolymorphicDropdownItem = Polymorphic.ForwardRefComponent<
>   "div",
>   DropdownItemProps
> >;
> 
> export const DropdownItem = React.forwardRef(({ className, ...props }, ref) => (
>   <DropdownMenu.Item
>     {...props}
>     ref={ref}
>     className={clsx(className, dropdownItem.className)}
>   />
> )) as PolymorphicDropdownItem;
> ```
> 
> I got this approach from a comment @peduarte left on Discord, which pointed me towards the approach taken internally at Modulz: https://github.com/radix-ui/design-system/blob/master/components/Heading.tsx

btw @smhutch if all you need is wrap the part to add a className, we actually have a much simpler way to extend a part whilst retaining polymorphism, see here: https://radix-ui.com/primitives/docs/overview/styling#styling-a-part

Basically you can do this:

```tsx
const DropdownItem = extendPrimitive(DropdownMenu.Item, {
  className: 'my-dropdown-item',
});
```

**Comment by benoitgrelard** [comment]
@tarngerine let me know if that's what you were after or if there's actually an issue with the `as` prop here. Feel free to close the issue if it's resolved for you. 👍

**Comment by tarngerine** [comment]
i'll take a look again later, thanks! do y'all have a good resoruce for super beginner non-CS major for "polymorphism" in this context? its' something i've heard but it's always sounded very scary

**Comment by benoitgrelard** [comment]
> i'll take a look again later, thanks! do y'all have a good resoruce for super beginner non-CS major for "polymorphism" in this context? its' something i've heard but it's always sounded very scary

I can't think of one right now but I can try to explain!

**Polymorphism** can be defined as **the ability of an object to take on many forms**.

### JS

In our context, it is linked to the `as` prop, which means that we can make a particular component render `as` something else. At a basic level, that's all it really is. For example, you can think of a `Text` component which may render a `span` by default, but as a user you might have more knowledge where you use it and want to render it as an `h1` (another html tag).

The next level is that it doesn't necessarily has to render as an html tag, it could be rendered as another component. A good example of that is when you have a component that renders a `a` normally, but you may want to render it `as` a `Link` component from `react-router`, so that it actually has all the behaviour from it and navigates as expected.

If we're only talking about JS, then that's kinda where it stops, so that's fairly painless.

### TS 

Where it all becomes super complex and frankly a can of worms is unfortunately when you involve types (TypeScript).
This is because now if you truly want your component to behave like a polymorphic component (ie. it takes on another form), then the types need to dynamically adapt. For example, if you have a `Trigger` component which renders a `button` by default, you would get autocomplete and type validation for say the `type` attribute, etc. If you rendered it `as="a"` now you would expect to not get `type` but get things like `href` in autocomplete and type validation.

This is inherently where most of the complexity lies for us and thus why we need to do this whole polymorphic dance with the types. Unfortunately right now there's no way to have this whilst not leaking all this implementation details onto the users. This is a combination of the `React.forwardRef` api and inherent limits of TS.

**Comment by smhutch** [comment]
Thanks @benoitgrelard, and great explanation. About `extendPrimitive`, that's great to know. I hadn't found that helper yet. Unfortunately I need to merge, not override the `className` prop. If I use `extendPrimitive`, I risk styles breaking if a consumer passes any random className as a prop.

**Comment by benoitgrelard** [comment]
> Thanks @benoitgrelard, and great explanation. About `extendPrimitive`, that's great to know. I hadn't found that helper yet. Unfortunately I need to merge, not override the `className` prop. If I use `extendPrimitive`, I risk styles breaking if a consumer passes any random className as a prop.

Oh that's a great point @smhutch! @jjenzz and I had actually talked about this, the fact we should merge `className`, `style`, etc. It seems we then overlooked it and forgot to include that as part of our process forming this API. We'll get back on this one soon.

**Comment by benoitgrelard** [comment]
@smhutch on this, for now we have decided to keep the `extendPrimitive` API the same, that's why we pass an object with `defaultProps` because they behave like default props (can be overridden). The merging situation is because `className` is a single attribute. We are updating our styling docs accordingly to show how you'd do it when you want `className` with merging, or if you want to use `extendPrimitive` with data attributes as selectors.

https://github.com/radix-ui/website/pull/119

**Comment by benoitgrelard** [comment]
@tarngerine I will now close this issue as I believe the matter has been addressed. Please feel free to re-open if you think there's still an issue.
