### ISSUE TITLE
[Popover] Better collision prevention

### ISSUE THREAD

**Issue by vladmoroz** [radix-ui/primitives#557]
## Feature request

When using `align="start"` or `align="end"` the alignment may flip abruptly when a collision happens. Sometimes this introduces just another collision, which neither uses the available space efficiently, nor keeps the preferred alignment intact.

For example, when using `align="start" side="right"` the desired behaviour would be:
- If `align="start"` results in a collision, try `align="center"`
- If `align="center"` does not resolve the collision, try `align="end"`
- If `align="end"` does not resolve the collision, revert to `align="start"`

Current behaviour:

https://user-images.githubusercontent.com/8441036/111156630-a5ec8400-859e-11eb-906a-3fc953ce4a10.mov

<img src="https://user-images.githubusercontent.com/8441036/111156713-bac91780-859e-11eb-9799-be7985342137.png" width="541" />

**Comment by bkrausz** [comment]
> For example, when using `align="start" side="right"` the desired behaviour would be:
> 
> * If `align="start"` results in a collision, try `align="center"`
> * If `align="center"` does not resolve the collision, try `align="end"`
> * If `align="end"` does not resolve the collision, revert to `align="start"`

IMO the desired behavior is to try and remain as close to the intended placement while avoiding the collision, so rather than re-aligning to a completely different value, offset such that the popper is against the edge.

For example, Popper.js with a middle-right placement:

Normal
<img width="257" alt="Screen Shot 2021-11-11 at 11 47 26 AM" src="https://user-images.githubusercontent.com/364070/141359574-c73ac359-c055-41e5-80c3-c67d31f6c3b6.png">

Hitting bounds
<img width="271" alt="Screen Shot 2021-11-11 at 11 48 14 AM" src="https://user-images.githubusercontent.com/364070/141359667-5390df4a-cf8b-4d82-8d11-9faecf1f737d.png">

**Comment by Darko** [comment]
Facing a similar situation here with a dropdown component that is `align="start"` and `side="bottom"`. In my case, this opens the content from the left side. As the viewport gets smaller and a collision happens, it moves over to `align="end"`, but since the position of the trigger is very close to the start of the viewport, it overflows outside the window.

I would expect that it would stick no further than the start edge. This way I could limit the size of the content, and potentially involve scrollbars when that's ok if the screen is of smaller size than necessary for my content.

[CodeSandbox](https://codesandbox.io/s/laughing-frog-yc7k8?file=/src/App.js)

Here I'd expect that it would then subtract the overflowing amount and push it to the preferred side (start/end).

Hope this makes sense.
