### ISSUE TITLE
[DropdownMenu] Can't enable scroll for `DropdownMenu` in overflow scroll container

### ISSUE THREAD

**Issue by vladmoroz** [radix-ui/primitives#566]
## Bug report

`<DropdownMenu.Content disableOutsideScroll={false}>` doesn't do anything when the Dropdown is inside a scrollable container
https://codesandbox.io/s/gifted-wave-xg810

**Comment by benoitgrelard** [comment]
@vladmoroz I realised that this is kinda an overlap.
By default `Dropdown.Content` also has `disableOutsidePointerEvents={true}`.
That obviously also in turns neutralises scroll events, so that kind of makes sense in a way.
It's a bit annoying cause now we have 2 props that kinda do the same thing partially…

cc @jjenzz

**Comment by jjenzz** [comment]
I also discovered an additional issue while looking into this. The `react-remove-scroll` lib we're using doesn't actually remove the scrollbar from the custom scroll container (I can still see it if scrollbars are visible). It just "feels" like it has because:

> By default `Dropdown.Content` also has `disableOutsidePointerEvents={true}`. 
> That obviously also in turns neutralises scroll events, so that kind of makes sense in a way

It seems correct to me that if pointer events are disabled you wouldn't be able to scroll but I wonder if the modality work we're doing would make this much simpler. Instead of saying `disableOutsideScroll={false}` we would use `modal={false}` which would also enable pointer events?

**Comment by benoitgrelard** [comment]
Yeah I believe you are right in the fact that the combination above is rendered inexistent with the current modality work.
ie. you cannot have `disableOutsidePointerEvents={true}` AND `disableOutsideScroll={false}`.
