### ISSUE TITLE
Add type for `onOpenAutoFocus` to ContextMenu.Content

### ISSUE THREAD

**Issue by steveruizok** [radix-ui/primitives#569]
## Bug report

The `ContextMenu.Context` element has a (useful) prop, `onOpenAutoFocus`, that fires when the context menu opens. This prop works but is not included in the component's type.

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/blissful-nightingale-st2mh)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-context-menu | 0.0.10 |

**Comment by benoitgrelard** [comment]
Hey Steve! Fancy seeing you here 🙂
So, this was actually on purpose that we removed the `onOpenAutoFocus` prop from the various menu components.

That prop is here so you can essentially prevent default our default focus management behaviour on open.
It is a useful prop for more generic things like `Dialog` or `Popover` as you may want to focus something specific initially.

However, for menus we were of the opinion that it wasn't needed here, or even potentially harmful to override our behaviour.

Your sandbox is 404'ing so I can't see what you were trying to do, but maybe you can explain and I can get convinced as to why we should still expose anyway.

PS: I'm conscious that it is working anyway in JS-land, so if anything we should omit the prop if we don't think it's useful. But yeah curious if there's a use case we didn't see there.

**Comment by steveruizok** [comment]
Heya 👋 I've updated the CodeSandbox link to the correct URL, though the example only shows the typing issue. Really I just need to know when a menu has opened so that I can set its content dynamically.

Maybe it's easier if I describe my use case for such a prop, and then you can advise on whether a different part of the API is a better alternative?

I'm working on [a project](https://glob-editor-steveruizok.vercel.app/) that where most of the action happens in one big SVG (the "canvas"). Rather than wrapping elements of that SVG tree with triggers (which is how I understand this component to normally work), I would prefer to use just one trigger that wraps the whole SVG. The app already knows which canvas items are selected or hovered; so I can set the menu's content based on that information. 

![Kapture 2021-03-22 at 11 27 29](https://user-images.githubusercontent.com/23072548/111983063-9e2e6180-8b01-11eb-82e2-8743deb7c253.gif)

```js
function ContextMenuContent() {
  const hoveredNode = useSelector(s => s.data.hoveredNode)
  
  return (
    <StyledContent>
      <StyledItem>{hoveredNode?.id}</StyledItem>
    </StyledContent>
  )
}
```

However, if I can avoid it, I'd rather not be changing the content of the menu as a user is hovering around the app while the menu is closed. And I might want to do cancel or disable other things when the menu opens. That's all easy to do as long as I know the state of the menu, which brings me to the `onOpenAutoFocus` prop as a way (the only way?) to know when a menu has opened.

**Comment by benoitgrelard** [comment]
Thanks for explaining the use case. It's clearer now.

So basically you are using these handlers as a way to know when the menu opens/closes because `ContextMenu` isn't controllable.

The reason we haven't made this one controllable is because it doesn't really make sense as you can't really control it open as it's not just the open state but also "where" it opens. That said, it's making me wonder whether we should at least expose an `onOpenChange` callback, even you can't control it, you may want to know when it updated internally.

That being said…

> However, if I can avoid it, I'd rather not be changing the content of the menu as a user is hovering around the app while the menu is closed.

When the menu is closed, we don't render anything, so I don't think it would be an issue. What are you worried about in this case? You can update your items as you hover, open the react devtools and you'll see that the items aren't even in the react tree.

**Comment by benoitgrelard** [comment]
I've tried the above and it seems that there is no issue doing so because it's not rendering them anyway.
But in case you are still wary, you can even do this:

```tsx
<ContextMenuTrigger>
  <div className="node" onContextMenu={() => setActiveNodeId(1)} />
  <div className="node" onContextMenu={() => setActiveNodeId(2)} />
</ContextMenuTrigger>
```

And update your menu content using the active id, then it literally isn't doing anything on hover…

**Comment by steveruizok** [comment]
Thanks Benoit, this sounds like enough to get me going! Having some `onOpen` events sounds useful too.

**Comment by benoitgrelard** [comment]
No problem Steve!

> Rather than wrapping elements of that SVG tree with triggers (which is how I understand this component to normally work), I would prefer to use just one trigger that wraps the whole SVG.

On this, I am curious why you would prefer to go for a single instance and having to change the content dynamically rather than multiple instances? 

Here's a quick sandbox showing multiple instances: https://codesandbox.io/s/contextmenu-svg-vuw8r?file=/src/App.js
I imagine that in an app like yours you'd already have components for each type of node (like the circle one, the "branch" between 2 circles, etc) so each menu would be colocated with its component which IMO makes the whole thing a lot easier to think about.

That's one of the reasons we have designed these APIs around component reuse rather than instance re-use so I'm curious what your train of thought was here in terms of wanting to avoid that 👍

**Comment by steveruizok** [comment]
Thats a good reference! I'll investigate. Thanks for the support. 🙇‍♂️

**Comment by benoitgrelard** [comment]
Closing this as I don't think we would consider adding that prop and have provided other alternatives to the problem you were dealing with.
