### ISSUE TITLE
Explore `inert` attribute

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/primitives#579]
We want to see what the behaviour is when something is `inert`, in particular if it can be focused programmatically or if it's just to do with pointer/focus/blur events.

**Comment by benoitgrelard** [comment]
I have explored this by turning on experimental support in Chrome and for all intents and purposes, sub-trees with inert behave pointer-wise like something that has pointer-events: none. Additionally, if trying to focus anything in there **programatically** the browser simply doesn't do anything and keep focus where it currently is.

**Comment by yumin-chen** [comment]
This issue is from last year and things might have changed since Chrome 102? @benoitgrelard  https://developer.chrome.com/articles/inert/

Maybe it's worth revisiting this issue.

Mozilla's Developer docs says this about `inert`:
> makes the browser "ignore" user input events for the element, including focus events and events from assistive technologies.

It really sounds like this should be applied to the hidden content as `inert` in components like Dialog, Popover, etc, when they're not `open`.

**Comment by benoitgrelard** [comment]
That's not the issue, we do take care of those things just in different ways.
We were looking to see if we support-wise we could use that instead. However I believe we would have to support both or update our support matrix which I don't think we are ready to do at this point.
