### ISSUE TITLE
[tooltip] PopperArrow must be used within Popper

### ISSUE THREAD

**Issue by pacocoursey** [radix-ui/primitives#590]
### Current Behavior

Throws an error when using `Tooltip.Arrow`, exactly as specified in the docs.

<img width="436" alt="Screen Shot 2021-04-10 at 11 45 11 AM" src="https://user-images.githubusercontent.com/34928425/114279492-37aaae00-99f2-11eb-9c00-85031dee0049.png">

### Expected behavior

Shouldn't throw an error when using `Tooltip.Arrow`.

### Reproducible example

https://codesandbox.io/s/determined-https-t877h

### Suggested solution

n/a

### Additional context

n/a

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     Tooltip |   0.0.16      |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by pacocoursey** [comment]
Closing this as I realize it's a documentation issue, the first code snippet shows usage that will immediately break:

```js
import * as Tooltip from '@radix-ui/react-tooltip';

export default () => (
  <Tooltip.Root>
    <Tooltip.Trigger />
    <Tooltip.Content />
    <Tooltip.Arrow />
  </Tooltip.Root>
);
```

Maybe the error could be improved as well to be Tooltip specific.

**Comment by benoitgrelard** [comment]
Hey @pacocoursey, good catch on the documentation issue, I will get it fixed.

Regarding the error, we actually have an issue open about this (#210).

It's been a pet peeve of mine for a while as we can't currently control this message to make it more obvious because it's inside multiple layer of component re-use. So it makes it really cryptic because the users don't interact with `Popper` directly but `Tooltip` is built on top of it.

**Comment by benoitgrelard** [comment]
Fix for the docs: https://github.com/radix-ui/website/pull/131
