### ISSUE TITLE
Checkbox receives double focus with `input: { all: unset }`

### ISSUE THREAD

**Issue by rafgraph** [radix-ui/primitives#605]
### Current Behavior

When using a css reset with `input { all: unset }` and tab through the page, the Checkbox component's `<input hidden>` receives focus before the `<button>` receives focus resulting in double focus when tabbing the page.

I believe the `all: unset` properties that are causing this are `display` and `appearance`, and can be replicated with `input { display: unset; appearance: unset; }`.

### Expected behavior

Only the `<button>` should receive focus, not the hidden input.

### Reproducible example

https://codesandbox.io/s/radix-checkbox-focus-bug-ivm9i?file=/src/App.js

### Suggested solution

I'm not an ARIA expert, but it seems redundant to render a hidden `input` as well as a `<button type="button" role="checkbox" aria-checked="true" etc...>...</button>`, so maybe just not render the `input`?

Alternatively, setting `tabIndex={-1}` on the `input` would also fix this.

### Your environment

`"@radix-ui/react-checkbox": "^0.0.13"`
Chrome `Version 89.0.4389.114 (Official Build) (x86_64)`

**Comment by jjenzz** [comment]
Hi @rafgraph, thanks for reporting this 🙂 

The hidden input is needed for when your `Checkbox` is inside a `form`. It allows the checkbox change to event to propagate to the form's `onChange` event.

I'm thinking the best solution for this would be to use `style={{ display: 'none' }}` on the input so that the inline styles have a higher specificity over any stylesheet styles. 

I'll take a look at this. Thanks again!

**Comment by rafgraph** [comment]
@jjenzz, thanks for the quick reply! I forgot about forms, good point. Using inline styles with `style={{ display: 'none' }}` works too!

**Comment by jjenzz** [comment]
My pleasure! PR is up https://github.com/radix-ui/primitives/pull/606
