### ISSUE TITLE
[FocusScope] Causes unexpected scroll updates in Safari

### ISSUE THREAD

**Issue by vladmoroz** [radix-ui/primitives#611]
## Bug report

https://codesandbox.io/s/focus-lock-scroll-issue-occly?file=/src/App.tsx

When a focusable container has a long list of context menus, popovers, or dropdowns:
- In Safari 14.0, closing the menu completely resets this document scroll position to the start of the list. (Apparently, because Safari doesn't support `preventScroll` option yet).
- In all browsers, opening the menu jerks the scroll slightly in this example. Not sure what causes it, adding any content above the container solves the issue. I haven't run into this bug in the wild and it wasn't the point of this bug report though, just noticed it on the CSB example I built.

**Comment by benoitgrelard** [comment]
Yeah, unfortunately there isn't much we can do about the fact that `preventScroll` isn't supported in some browsers.

You can hover, potentially mitigate the issue app-side. Hard to tell what your real use case is, but for example with that sandbox, if you made the context menu triggers themselves focusable (tabIndex={-1}), focus will go back to it after closing. The reason you will see the big jump in your example is because the top level wrapper div is the thing that will be re-focused.

For the second issue, it's unrelated, it's something to do with collapsing margins by default. In the case of that sandbox here, you can get rid of it by setting `style={{ margin: -1, padding: 1 }}` on your top-level div.

Let me know if that helps, or hit me up on Slack with your real use-case if it doesn't.
