### ISSUE TITLE
[Slider] Thumb loses focus when value changes

### ISSUE THREAD

**Issue by jjenzz** [radix-ui/primitives#615]
Originally reported here: https://discord.com/channels/752614004387610674/803656530259738674/834838499906551869

Strangely this cannot be reproduced in our project or in a CodeSandbox but I was able to decipher that the `Thumb` is unmounting/mounting when the value changes.

We have the following logic that renders the thumb:

```jsx
return value !== undefined ? <SliderThumbImpl ... /> : null;
```

However, some local logging in Darko's project shows that the `value` never changes to `undefined` so I'm baffled. If I remove this conditional though, everything works fine in his project. 

I'm parking for now as we have other priorities but one to investigate when we have time.

**Comment by jjenzz** [comment]
This can be easily replicated by spinning up a new snowpack build from this template https://github.com/snowpackjs/snowpack/tree/main/create-snowpack-app/app-template-react-typescript

```
npx create-snowpack-app react-snowpack --template @snowpack/app-template-react-typescript
```

**Comment by jjenzz** [comment]
Issue also occurring when there are multiple thumbs in a CRA project

**Comment by andy-hook** [comment]
Related https://github.com/radix-ui/primitives/issues/615

I was curious so did some digging on this today. The issue originates in https://github.com/radix-ui/primitives/pull/731 but is not the cause, I think it's an underlying issue that's been obfuscated.

I'm 99% sure it's caused by `StrictMode` exposing non-idempotent code in the [collection index handling](https://github.com/radix-ui/primitives/blob/63b54f0a3b242eeef767587f9714acb9a131dd5f/packages/react/slider/src/collection.tsx#L18-L23), this is why we see it occur in CLI scaffolded projects like CRA, create-snowpack-app etc as they most likely ship with it enabled. `StrictMode` also only runs in development which maps to other reports we've [had in Discord](https://discord.com/channels/752614004387610674/803656530259738674/867299726998765608)

Repro: https://codesandbox.io/s/awesome-wozniak-tsokb?file=/App.js

I think the basis of the problem is that code is running more often than expected in `Strict` making the index [returned in `useSliderCollectionItem` ](https://github.com/radix-ui/primitives/blob/63b54f0a3b242eeef767587f9714acb9a131dd5f/packages/react/slider/src/Slider.tsx#L496-L502) off by one (thus `value === undefined`)

I don't think the rendering assumptions in the collection are true because in StrictMode `render` can be [run multiple times](https://kentcdodds.com/blog/react-strict-mode#it-runs-code-twice) to catch these types of problems.

@jjenzz @benoitgrelard I looked into raising a fix but I don't fully grok why we need to manage the index's like this in order to keep SSR happy?

**Comment by jjenzz** [comment]
This bug was occurring before #731, but #731 definitely made it worse ([which we were aware of](https://github.com/radix-ui/primitives/pull/731#issuecomment-865086624) at the time).

Moving `Slider` to the new `Collection` component might fix it. It's using an old version of our collection logic that was flakey.

**Comment by jjenzz** [comment]
> I looked into raising a fix but I don't fully grok why we need to manage the index's like this in order to keep SSR happy? wanted to write this down now while I remember.

Most collection index solutions require a render first to get all the item refs and then do something like `findIndex` to get the index. That means the `index` isn't known until the second render but SSR doesn't re-render. We need to somehow know the `index` on that initial render and that's what all that complex stuff was _trying_ to do.

This problem has returned in our new `Collection` implementation (cc @benoitgrelard) so for `Slider` we would have issues but the component wouldn't have these more obvious issues at least.

The `Slider` needs the index of each `SliderThumb` to work out which value in the `value` array it is associated with in order to position it in the right place on the range. So, with our new `Collection` approach, the slider would render server-side with all thumbs at `0` on the range and they would move into the right positions when hydrated.

That's probably fine for now though so I'll PR this intermediary step till we can come up with something better.

**Comment by jjenzz** [comment]
Having said all that, I've just tested NextJS SSR with the changes in #794 and it appears to be rendering the thumbs in the right position 🤔  no idea what's going on there but it seems okay.

**Comment by benoitgrelard** [comment]
Hey all! Amazing write-up all round here, made catching up nice easy! ♥️
