### ISSUE TITLE
[DropdownMenu] Imperatively focusing from `Item`'s `onSelect` doesn't work unless delayed a little

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/primitives#622]
This was discussed in #598 and needs to be investigated.
As far as I tested whilst looking at #598, there is nothing happening focus wise, once I disabled the `closeAutoFocus`.

**Comment by benoitgrelard** [comment]
I took a deeper look a this. Here are some notes:
- when `event.preventDefault`ing in `Content`'s `onCloseAutoFocus` and imperatively focus instead, it all works fine
- when `event.preventDefault`ing in `Content`'s `onCloseAutoFocus` but imperatively focus in `Item`'s `onSelect`, it doesn't work
- the reason it doesn't work is because of the order of events. The `onSelect` callback executes "before" the `Content` gets closed, and so focus is still trapped.

One potential solution I could see would be similar to what we do already to allow some specific events to temporarily untrap  or untrap early. Here we could do set up a ref that becomes true when the content gets closed as a result of an item selection. We would then be able to disable trapping a little earlier in these case.

@jjenzz @andy-hook let me know what you think, and if we agree I can go ahead with a fix.

**Comment by jjenzz** [comment]
This sounds like another case of someone needing `wrapped` but not `trapped`. If we split the two then they can have 

```jsx
<DropdownMenu.Content 
	focusWrap={true} 
	focusTrap={false}
	onCloseAutoFocus={event => event.preventDefault()}
>
  <DropdownMenu.Item onSelect={() => somethinElseRef.current.focus()} />
</DropdownMenu.Content>
```

**Comment by benoitgrelard** [comment]
I'm not sure that's the same case. I think it's fair to want focus to be trapped, but to also want to programatically focus when selecting an item. The trouble here is that it's a race condition that we can't get out of because the callback will always have to execute before the item closes.

The `loop` prop on menu is actually the one from roving focus group. In a `Menu` the future `FocusScope` `loop` prop doesn't really matter because there's only ever one thing tabbable.

**Comment by jjenzz** [comment]
> The trouble here is that it's a race condition that we can't get out of because the callback will always have to execute before the item closes.

I don't agree this is a race condition issue. You can't select an item on a closed menu so `onSelect` inherently means the menu is open, they can prevent closing from this event. If you have trapped focus, then focus will be trapped at the time this event occurs because it is open.

It's like calling `.focus()` in a `mousedown` handler. The browser's `mousedown` will call your handler first to check if you prevented default, so your `.focus()` will happen and then it will execute its `mousedown` implementation on the original element. Our `focus` here is happening too soon and needs to move to the next tick: https://codesandbox.io/s/pedantic-pasteur-s8yd4

> I think it's fair to want focus to be trapped, but to also want to programatically focus when selecting an item

I agree this is a fair use-case so, exposing the two props allows them to manage it themselves. Or they move to next tick like the `mousedown` example.

**Comment by jjenzz** [comment]
Here's an example without forcing next tick or fiddling with props https://codesandbox.io/s/focus-from-menu-item-forked-g9zc8

**Comment by benoitgrelard** [comment]
> > The trouble here is that it's a race condition that we can't get out of because the callback will always have to execute before the item closes.
> 
> I don't agree this is a race condition. You can't select an item on a closed menu so `onSelect` inherently means the menu is open, they can prevent closing from this event. If you have trapped focus, then focus will be trapped at the time this event occurs because it is open.
> 
> It's like calling `.focus()` in a `mousedown` handler. The browser's `mousedown` will call your handler first to check if you prevented default, so your `.focus()` will happen and **then** it will execute its `mousedown` implementation on the original element. The `focus` here is happening too soon and needs to move to the next tick: https://codesandbox.io/s/pedantic-pasteur-s8yd4
> 
> In our case, we're calling their `onSelect` handler to see if they prevented close, if not, we call our close implementation which removes trapping and focuses the trigger. If they focus in that `onSelect` handler, it's too soon by design.
> 
> > I think it's fair to want focus to be trapped, but to also want to programatically focus when selecting an item
> 
> I agree this is a fair use-case so, exposing the two props allows them to manage it themselves. Or they move to next tick like the `mousedown` example.

I completely agree with you on all counts! When you know the internals, everything works "as intended". Which is why I said "…it's a race condition that we can't get out of because the callback will always have to execute before the item closes…".

Granted "race condition" was a poor choice of word here 😀 haha

I also agree that we already provide ways to deal with it, which is why I first suggested a solution to them (although I think your last one is even more elegant!)

But my point is rather about expectations. I think it's pretty clear that users feel like they should be able to focus on select, and get confused why they can't. Not only that, but I think fundamentally it feels much more appropriate and direct to want to focus from within an item's `onSelect` rather than indirectly from within the global `onCloseAutoFocus`.

Obviously for now, it all makes sense "by design" but I just wonder if we could potentially change that "design" to make our user's life easier. At the very least if we don't do any change, I think we'd have to provide an example in the docs (yours in particular is very nice, because it tallies up the fact that autofocus should be prevented with the fact there's something else to focus, I ♥️ that!).

**Comment by jjenzz** [comment]
Yeah, I agree it would be nice to at least try to meet people's expectations here but I don't think the solution you have suggested would work because of the event ordering reasons. I'm imagining these steps:

- `onSelect` calls consumer handler 
- handler triggers `.focus()`
- if default isn't prevented we then set `open` to false with a `wasItemSelectedRef`, but wait, `focus()` has already been called so it's too late. 

We would have to do the `setTimeout` internally for them to make sure that their handler only fires **after** we've set some `wasItemSelected` **state** that triggers content re-render to disable trapping, **then** fire their handler 😬  For such an edge case, I'm not sure if it's worth it.

This is why I don't think our knowledge of internals has anything to do with it, it's obvious a menu is open if `onSelect` fires. It can't be responsible for controlling things that you expect to happen **after it is closed**. What's not so obvious is that focus is trapped when open (not just wrapped) which I'm thinking is the underlying issue here. They didn't enable trapping themselves and therefore, can't connect those dots mentally.

**Comment by benoitgrelard** [comment]
You're totally right, it only hit me now that the same limitations would apply to us internally haha

We can revisit once we do the modality changes, but I think ultimately a `DropdownMenu` owes to be `modal` because it's a task you have to complete and can't ignore (ie. picking an item or dismissing it).

But that said, honestly I'm really satisfied by the solution you provided in that sandbox. If that's ok with you I'll post an update on the other issue and I'll send a link to your sandbox as a different solution.

**Comment by jjenzz** [comment]
Yep that works for me :+1: 💛

**Comment by benoitgrelard** [comment]
Updated #598, closing now.
