### ISSUE TITLE
unmountOnExit prop for Popover

### ISSUE THREAD

**Issue by deebov** [radix-ui/primitives#628]
### Overview

A way to enable/disable unmounting the Popover content when open=false. 
We have some cases that the content of Popover has its own state and sometimes it's complex. so instead of re-initiating/resetting the state  we just want to hide the content (and make it inaccessible) when Popover is hidden.

### Examples in other libraries

https://github.com/chakra-ui/chakra-ui/blob/main/packages/transition/src/scale-fade.tsx

### Who does this impact? Who is this for?

We want to switch from @react-aria's overlay hooks to Radix Popover because it supports scrolling outside. We have a design system built using Stitches & react-aria.

### Additional context

Currently Popover.Content has `forceMount` which will not unmount the content if set to true. but issue is it has does not change the accessibility of dom nodes (does not remove aria-hidden from other dom nodes).

**Comment by benoitgrelard** [comment]
Hi @deebov I think what you are after is our `forceMount` prop:

**Comment by benoitgrelard** [comment]
`forceMount` should let you do what you're after I believe, so what you mention may actually be a bug. Would you be able to provide a sandbox demoing your use case? Thanks!

**Comment by jjenzz** [comment]
I'm not convinced this is a Radix issue to solve as it's not advisable to have components re-rendering and running their associated listeners/logic etc. in the background when they're not needed.

If you are trying to maintain some state for your content when the popover is closed, then I would suggest lifting that state so that when it opens, your custom content is __controlled__ by that lifted state.

**Comment by benoitgrelard** [comment]
@deebov let us know if the above is satisfactory.

**Comment by deebov** [comment]
tbh i'd expect that the `aria-hidden` attributes don't depend on `forceMount`'s value but rather depend on the `open` prop. Currently if `open=false` and `foceMount=true` the aria attributes behave as it's `open=true`. 
What do you think?

**Comment by jjenzz** [comment]
I have the same thoughts as last time, sorry for the confusion. My thoughts were the last bit that `forceMount` is only there to **postpone** unmounting so I expected `forceMount=true` to behave as if it were `open=true`. Our intention was that the component would eventually be unmounted by the consumer as it is not good for performance if component lifecycle continues in the background unnecessarily.

However, I realised that we halfway do what @deebov is asking because `forceMount=true` actually behaves as if `open=false` on the most part. It seemed inconsistent that we don't do this when `disableOutsideScroll` is enabled so I was thinking we could maybe make it consistent.

@deebov We've had a catch up about this though and we are reluctant to encourage hidden Radix components for performance reasons. It would also increase complexity in our code purely because of a complexity in **your** architecture when it sounds like it could be solved by lifting the state you want to preserve.

We don't feel this is something that should be solved by Radix Primitives right now but will keep this in mind for the future. Please do let us know if we have misunderstood your use-case though.

**Comment by jjenzz** [comment]
Closing as stale.
