### ISSUE TITLE
Issue with react polymorphic when props are declared as object

### ISSUE THREAD

**Issue by asvny** [radix-ui/primitives#632]
### Current Behavior
Lets say we have code like this 
```tsx
const Button = React.forwardRef((props, ref) => {
  const Component = props.as ?? "button";

  return <Component style={{ color: props.color }}>{props.children}</Component>;
}) as Polymorphic.ForwardRefComponent<"button", { color?: string }>;

type ButtonProps = React.ComponentProps<typeof Button>;
```
This line of code works fine
```tsx
 <Button color="red">Submit</Button>
```
but when we do like this ... you get a type error
```tsx
const btnProps: ButtonProps = {
  as: "a", -> type error
  color: "green"
}
<Button {...btnProps}>Submit</Button>
```

*Usecase* - When you write stories with Args object in Storybook .. it fails. https://storybook.js.org/docs/react/writing-stories/args#story-args

### Expected behavior
Should accept any component or html tag for `as` prop

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/hardcore-thunder-2iyjy?file=/src/App.tsx)

### Suggested solution

No idea on how to solve this issue.

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-polymorphic      |   0.0.11   |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by jjenzz** [comment]
@asvny Thank you for reporting this, however, the error you are seeing is correct. When you use `React.ComponentProps` you lose polymorphism, so prop validation, prop autocompletion and event typing would not work if you use that type to type the props of a component.

Here's a demonstration of the issue using `react-polymorphic-types`:

https://user-images.githubusercontent.com/175330/116985074-e7a6ca80-acc3-11eb-987b-bf998ecea187.mp4

Our types correctly report that it can only be a `button` in your case because your type isn't polymorphic anymore. 

We have an example in our docs of how you can [maintain polymorphism when extending a polymorphic component](https://radix-ui.com/primitives/docs/utilities/polymorphic#extending-a-polymorphic-component) but I'm not sure this helps your use-case. 

I'm not too familiar with the storybook args object but you'd probably have to construct your own type to silence the error with the understanding that this would just be silencing the error and no longer polymorphic:

```jsx
type ButtonProps = Polymorphic.Merge<
  React.ComponentProps<"a">,
  Polymorphic.OwnProps<typeof Button> & { as: "a" }
>;
```

This is probably not what you wanted to hear but I hope it helps in some way 😬

**Comment by asvny** [comment]
Totally understand . forwardRef and generics is hard. Your idea to silence the error helps for time being. Thank you! btw big fan of your work.

**Comment by jjenzz** [comment]
> . forwardRef and generics is hard

💯 😅

> btw big fan of your work.

Aw thank you! Means a lot to us to hear feedback like this ☺️ thank you.

I'm closing this issue for now but please feel free to open another if you spot anything else 🙂
