### ISSUE TITLE
Tooltip.Trigger with Slot not working if we don't spread the props

### ISSUE THREAD

**Issue by Kerumen** [radix-ui/primitives#725]
### Current Behavior

I'm creating a custom tooltip following [the docs](https://radix-ui.com/primitives/docs/components/tooltip#custom-apis) here. If I don't spread the props in my custom component, the tooltip is not working:

```jsx
const Button = React.forwardRef(({ children }, ref) => (
  <button ref={ref}>{children}</button>
));
```

To fix it, I need to spread the remaining props:

```jsx
const Button = React.forwardRef(({ children, ...props }, ref) => (
  <button ref={ref} {...props}>{children}</button>
));
```

I compared with [Tippy.js](https://github.com/atomiks/tippyjs-react) and this library is working even without the props spreading. I think it should be possible to achieve the same behavior here!

### Expected behavior

The tooltip should work even if I don't spread the props in my custom component.

### Reproducible example

Here is a sandbox with Tippy.js as a comparison.

[CodeSandbox](https://codesandbox.io/s/wonderful-goldwasser-5q526)

### Suggested solution

Unfortunately I can't change all of my components one by one to spread the remaining props as it can leads to unexpected behavior. We should investigate why it's not working without the props spreading.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-polymorphic        | v0.0.11        |
|                  | @radix-ui/react-slot | v0.0.10 |
|                  | @radix-ui/react-tooltip | v0.0.18 |
| React            | n/a     | v17.0.1 |
| Browser          | Chrome        | v91.0.4472.101        |
| Node             | n/a     | v12.20.0        |
| yarn             | n/a        | v1.22.10        |
| Operating System | macOS        | v10.15.7        |

**Comment by benoitgrelard** [comment]
This is not a bug, the button you use as the tooltip trigger needs to be able to receive certain props (mostly ref and some event handlers) so the tooltip can be positioned appropriately and can be shown at the right time based on the right events.

I would guess the tippy thing works because it's most likely a vanilla JS lib with a thin react wrapper, so the event handlers are probably outside of the react event system.

Radix UI is a react-first library so we can leverage all of the capabilities of React so that is not something we are currently comfortable doing.

Let me know if I misunderstood the issue though.
