### ISSUE TITLE
Checkbox forwarded Ref should set on Input field and not Button

### ISSUE THREAD

**Issue by emadabdulrahim** [radix-ui/primitives#873]
## Bug report

I tried using Checkbox and pass it a ref, but it seems like the ref is being set on the Button element and not the actual input element itself. This means any library expecting to access the native Input event will not work properly.

I believe the Ref should be set on the hidden input element itself.

https://github.com/radix-ui/primitives/blob/c553b2fe6d29f7415f38c13e6bcbfad052e9c8c1/packages/react/checkbox/src/Checkbox.tsx#L76

**Comment by jjenzz** [comment]
The `Checkbox` is a `button` so you will get a `button`. The `input` is only rendered when it is used within a `form` in order to propagate events. If it wasn't for that, we wouldn't render one at all.

Would you mind helping us understand why you need a reference to the `input`, what is your use-case?
