### ISSUE TITLE
[Dialog] Any way to limit where the dialog appears?

### ISSUE THREAD

**Issue by steveruizok** [radix-ui/primitives#891]
In a component that is meant to be self-contained, any modals are always placed relative to the window. This can lead to menus appearing outside of the self-contained component.

![Kapture 2021-10-06 at 12 34 29](https://user-images.githubusercontent.com/23072548/136195367-f41043ad-e8fb-4563-93c9-0818f54c4e27.gif)

I'm sure that in 99% of cases this wouldn't be an issue, but just in case—is there any way to control where the menu and overlay can be placed?

**Comment by steveruizok** [comment]
> Would this issue give you what you need once solved? #760
> 
> We've been discussing exposing a `Dialog.Portal` part that would allow you to pass a `containerRef` prop to switch the container it renders within.

Yes, I believe that would be the fix. This would also solve a related issue where, because menus are parented to the `body`, they can't receive "scoped" themes—ie themes that have been applied to other containers lower down in the document. For tldraw, this means that the menus are always in light mode, because the dark mode is only applied within the component.

![image](https://user-images.githubusercontent.com/23072548/136414073-5c1bfae6-df3f-4dad-a442-6cdb414c66a2.png)

**Comment by jjenzz** [comment]
@steveruizok We published a [release candidate to trial a new Dialog API](https://github.com/radix-ui/primitives/issues/760#issuecomment-952102287). Does this solve your original issue? We plan to apply this approach across the other primitives when we can so any early feedback will be super helpful.

**Comment by steveruizok** [comment]
Looks like this will work! Great solution, looking forward to the release.

**Comment by steveruizok** [comment]
My only thought is that many apps would use the same container for these sorts of floaty things (dropdown / context menu / dialog / etc), and that there could be a solution that would avoid having t define this portal separately as a child of each floaty thing's root component. However, if it were a choice between the two, I would pick your solution to allow for cases where different floaty things need to be portaled to different containers.

**Comment by benoitgrelard** [comment]
Yeah and if you need to, it should be easy to bake in yourself a provider/context solution around your own components to share that container.

**Comment by jjenzz** [comment]
> My only thought is that many apps would use the same container for these sorts of floaty things

They can't really use the same container unfortunately because it wouldn't know if the `Dialog.Content` was open or not.

We only want to render the portal when these things are open and although the `Portal` part doesn't do much atm (so having it re-rendering in the background when closed wouldn't be the end of the world), we tend to avoid rendering things unnecessarily to prevent us from impacting perf with any future lifecycle logic we might introduce.

We could share some context between a geeneric `Portal` and these portallable things but we try to avoid cross dependencies between components like that otherwise someone that uses `Dialog` without portalling would still have the `Portal` package in their bundle.
