### ISSUE TITLE
[ContextMenu] Controlled state

### ISSUE THREAD

**Issue by Rawnly** [radix-ui/primitives#927]
## Feature request
Allow custom trigger (controlled state) for `ContextMenu`. 

### Overview
In my use case I'm working with `react-konva` and I don't have the ability to use `Root`/`Trigger`.

### Who does this impact? Who is this for?
Everyone who cannot trigger because of canvas/webgl

### Additional context
it could be something like 

```ts
	const [ isOpen ,setIsOpen ] = useState(false)

	<ContextMenu.Content open={isOpen} onClose={() => setIsOpen(false)}>
		...
	</ContextMenu.Coontent>
```

**Comment by benoitgrelard** [comment]
Thanks for that!

That's interesting konva actually provides an `onContextMenu` on these abstract elements (just drawing in canvas) so it could almost work natively.

The reason it doesn't work natively is that as far as I can tell they wrap the native event under a `evt` property, so when we internally do `event.preventDefault` or read `event.clientX` and `event.ClientY` it doesn't have these properties on the konva event object, they are in `event.evt`.

That's a shame because otherwise you could benefit from collocation, ie. having one instance of context menu per shape.

You could do something like this:
https://codesandbox.io/s/contextmenu-react-konva-31jph?file=/src/App.js

Obviously now it's just a single instance of context menu so you're having to swap the content of the menu.

Hope that helps!
