### ISSUE TITLE
[Dropdown Menu] Causes screen offset in mobile

### ISSUE THREAD

**Issue by luisorbaiceta** [radix-ui/primitives#945]
### Current Behavior

When working on small screens, if there is a nested menu that doesn't fit the screen, it offsets the entire layout to fit.

![image](https://user-images.githubusercontent.com/44276180/139530594-6537ec44-2325-41cc-9d80-28702ea92a59.png)

![image](https://user-images.githubusercontent.com/44276180/139530604-57dd762e-96d7-4741-a42d-5bd8f732fbd7.png)

### Expected behavior

Maybe on mobile devices it would be helpful to hover the nested menu over the parent one.

### Your environment

Radix UI Docs website.

**Comment by jjenzz** [comment]
Thank you @luisorbaiceta. 

For anyone following along, this occurs when there is not enough space on either side of the menu so the collision detection preserves its originally intended position. This is definitely something we plan to improve. 

We have another similar issue that may also be fixed by the solution we come up with here https://github.com/radix-ui/primitives/issues/557

**Comment by benoitgrelard** [comment]
We're going to close this one as currently with the new version, in just gets clipped, rather than expanding the body.
More importantly, this is really more down to a product decision, as this component probably shouldn't end up being use on mobile (at least submenus).
