### ISSUE TITLE
Trigger actions with spacebar (in addition to return)

### ISSUE THREAD

**Issue by DaniGuardiola** [radix-ui/primitives#980]
### Overview

Some buttons like dialog or menu triggers work on `click` and on `return` key. I'd like `spacebar` to work too, as it does in other design systems.

- The vanilla `<button>` element, along with a few other input elements, does this: http://fyvr.net/a11y/spacebar-action.html
- Additional info on vanilla elements: https://www.last-child.com/keyboard-accessibility-with-the-space-bar/

### Examples in other libraries

- `useButton` (and `usePress`) from `react-aria` does this. See this blog post for more info: https://react-spectrum.adobe.com/blog/building-a-button-part-1.html 

### Who does this impact? Who is this for?

- End users, who can use `spacebar` to trigger buttons.
- Developers who have a `Button` component that work with `spacebar`. Since your users will be used to having `spacebar` as an option to trigger the action, they will be disappointing when it doesn't work to open a dialog, menu, etc.
- Additionally, some teams (like mine) use something like `usePress` to get consistent pressed states (A.K.A. a JS replacement for `:active`), which shows the pressed state when the button is focused and the spacebar is pressed. Those styles are misleading if it doesn't actually work.

### Additional context

n/a

**Comment by jjenzz** [comment]
Would you mind listing which components you think this applies to? A quick test of the components in our [radix-ui.com](https://radix-ui.com) docs shows that the aforementioned components do already support `space` keypress.

I can see we bind to `onKeyDown` instead of `onClick` for `DropdownMenu.Trigger`, `Tooltip.Trigger` and `Tabs.Trigger` so perhaps you are having some interoperability issues there? I'm not sure why we chose to use that event (@benoitgrelard might know more) but space key is supported as far as I can tell.

Regardless, I'd personally prefer that we simplified some of our logic by ensuring all triggers are `button`s (e.g. `Tabs.Trigger`) and use `onClick` if possible. It's been on my mind for some time.

**Comment by DaniGuardiola** [comment]
I'll take another look later when I'm on the computer, but looking at the code I suspect it might be related to the use of `" "` in the key down handler. I've frequently seen code declaring both that and something like `"spacebar"`, so it might be a cross-browser issue?

Anyway, seems like with the onClick it should be okay.

And btw, I recently came up with a way of achieving pretty decent interoperability between radix and the react-aria hooks. It involved doing some less-than-ideal patching of events to prevent the hook from using `stopPropagation` and `preventDefault` lol. It works fine though, and it now works with radix out of the box.

I'll investigate a little just in case. Thanks!

**Comment by jjenzz** [comment]
The `event.key` property is pretty [well supported across browsers](https://caniuse.com/keyboardevent-key) so I'd be surprised if that was the culprit and the dialog already uses `onClick` so would be helpful if you could give that one another try as it doesn't appear to be a problem on our end 🙏

> It involved doing some less-than-ideal patching of events to prevent the hook from using `stopPropagation` and `preventDefault` lol. It works fine though, and it now works with radix out of the box.

Haha, blimey, that's some serious dedication 😛  Glad you got it figured out.
