### ISSUE TITLE
[Tooltip] wrapping `input` element defaults its type to `button`

### ISSUE THREAD

**Issue by seedy** [radix-ui/primitives#993]
## Bug report

Wrapping a native `input` component without explicit type with a `Tooltip` defaults its type attribute to `'button'`.

This behaviour is not documented, nor should it be expected.

### Current Behavior

Screenshot from demo code reused to wrap native inputs:
![image](https://user-images.githubusercontent.com/3367393/142860216-651c3f6a-49b0-4df0-b24c-bd163925c806.png)

First input element becomes a button

### Expected behavior

I would expect input wrapped with a `Tooltip` to behave just as if it wasn't wrapped, hence having no type forced if none is set.

### Reproducible example

https://codesandbox.io/s/keen-heisenberg-c43y8

**Comment by benoitgrelard** [comment]
Hey @seedy,

Thanks for raising this.
This is not really a bug per-se but rather an unfortunate combination of things which produces this result.

- `Tooltip.Trigger` is a `button` by default, and as such, we always add `type="button"` on those so they don't automatically submit forms when embedded inside a `form` (as this is what happens when no `type` is defined)
- When using `asChild` it will clone the child, here an `input` and pass it all the attributes from the trigger.
- Unfortunately here you end up with `<input type="button" />` which is a valid thing in HTML and produces a button.

We thought about this a few times and took the stance that once you change the underlying element, it's up to you to make the relevant changes when necessary. In general, it isn't really necessary to remove the `type` attribute, although possible with `type={undefined}`.

In this case you would have to simply pass `type="text"` to your `input` and it will solve you issue.

I hope that explains the situation well enough.

@jjenzz, @andy-hook, I still think our decision NOT to do anything special about handling changes in rendered element is the right choice as it could unravel a host of changes to consider otherwise, but I do agree that this specific one is potentially confusing so I wonder what you both think of it.

**Comment by seedy** [comment]
Thanks @benoitgrelard for the explanation.
I understand the reasoning behind the `type="button"` when the trigger is actually a button.

If one passes `asChild`, is there still a need to keep `type="button"` ?

It seems that it may bring unexpected side effects, such as the one I described.

As you may see in my linked code repro, I noticed the workaround forcing a type.
I think it's enough for my need.

I suppose giving your solution as an example for the specific case of a wrapped input might be a useful addition to the Tooltip primitive doc, WDYT?

Thanks again for your time 🙏

**Comment by benoitgrelard** [comment]
> If one passes `asChild`, is there still a need to keep type="button" ?

The most common use case for `asChild` on the `Tooltip.Trigger` is when attaching the behaviour to your own existing styled button (say coming from your design system for example) in which case it is necessary to retain it.

> I suppose giving your solution as an example for the specific case of a wrapped input might be a useful addition to the Tooltip primitive doc, WDYT?

Great suggestion!

**Comment by jjenzz** [comment]
> @jjenzz, @andy-hook, I still think our decision NOT to do anything special about handling changes in rendered element is the right choice as it could unravel a host of changes to consider otherwise, but I do agree that this specific one is potentially confusing so I wonder what you both think of it.

I'm curious why @seedy is trying to attach a tooltip to an `input`. Usually inputs are labelled with `label` so what is the use-case here?

**Comment by seedy** [comment]
> The most common use case for `asChild` on the `Tooltip.Trigger` is when attaching the behaviour to your own existing styled button (say coming from your design system for example) in which case it is necessary to retain it.

As a developer, I would expect handling this myself: to me, if my component has a behaviour by itself, wrapping it with a tooltip shouldn't change that behaviour.

Disabling form submit by adding `type="button"` on a button is something quite common to handle, therefore I would expect to set this myself, before even thinking about wrapping the thing with a tooltip. Do you see what I mean?

**Comment by benoitgrelard** [comment]
Yeah I do, to be fair that's a possibility too, that's something we've been doing since the beginning but I don't remember us discussing much about whether it would be a good idea or not. In many ways, it's not a functionality or accessibility thing, more of a "gotcha" really that is DOM related.

**Comment by jjenzz** [comment]
> wrapping it with a tooltip shouldn't change that behaviour.

Unfortunately that's the whole reason `asChild` exists ... it changes the behaviour of your child to turn it into a trigger for the tooltip but I can see how the `type=button` is a little bit of an edge-case here. Perhaps we're going too far by adding it but we tend to go with what the 90% use-case is likely to be and it's very unlikely that people would put a tooltip on a form submit button.

I do like that this has broken your input though tbh because it is making me wonder why you have a tooltip on your input. I wonder if there are a11y implications there.

**Comment by seedy** [comment]
@jjenzz I have a requirement to display extra information when hovering over a disabled `TextField` (understand `input` and `label`).

I want to add a short hint somewhere around the field, but it shouldn't replace the `label` as it's not giving understanding about user input.

I would give a longer explanation via a tooltip when either input or label get hovered.

Because this information is directly related to the field being disabled, but not of primary importance to user's flow, we don't want to display it permanently. It's more of a "You wonder why it's disabled? Here's the reason." interaction.

I am trying to make the behaviour consistent, whether the field is disabled or not, but I must confess I have no need to display a tooltip when my field is not disabled.

**Comment by jjenzz** [comment]
@benoitgrelard Does that sound like a valid use-case to you? 

My understanding was that `Tooltip` should activate on hover but it wouldn't given that the input is disabled and would fail this criteria https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html#additional-notes

> Content which can be triggered via pointer hover should also be able to be triggered by keyboard focus

I'd also wonder how able-bodied users would know that it is interactive (given that it is disabled) in order to get this information, without some kind of information icon?

I would have thought an `info` icon or something alongside the input that uses `Popover` (like the[ info icon in our props tables](https://www.radix-ui.com/docs/primitives/components/radio-group#root)) would be more accessible.

**Comment by seedy** [comment]
I totally see the a11y issue you just brought @jjenzz.

In this case, I don't understand why you folks document the specific case of a tooltip around a disabled button, as it seems to me it fails WCAG2.1 in the same way. Am I missing something there?

Tbh I'm already pushing my team towards the `info` + `Popover` feature, as I totally agree with you it's more accessible.

I know I'm kind of splitting hairs here, if you feel like the discussion is not bringing positive value to your product, feel free to skip.

It would make sense to me if you gave opinionated recommendations in your documentation, such as:
- recommending to go for icon + popover for use cases with poor a11y (here, Tooltip + disabled inner element)
- allowing people to bypass those recommendations, and giving examples and your insight

**Comment by jjenzz** [comment]
> In this case, I don't understand why you folks document the specific case of a [tooltip around a disabled button](https://www.radix-ui.com/docs/primitives/components/tooltip#displaying-a-tooltip-from-a-disabled-button), as it seems to me it fails WCAG2.1 in the same way. Am I missing something there?

That's a very valid question. That example [stemmed from a user requesting an example on how to achieve it](https://github.com/radix-ui/primitives/issues/555) to match an example from MUI but thinking it through now, I do wonder if we should remove it or at the very least, add a `tabIndex={0}` to the `span`. 

I'd be interested to hear what @benoitgrelard's thoughts are on all of this as he is more experienced on the `Tooltip` side of things!

> if you feel like the discussion is not bringing positive value to your product, feel free to skip.

It's definitely bringing value, we love questions that have us thinking because we like to improve wherever we can 🙂 

> It would make sense to me if you gave opinionated recommendations in your documentation, such as:

On these, I agree we could improve but until we have reports like yours it's hard to know what use-cases to document so please keep them coming if you have more!

I do think that we could make it clearer that if you decide to branch away from the DOM/functionality we provide out of the box then it is up to you to ensure correct a11y though. For example, some people close dropdown menus when opening a dialog from one of its items which means the dialog cannot return focus to the dropdown and position in the document is lost. That's bad for a11y but it's really not clear.

**Comment by ericmatthys** [comment]
I filed https://github.com/radix-ui/primitives/issues/1010 separately, but it may be best to close that. The example I used in that GHI is an anchor tag, which I do think is a pretty common type of trigger for a tooltip.

**Comment by benoitgrelard** [comment]
> Yeah I do, to be fair that's a possibility too, that's something we've been doing since the beginning but I don't remember us discussing much about whether it would be a good idea or not. In many ways, it's not a functionality or accessibility thing, more of a "gotcha" really that is DOM related.

@jjenzz [this comment](https://github.com/radix-ui/primitives/issues/1010#issuecomment-984436712) from @seedy on a similar duplicate issue is solidifying the idea in my mind that we're probably going too far with adding the `type` attribute for "convenience". I'm really starting to think that it would be better left to our users to decide what to do.
