### ISSUE TITLE
Allow Radix primitives to use CSS transitions to suspend unmount while animation plays out (currently only CSS Animation detected)

### ISSUE THREAD

**Issue by cpakken** [radix-ui/primitives#996]
## Feature request
From the docs:
`You can use CSS animation to animate both mount and unmount phases. The latter is possible because the Radix Primitives will suspend unmount while your animation plays out.`

I was curious how this worked and discovered that the implementation in: 
https://github.com/radix-ui/primitives/blob/c86881840053c52cd34483f3c9e2d5a6ac0cba99/packages/react/presence/src/Presence.tsx#L112-L118

If we detect that the animation is from a CSS Transition 
```js
stylesRef.current.transition !== undefined
```
 instead we can use:
```js
node.addEventListener('transitionstart', handleTransitionStart);
node.addEventListener('transitioncancel', handleTransitionEnd);
node.addEventListener('transitionend', handleTransitionEnd);

//There is also a 'transitionrun' event. It might be important regarding the transition state?
```
It probably isn't as straightforward as adding these event listeners as there might be some subtle differences between CSS animation and transitions.

### Examples in other libraries
This component and proposed CSS transition detection is also implemented in the `Transition` component in the HeadlessUI library
https://headlessui.dev/react/transition
https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/transitions/transition.tsx

So you might want to take a look to see if it sparks any inspiration

### Desired Result
This is the CSS Transition implmentation of the example given in the animation docs (https://www.radix-ui.com/docs/primitives/overview/animation)
```css
.dialog-overlay[data-state='open'],
.dialog-content[data-state='open'] {
  opacity: 1;
  transition: opacity 500ms
}

.dialog-overlay[data-state='closed'],
.dialog-content[data-state='closed'] {
  opacity: 0;
  transition: opacity 500ms
}
```

**Comment by cpakken** [comment]
There is also the issue that CSS transitions will handle interruption smoother than CSS animations. 
If a user decides to close and open again before the close animation is complete, CSS Animations will restart at 0% while CSS transition values will keep their transit state while trying to transition back to the closed state.

**Comment by jjenzz** [comment]
We used to support transitions in `Presence` but [unfortunately had to remove it](https://github.com/radix-ui/primitives/pull/537) due to edge-case issues that came with it.

Our `Presence` doesn't do the same thing as the libraries you have linked to as it doesn't add any animation or transition styles for you, it simply postpones the unmount phase **when it detects an animation in your CSS**. 

The "detecting" is the tricky part because transitions needed multiple `requestAnimationFrame`s in our code to detect them and then trigger them on mount whereas animations are much easier to detect and execute on mount: https://codesandbox.io/s/modest-ramanujan-vo7s1?file=/src/App.js.

Usually most things can be achieved with CSS animation so we have historically pushed back on requests to add transition components/support. I'm curious what your use-case is that would benefit from transitions instead?

> If a user decides to close and open again before the close animation is complete, CSS Animations will restart at 0% while CSS transition values will keep their transit state while trying to transition back to the closed state.

This is an interesting point so it would be great to see an example of where you have needed this? There may be some new ways that we can solve for transitions if needed but would need to understand use-cases first. 

Some high level thinking if we were to revisit this:

```css
.fade { transition: opacity 500ms; }
.fade[data-state="open"] { opacity: 1; }
.fade[data-state="closed"] { opacity: 2; }
```
```jsx
<TransitionPresence className="fade">
  <Dialog.Content />
</TransitionPresence>
```

This way `Presence` can instantly detect there is a `TransitionPresence` via context and bypass all the imperative detecting. The only `requestAnimationFrame` it would need would be to make sure that adding `data-state="open"` is delayed slightly after mount.

**Comment by cpakken** [comment]
Adding transition detection seems to be more complicated than I expected. You're right that CSS animations does the job fine and the radix API allows the developer to implement more complex animations if necessary.

My thinking was that the extra option of using transitions may lead to more succinct patterns in addition to keeping the transit state may create smoother experiences. This is basically a 'nice to have' feature as any uses cases that demand more sophisticaed animation interactions can be added through a controlled component. (As intended by the wonderful radix design architecture)

**Comment by jjenzz** [comment]
> Adding transition detection seems to be more complicated than I expected

Haha, welcome to our world 😅 I'm always thinking "sure, that's easy enough" and then realise I couldn't be more wrong.

> This is basically a 'nice to have' feature as any uses cases that demand more sophisticaed animation interactions can be added through a controlled component.

Agreed it would be nice, and tbh if we provided a `<PresenceAnimation />` component too we would be able to reduce some of the complexity in the `Presence` bundle but I think the beauty of `Presence` is that things "Just Work™️" which would be taken away if we provided components instead.

**Comment by DylanVann** [comment]
I created a reproduction for this: https://codesandbox.io/s/radix-animation-not-interuptable-q2tcu1?file=/App.js

If you hit cancel while the `Dialog` is opening you can see it immediately becomes fully opaque/open and then transitions to being closed. It would be ideal if it could stop where it is and transition to being closed, which is how CSS transitions would work

**Comment by andy-hook** [comment]
> If you hit escape while the `Dialog` is opening you can see it immediately becomes fully opaque/open and then transitions to being closed. It would be ideal if it could stop where it is and transition to being closed, which is how CSS transitions would work

Unfortunately this is the nature of key frame animations and we can’t provide a better experience without adding significant complexity (both to the code, and the api)

We’ve found that the vast majority of users find the out-of-box animation support intuitive and sufficient for their needs, though for those who need a higher fidelity option or wish to support more sophisticated micro interactions we recommend using one of the many dedicated animation libraries and [handing over Radix lifecycle via `forceMount`](https://www.radix-ui.com/docs/primitives/overview/animation#delegating-unmounting-for-javascript-animation)

> As there are other good alternatives in the community, this isn't something we will tackle in Radix.

https://github.com/radix-ui/primitives/issues/994#issuecomment-1088770709
